"""Exact realization-equivalence theorem for the continuum tail wall.

CCCLXXXVIII reduced the continuum wall to one unique nonzero tail-operator
gauge class on the fixed avatar. The next exact question is whether this still
leaves several different notions of "realization", or whether the promoted
transport and matter packages are now all equivalent to one and the same
tail-line existence statement.

The exact answer is yes. On the fixed curvature-sensitive tail avatar:

1. the realizable transport residual operators form one one-dimensional line
   generated by the normalized profile
   `(65, 662, 15650/3, 17993/4)`;
2. any nonzero realized point on that line has forced scalar `217`, hence is
   exactly the promoted transport operator;
3. the matter-coupled operator is then exactly the `81`-fold qutrit lift.

So the live continuum wall is equivalent to existence of one nonzero point on
one exact tail-operator line.
"""

from __future__ import annotations

from functools import lru_cache
import json
from pathlib import Path
import sys
from typing import Any


if __package__ in {None, ""}:
    ROOT = Path(__file__).resolve().parents[1]
    if str(ROOT) not in sys.path:
        sys.path.insert(0, str(ROOT))
else:
    ROOT = Path(__file__).resolve().parents[1]

from w33_continuum_tail_operator_normal_form_bridge import (  # noqa: E402
    build_continuum_tail_operator_normal_form_summary,
)
from w33_continuum_tail_scalar_closure_bridge import (  # noqa: E402
    build_continuum_tail_scalar_closure_summary,
)
from w33_continuum_tail_witness_criterion_bridge import (  # noqa: E402
    build_continuum_tail_witness_criterion_summary,
)


DEFAULT_OUTPUT_PATH = (
    ROOT / "data" / "w33_continuum_tail_realization_equivalence_bridge_summary.json"
)


@lru_cache(maxsize=1)
def build_continuum_tail_realization_equivalence_summary() -> dict[str, Any]:
    normal = build_continuum_tail_operator_normal_form_summary()
    scalar = build_continuum_tail_scalar_closure_summary()
    witness = build_continuum_tail_witness_criterion_summary()

    transport = normal["realized_transport_tail_operator_profile"]
    matter = normal["realized_matter_tail_operator_profile"]
    scalar_amp = int(transport["scalar_amplitude"])

    return {
        "status": "ok",
        "tail_operator_line": {
            "dimension": 1,
            "normalized_generator": normal["normalized_tail_operator_profile"],
            "forced_nonzero_scalar": scalar_amp,
            "realized_transport_operator": transport,
            "realized_matter_operator": matter,
        },
        "continuum_tail_realization_equivalence_theorem": {
            "transport_realization_is_equivalent_to_existence_of_a_nonzero_point_on_the_unique_tail_operator_line": (
                scalar["tail_scalar_closure_theorem"][
                    "all_promoted_transport_residual_data_is_generated_by_one_scalar_amplitude"
                ]
                and normal["continuum_tail_operator_normal_form_theorem"][
                    "the_fixed_tail_avatar_has_one_unique_normalized_operator_profile"
                ]
            ),
            "any_nonzero_realized_point_on_that_line_has_forced_scalar_217": (
                witness["continuum_tail_witness_criterion_theorem"][
                    "any_one_promoted_nonzero_transport_tail_observable_recovers_the_exact_scalar_amplitude"
                ]
                and scalar_amp == 217
            ),
            "that_forces_the_exact_promoted_transport_operator": (
                normal["continuum_tail_operator_normal_form_theorem"][
                    "the_realized_transport_tail_operator_is_exactly_217_times_that_normal_form"
                ]
            ),
            "and_the_exact_matter_operator_then_follows_by_the_81_fold_qutrit_lift": (
                normal["continuum_tail_operator_normal_form_theorem"][
                    "the_realized_matter_tail_operator_is_the_exact_81_fold_lift_of_the_transport_operator"
                ]
            ),
            "therefore_the_live_continuum_wall_is_exactly_existence_of_one_nonzero_point_on_one_fixed_tail_operator_line": (
                scalar["tail_scalar_closure_theorem"][
                    "all_promoted_transport_residual_data_is_generated_by_one_scalar_amplitude"
                ]
                and witness["continuum_tail_witness_criterion_theorem"][
                    "any_one_promoted_nonzero_transport_tail_observable_recovers_the_exact_scalar_amplitude"
                ]
                and normal["continuum_tail_operator_normal_form_theorem"][
                    "the_realized_transport_tail_operator_is_exactly_217_times_that_normal_form"
                ]
                and normal["continuum_tail_operator_normal_form_theorem"][
                    "the_realized_matter_tail_operator_is_the_exact_81_fold_lift_of_the_transport_operator"
                ]
            ),
        },
        "bridge_verdict": (
            "The continuum wall is now as sharp as the current promoted data can "
            "make it. Transport realization, witness realization, scalar "
            "realization, and operator-normal-form realization are all "
            "equivalent on the fixed curvature-sensitive tail avatar. The "
            "realizable tail operators form one exact one-dimensional line, any "
            "nonzero point on that line has forced scalar 217, and the "
            "matter-coupled operator is then the exact 81-fold lift. So the "
            "remaining wall is exactly existence of one nonzero point on one "
            "fixed tail-operator line."
        ),
    }


def write_summary(path: Path = DEFAULT_OUTPUT_PATH) -> Path:
    path.write_text(
        json.dumps(build_continuum_tail_realization_equivalence_summary(), indent=2),
        encoding="utf-8",
    )
    return path


def main() -> None:
    path = write_summary()
    print(f"Wrote {path}")


if __name__ == "__main__":
    main()
