"""Single-generator closure for the promoted q=3 observable package.

After the exact q=3 selection the promoted public-facing observables all sit
over one distinguished rational:

    x = sin^2(theta_W) = q / Phi_3(q) = 3/13.

This module proves that the promoted Standard Model, cosmology, and internal
spectral-action / gravity ratios are then generated by rational functions of
the single variable x:

    tan(theta_C)        = x
    sin^2(theta_12)     = 4x/3
    sin^2(theta_23)     = 1 - 2x
    sin^2(theta_13)     = 2x^2 / (9(1 - 2x))
    Omega_Lambda        = 3x
    m_H^2 / v^2         = 2(1 - 2x) / (4 + x)
    a2 / a0             = 2/x - 4
    a4 / a0             = 8/x + 2
    c_6 / a0            = 6/x
    c_6 / c_EH,cont     = 9/x

So the promoted electroweak/flavour/cosmology layer and the promoted internal
spectral-action / gravity layer are not merely cyclotomic cousins. Once q=3 is
selected, they become one single-generator rational package.
"""

from __future__ import annotations

from fractions import Fraction
from functools import lru_cache
import json
from pathlib import Path
from typing import Any

from w33_spectral_action_cyclotomic_bridge import build_spectral_action_cyclotomic_summary
from w33_standard_model_cyclotomic_bridge import build_standard_model_cyclotomic_summary


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT_PATH = ROOT / "data" / "w33_weinberg_generator_bridge_summary.json"

Q = 3


def _fraction_dict(value: Fraction) -> dict[str, Any]:
    exact = str(value.numerator) if value.denominator == 1 else f"{value.numerator}/{value.denominator}"
    return {"exact": exact, "float": float(value)}


@lru_cache(maxsize=1)
def build_weinberg_generator_summary() -> dict[str, Any]:
    sm = build_standard_model_cyclotomic_summary()
    spectral = build_spectral_action_cyclotomic_summary()

    x = Fraction(sm["promoted_observables"]["sin2_theta_w_ew"]["exact"])
    tan_theta_c = Fraction(sm["promoted_observables"]["tan_theta_c"]["exact"])
    sin2_theta_12 = Fraction(sm["promoted_observables"]["sin2_theta_12"]["exact"])
    sin2_theta_23 = Fraction(sm["promoted_observables"]["sin2_theta_23"]["exact"])
    sin2_theta_13 = Fraction(sm["promoted_observables"]["sin2_theta_13"]["exact"])
    higgs_ratio_square = Fraction(sm["promoted_observables"]["higgs_ratio_square"]["exact"])
    omega_lambda = Fraction(sm["promoted_observables"]["omega_lambda"]["exact"])

    a2_over_a0 = Fraction(spectral["internal_spectral_action"]["a2_over_a0"]["exact"])
    a4_over_a0 = Fraction(spectral["internal_spectral_action"]["a4_over_a0"]["exact"])
    c6_over_a0 = Fraction(spectral["gravity_lock"]["discrete_6_mode_over_a0"]["exact"])
    c6_over_c_eh = Fraction(spectral["gravity_lock"]["discrete_to_continuum_ratio"]["exact"])

    formulas = {
        "tan_theta_c": x,
        "sin2_theta_12": Fraction(4, 3) * x,
        "sin2_theta_23": Fraction(1) - 2 * x,
        "sin2_theta_13": Fraction(2, 9) * x * x / (Fraction(1) - 2 * x),
        "omega_lambda": 3 * x,
        "higgs_ratio_square": Fraction(2) * (Fraction(1) - 2 * x) / (Fraction(4) + x),
        "a2_over_a0": Fraction(2, 1) / x - 4,
        "a4_over_a0": Fraction(8, 1) / x + 2,
        "discrete_6_mode_over_a0": Fraction(6, 1) / x,
        "discrete_to_continuum_ratio": Fraction(9, 1) / x,
    }

    exact = {
        "tan_theta_c": tan_theta_c,
        "sin2_theta_12": sin2_theta_12,
        "sin2_theta_23": sin2_theta_23,
        "sin2_theta_13": sin2_theta_13,
        "omega_lambda": omega_lambda,
        "higgs_ratio_square": higgs_ratio_square,
        "a2_over_a0": a2_over_a0,
        "a4_over_a0": a4_over_a0,
        "discrete_6_mode_over_a0": c6_over_a0,
        "discrete_to_continuum_ratio": c6_over_c_eh,
    }

    return {
        "status": "ok",
        "generator": {
            "symbol": "x",
            "meaning": "sin^2(theta_W)",
            "exact": _fraction_dict(x),
            "q": Q,
        },
        "generated_observables": {
            key: {
                "exact": _fraction_dict(value),
                "formula_in_x": _fraction_dict(formulas[key]),
                "matches_formula": value == formulas[key],
            }
            for key, value in exact.items()
        },
        "derived_relations": {
            "sin2_theta_23_plus_2weinberg_equals_1": sin2_theta_23 + 2 * x == 1,
            "sin2_theta_12_equals_four_thirds_weinberg": sin2_theta_12 == Fraction(4, 3) * x,
            "omega_lambda_equals_3weinberg": omega_lambda == 3 * x,
            "cabibbo_equals_weinberg": tan_theta_c == x,
            "gravity_ratio_equals_9_over_weinberg": c6_over_c_eh == Fraction(9, 1) / x,
        },
        "bridge_verdict": (
            "Once q=3 is selected, the promoted public-facing observable package "
            "collapses to one exact generator x = sin^2(theta_W) = 3/13. "
            "Cabibbo, PMNS, Omega_Lambda, the Higgs ratio, the internal "
            "spectral-action ratios, and the discrete gravity normalization are "
            "all rational functions of x. So the promoted Standard Model and "
            "gravity layers are not just compatible; they are a single-generator "
            "closure."
        ),
    }


def write_summary(path: Path = DEFAULT_OUTPUT_PATH) -> Path:
    path.write_text(
        json.dumps(build_weinberg_generator_summary(), indent=2),
        encoding="utf-8",
    )
    return path


if __name__ == "__main__":
    write_summary()
