"""Exact scalar closure of the residual continuum tail package.

CCCLXXXV showed that the live continuum residual already lies on one exact
primitive tail ray:

- transport first-order local `r^20` CP2/K3 gap vector = `217 * (65, 662)`
- matter-coupled local `r^20` CP2/K3 gap vector = `81 * 217 * (65, 662)`
- seed-to-`sd^1` quadratic contraction ratio = `53979 / 62600`

The next exact question is whether the residual package still contains several
independent transport-tail parameters, or whether all promoted first- and
second-order residual data is already generated by one scalar amplitude on that
fixed ray.

The exact answer is yes: the entire residual continuum package is generated by
one scalar `A = 217`, with transport formulas

- constant gap = `65 A`
- linear gap = `662 A`
- quadratic seed gap = `(15650 / 3) A`
- quadratic `sd^1` gap = `(17993 / 4) A`

and the matter-coupled package is exactly the `81`-fold qutrit lift of the
same scalar family.
"""

from __future__ import annotations

from fractions import Fraction
from functools import lru_cache
import json
from pathlib import Path
import sys
from typing import Any


if __package__ in {None, ""}:
    ROOT = Path(__file__).resolve().parents[1]
    if str(ROOT) not in sys.path:
        sys.path.insert(0, str(ROOT))
else:
    ROOT = Path(__file__).resolve().parents[1]

from w33_continuum_qutrit_scaling_bridge import QUTRIT_FACTOR  # noqa: E402
from w33_continuum_seed_isolation_bridge import (  # noqa: E402
    build_continuum_seed_isolation_bridge_summary,
)
from w33_continuum_tail_profile_rigidity_bridge import (  # noqa: E402
    build_continuum_tail_profile_rigidity_summary,
)


DEFAULT_OUTPUT_PATH = (
    ROOT / "data" / "w33_continuum_tail_scalar_closure_bridge_summary.json"
)


@lru_cache(maxsize=1)
def build_continuum_tail_scalar_closure_summary() -> dict[str, Any]:
    seed = build_continuum_seed_isolation_bridge_summary()
    profile = build_continuum_tail_profile_rigidity_summary()

    transport_profile = profile["transport_tail_profile"]
    contraction = profile["transport_tail_contraction"]
    quadratic = seed["quadratic_gap_contraction"]

    amplitude = int(transport_profile["transport_profile_amplitude"])
    primitive = transport_profile["primitive_transport_profile"]
    matter_amplitude = int(transport_profile["matter_profile_amplitude"])

    transport_const = int(transport_profile["transport_local_r20_gap_vector"][0])
    transport_lin = int(transport_profile["transport_local_r20_gap_vector"][1])
    matter_const = int(transport_profile["matter_local_r20_gap_vector"][0])
    matter_lin = int(transport_profile["matter_local_r20_gap_vector"][1])

    transport_seed_gap = Fraction(quadratic["transport_seed_gap"]["exact"])
    transport_sd1_gap = Fraction(quadratic["transport_sd1_gap"]["exact"])
    matter_seed_gap = Fraction(quadratic["matter_seed_gap"]["exact"])
    matter_sd1_gap = Fraction(quadratic["matter_sd1_gap"]["exact"])

    transport_seed_coefficient = transport_seed_gap / amplitude
    transport_sd1_coefficient = transport_sd1_gap / amplitude

    return {
        "status": "ok",
        "tail_scalar_generator": {
            "transport_amplitude": amplitude,
            "primitive_transport_profile": primitive,
            "transport_first_order_constant_gap": transport_const,
            "transport_first_order_linear_gap": transport_lin,
            "transport_quadratic_seed_gap": str(transport_seed_gap),
            "transport_quadratic_sd1_gap": str(transport_sd1_gap),
            "transport_first_order_constant_is_65_times_amplitude": (
                transport_const == 65 * amplitude
            ),
            "transport_first_order_linear_is_662_times_amplitude": (
                transport_lin == 662 * amplitude
            ),
            "transport_quadratic_seed_is_15650_over_3_times_amplitude": (
                transport_seed_gap == Fraction(15650, 3) * amplitude
            ),
            "transport_quadratic_sd1_is_17993_over_4_times_amplitude": (
                transport_sd1_gap == Fraction(17993, 4) * amplitude
            ),
            "transport_quadratic_seed_coefficient": str(transport_seed_coefficient),
            "transport_quadratic_sd1_coefficient": str(transport_sd1_coefficient),
        },
        "matter_qutrit_lift_generator": {
            "qutrit_factor": QUTRIT_FACTOR,
            "matter_amplitude": matter_amplitude,
            "matter_first_order_constant_gap": matter_const,
            "matter_first_order_linear_gap": matter_lin,
            "matter_quadratic_seed_gap": str(matter_seed_gap),
            "matter_quadratic_sd1_gap": str(matter_sd1_gap),
            "matter_amplitude_is_81_times_transport_amplitude": (
                matter_amplitude == QUTRIT_FACTOR * amplitude
            ),
            "matter_first_order_constant_is_81_times_transport_constant": (
                matter_const == QUTRIT_FACTOR * transport_const
            ),
            "matter_first_order_linear_is_81_times_transport_linear": (
                matter_lin == QUTRIT_FACTOR * transport_lin
            ),
            "matter_quadratic_seed_is_81_times_transport_seed": (
                matter_seed_gap == QUTRIT_FACTOR * transport_seed_gap
            ),
            "matter_quadratic_sd1_is_81_times_transport_sd1": (
                matter_sd1_gap == QUTRIT_FACTOR * transport_sd1_gap
            ),
        },
        "tail_scalar_closure_theorem": {
            "all_promoted_transport_residual_data_is_generated_by_one_scalar_amplitude": (
                transport_const == 65 * amplitude
                and transport_lin == 662 * amplitude
                and transport_seed_gap == Fraction(15650, 3) * amplitude
                and transport_sd1_gap == Fraction(17993, 4) * amplitude
            ),
            "the_matter_coupled_residual_package_is_the_exact_81_fold_lift_of_the_same_scalar_family": (
                matter_amplitude == QUTRIT_FACTOR * amplitude
                and matter_const == QUTRIT_FACTOR * transport_const
                and matter_lin == QUTRIT_FACTOR * transport_lin
                and matter_seed_gap == QUTRIT_FACTOR * transport_seed_gap
                and matter_sd1_gap == QUTRIT_FACTOR * transport_sd1_gap
            ),
            "the_seed_to_sd1_quadratic_contraction_law_is_amplitude_independent": (
                contraction["seed_to_sd1_quadratic_contraction_ratio"]
                == "53979/62600"
            ),
            "therefore_the_live_continuum_wall_is_existence_of_one_scalar_tail_realization_on_a_fixed_avatar": (
                transport_const == 65 * amplitude
                and transport_lin == 662 * amplitude
                and transport_seed_gap == Fraction(15650, 3) * amplitude
                and transport_sd1_gap == Fraction(17993, 4) * amplitude
                and matter_amplitude == QUTRIT_FACTOR * amplitude
                and matter_const == QUTRIT_FACTOR * transport_const
                and matter_lin == QUTRIT_FACTOR * transport_lin
                and matter_seed_gap == QUTRIT_FACTOR * transport_seed_gap
                and matter_sd1_gap == QUTRIT_FACTOR * transport_sd1_gap
                and contraction["seed_to_sd1_quadratic_contraction_ratio"]
                == "53979/62600"
            ),
        },
        "bridge_verdict": (
            "The continuum wall is now sharper than a generic one-parameter ray "
            "selection problem. The entire promoted transport residual package is "
            "already generated by one scalar amplitude A=217 on one fixed "
            "primitive profile (65,662): first-order gaps are 65A and 662A, "
            "while the quadratic seed and sd^1 gaps are (15650/3)A and "
            "(17993/4)A. The matter-coupled package is then exactly the 81-fold "
            "qutrit lift of that same scalar family. So the remaining continuum "
            "existence problem is realization of one scalar tail datum on the "
            "fixed avatar, not a free multi-parameter residual package."
        ),
    }


def write_summary(path: Path = DEFAULT_OUTPUT_PATH) -> Path:
    path.write_text(
        json.dumps(build_continuum_tail_scalar_closure_summary(), indent=2),
        encoding="utf-8",
    )
    return path


def main() -> None:
    path = write_summary()
    print(f"Wrote {path}")


if __name__ == "__main__":
    main()
