#!/usr/bin/env python3
"""
IDENTIFY_N_PHASE3.py — Conjugacy class fingerprint + SmallGroup match
=====================================================================

Computes (element_order, class_size) for each of 14 conjugacy classes,
then uses additional invariants to pin down the GAP SmallGroup(192, ?) ID.
"""

import json
from collections import Counter

def compose(a, b):
    return [a[b[i]] for i in range(len(a))]

def inv(p):
    q = [0]*len(p)
    for i, v in enumerate(p):
        q[v] = i
    return q

def perm_order(p):
    x = list(range(len(p)))
    q = list(p)
    for k in range(1, len(p)+1):
        if q == x:
            return k
        q = compose(p, q)
    return len(p)

# ── load N ────────────────────────────────────────────────────────────
with open("N_subgroup.json") as f:
    N_raw = json.load(f)
N_elts = [tuple(g) for g in N_raw]
N_set = set(N_elts)
e = tuple(range(len(N_elts[0])))

# ── conjugacy classes with element orders ─────────────────────────────
print("Computing conjugacy classes with element orders ...")
seen = set()
class_data = []  # (rep_order, class_size)
for g in N_elts:
    if g in seen:
        continue
    cls = set()
    for h in N_elts:
        c = tuple(compose(compose(list(h), list(g)), inv(list(h))))
        cls.add(c)
    rep_ord = perm_order(g)
    class_data.append((rep_ord, len(cls)))
    seen |= cls

class_data.sort(key=lambda x: (x[0], x[1]))
print("\nCONJUGACY CLASS FINGERPRINT")
print("="*40)
print(f"{'Order':>6} {'Class Size':>12} {'Centralizer':>12}")
print("-"*40)
for ord_val, size in class_data:
    cent = 192 // size
    print(f"{ord_val:>6} {size:>12} {cent:>12}")
print("-"*40)
print(f"{'Total':>6} {sum(s for _, s in class_data):>12}")

# ── element order profile per class ───────────────────────────────────
# Verify: sum of class sizes matches element order distribution
ord_from_classes = Counter()
for ord_val, size in class_data:
    ord_from_classes[ord_val] += size
print(f"\nElement counts from classes: {dict(sorted(ord_from_classes.items()))}")

# ── Compute the lower central series ──────────────────────────────────
print("\n=== LOWER CENTRAL SERIES ===")
# γ₁(N) = N, γ_{i+1}(N) = [γᵢ(N), N]

def close_subgroup(generators, ambient):
    """Close a set of generators under multiplication within ambient."""
    sub = set(generators)
    sub.add(e)
    gens = list(generators)
    changed = True
    while changed:
        changed = False
        to_add = set()
        for a in list(sub):
            for b in gens:
                p1 = tuple(compose(list(a), list(b)))
                p2 = tuple(compose(list(b), list(a)))
                for p in [p1, p2]:
                    if p in ambient and p not in sub:
                        to_add.add(p)
        if to_add:
            sub |= to_add
            gens = list(to_add)  # only multiply new elements
            changed = True
    return sub

def commutator_subgroup(H, K, ambient):
    """Compute [H, K] = subgroup generated by [h,k] for h∈H, k∈K."""
    comms = set()
    for h in H:
        for k in K:
            c = tuple(compose(compose(list(h), list(k)),
                             compose(inv(list(h)), inv(list(k)))))
            if c in ambient:
                comms.add(c)
    return close_subgroup(comms, ambient)

gamma = [None, N_set]  # γ₁ = N
for i in range(2, 8):
    gi = commutator_subgroup(gamma[i-1], N_set, N_set)
    gamma.append(gi)
    print(f"  γ_{i}(N) = [γ_{i-1}(N), N]  has order {len(gi)}")
    if len(gi) == 1:
        print(f"  N is nilpotent of class {i-1}")
        break
    if len(gi) == len(gamma[i-1]):
        print(f"  Stabilized at γ_{i}(N) = γ_{i-1}(N)")
        break

# ── Upper central series ──────────────────────────────────────────────
print("\n=== UPPER CENTRAL SERIES ===")
# Z₀ = {e}, Z₁ = Z(N), Z₂/Z₁ = Z(N/Z₁), ...
Z = [{e}]
current_quotient_data = None  # would need coset computation
print(f"  Z₀(N) = {{e}},  |Z₀| = 1")
# Z₁ = Z(N) = {e}  (we know this)
print(f"  Z₁(N) = Z(N) = {{e}},  |Z₁| = 1")
print(f"  Upper central series terminates at Z₁ = Z₀ (trivial)")
print(f"  → N is NOT nilpotent (as expected for non-p-group)")

# ── Fitting subgroup ──────────────────────────────────────────────────
print("\n=== FITTING SUBGROUP ===")
# Fit(N) = largest nilpotent normal subgroup
# For a solvable group, Fit(N) contains all nilpotent normal subgroups.
# Our [N,N]' = C₂⁴ is nilpotent (abelian!) and normal. Is [N,N] nilpotent?
# [N,N] ≅ C₂⁴ ⋊ C₃ — this is NOT nilpotent (it's not a p-group and has trivial center).
# So Fit(N) is at least C₂⁴.

# Check if Fit(N) = C₂⁴ or larger. Fit(N) must be nilpotent.
# Any nilpotent normal subgroup must have its Sylow subgroups also normal in N.
# Sylow-3 of N: order 3 subgroups. [N,N] has unique C₃ (since [N,N] = C₂⁴ ⋊ C₃
# and C₃ acts fixed-point-free). But C₃ is not normal in N (since some elements invert it).
# Actually, C₃ is normal in [N,N] (it's the unique Sylow-3), and [N,N] is normal in N,
# so C₃ is normal in N iff every conjugate of C₃ by elements of N lands in [N,N].
# Since C₃ is the unique Sylow-3 of [N,N], and [N,N] is normal in N,
# every conjugate of C₃ is still a Sylow-3 of [N,N], hence equals C₃.
# So C₃ IS normal in N!

print("Checking: is C₃ = unique Sylow-3 of [N,N] normal in N?")
# Find C₃
deriv = commutator_subgroup(N_set, N_set, N_set)
order3_elts = [g for g in deriv if perm_order(g) == 3]
# C₃ has 2 elements of order 3 + identity = 3 elements
# But there are 32 elements of order 3 in [N,N]. They form 16 subgroups of order 3.
# Wait, 32 elements of order 3 give 32/2 = 16 subgroups C₃.
# Are these conjugate in N? If C₃ is normal, it must be unique.
# But 16 subgroups can't all be the same C₃!
# So C₃ is NOT unique in [N,N]. My reasoning was wrong.

# The Sylow-3 subgroup of [N,N] has order 3 (since |[N,N]| = 48 = 16×3).
# By Sylow's theorem, the number of Sylow-3 subgroups divides 16 and ≡ 1 mod 3.
# So #Syl₃([N,N]) ∈ {1, 4, 16}.
# 32 elements of order 3 → 16 subgroups of order 3 → #Syl₃ = 16.

num_syl3 = len(order3_elts) // 2
print(f"  Elements of order 3 in [N,N]: {len(order3_elts)}")
print(f"  Subgroups of order 3: {num_syl3}")
print(f"  → {num_syl3} Sylow-3 subgroups in [N,N]")

# What about Sylow-3 in N? |N| = 192 = 64 × 3, so Sylow-3 of N has order 3.
# Number of Sylow-3 in N: divides 64, ≡ 1 mod 3 → {1, 4, 16, 64}
all_ord3_N = [g for g in N_elts if perm_order(g) == 3]
num_syl3_N = len(all_ord3_N) // 2
print(f"  Elements of order 3 in N: {len(all_ord3_N)}")
print(f"  Subgroups of order 3 in N: {num_syl3_N}")

# The Fitting subgroup
# Since all Sylow-3 subgroups are conjugate (none normal individually unless there's just 1),
# and there are 16 of them, the Sylow-3 is not normal → F₃ part of Fit(N) is trivial.
# The normal 2-subgroups: C₂⁴ is normal (order 16). Is there a larger normal 2-subgroup?
# Sylow-2 of N has order 64 but is NOT normal (3 conjugates).
# So the largest normal 2-subgroup is... need to check.

# Check if C₂⁴ (order 16) is the largest normal 2-subgroup.
# A normal 2-subgroup larger than C₂⁴ would have order 32 or 64.
# Sylow-2 is not normal (3 conjugates from Pillar 95), so max normal 2-subgroup < 64.
# Could there be a normal subgroup of order 32?

# Let me check: is there any element of order 2 or 4 outside [N,N] = 48 elements
# that normalizes C₂⁴?

print("\n  Fit(N) analysis:")
print(f"  C₂⁴ is normal in N (characteristic in [N,N] ⊴ N) ✓")
print(f"  |Sylow-3| = 3, number of Sylow-3 in N = {num_syl3_N}  → not normal")
print(f"  Fit(N) ⊇ C₂⁴ (order 16)")

# Check if the core of a Sylow-2 subgroup is larger than C₂⁴
# The 2-core O₂(N) = largest normal 2-subgroup
# Find it: intersection of all Sylow-2 subgroups
# We know there are 3 Sylow-2 subgroups of order 64

print("\n  Computing O₂(N) (largest normal 2-subgroup) ...")
# Find all Sylow-2 subgroups
# Elements of 2-power order:
two_power = [g for g in N_elts if perm_order(g) in (1, 2, 4)]
print(f"  Elements of 2-power order: {len(two_power)}")

# From Pillar 95: Sylow-2 has 64 elements, 3 conjugates
# We need to find one Sylow-2 subgroup
# Use: start with an element of order 4, close under multiplication
# Actually, let's find a Sylow-2 subgroup by finding a subgroup of order 64
# containing all of C₂⁴

# C₂⁴ has 16 elements. We need to extend to 64.
V_set = set()
# Recompute V = [N,N]' = C₂⁴
comm_set = set()
for g in deriv:
    for h in deriv:
        c = tuple(compose(compose(list(g), list(h)),
                         compose(inv(list(g)), inv(list(h)))))
        comm_set.add(c)
V_set = set(comm_set)
changed = True
while changed:
    changed = False
    new = set()
    for a in list(V_set):
        for b in comm_set:
            p = tuple(compose(list(a), list(b)))
            if p not in V_set:
                new.add(p)
    if new:
        V_set |= new
        changed = True
        if len(V_set) > 200:
            break
print(f"  |C₂⁴| = {len(V_set)}")

# Find an involution outside [N,N] that normalizes C₂⁴ and add it
# All of N normalizes C₂⁴ (since it's normal), so we just need an involution
# outside [N,N] to extend.
ext_invols = [g for g in N_elts if perm_order(g) == 2 and g not in deriv]
print(f"  Involutions outside [N,N]: {len(ext_invols)}")

# Close V_set ∪ {ext_invols[0]} to get a subgroup
syl2_gens = V_set | {ext_invols[0]}
syl2 = close_subgroup(syl2_gens, N_set)
print(f"  Generated 2-subgroup: order {len(syl2)}")

if len(syl2) < 64:
    # Need more generators
    for inv2 in ext_invols[1:]:
        if inv2 not in syl2:
            syl2 = close_subgroup(syl2 | {inv2}, N_set)
            print(f"  Extended to order {len(syl2)}")
            if len(syl2) >= 64:
                break

if len(syl2) == 64:
    print(f"  Found Sylow-2 subgroup of order {len(syl2)} ✓")
    
    # Find all conjugates
    syl2_conjugates = []
    for g in N_elts:
        conj = frozenset(tuple(compose(compose(list(g), list(s)), inv(list(g)))) for s in syl2)
        if conj not in [frozenset(s) for s in syl2_conjugates]:
            syl2_conjugates.append(set(conj))
    
    print(f"  Number of Sylow-2 subgroups: {len(syl2_conjugates)}")
    
    # O₂(N) = intersection of all Sylow-2 subgroups
    O2_N = syl2_conjugates[0]
    for s in syl2_conjugates[1:]:
        O2_N &= s
    print(f"  |O₂(N)| = |intersection of all Sylow-2 subgroups| = {len(O2_N)}")
    
    if len(O2_N) == 16:
        print(f"  O₂(N) = C₂⁴  → Fit(N) = C₂⁴ (order 16)")
    elif len(O2_N) == 32:
        print(f"  O₂(N) has order 32  → Fit(N) ⊇ O₂(N)")
    else:
        print(f"  O₂(N) has order {len(O2_N)}")
    
    # Analyse structure of Sylow-2 subgroup
    print("\n=== SYLOW-2 SUBGROUP STRUCTURE (order 64) ===")
    syl2_orders = Counter(perm_order(g) for g in syl2)
    print(f"  Element orders: {dict(sorted(syl2_orders.items()))}")
    
    # Centre of Sylow-2
    syl2_list = list(syl2)
    syl2_centre = []
    for g in syl2_list:
        if all(compose(list(g), list(h)) == compose(list(h), list(g)) for h in syl2_list):
            syl2_centre.append(g)
    print(f"  |Z(Syl₂)| = {len(syl2_centre)}")
    
    # Derived subgroup of Sylow-2
    syl2_comms = set()
    for g in syl2_list:
        for h in syl2_list:
            c = tuple(compose(compose(list(g), list(h)),
                             compose(inv(list(g)), inv(list(h)))))
            syl2_comms.add(c)
    syl2_deriv = close_subgroup(syl2_comms, syl2)
    print(f"  |[Syl₂, Syl₂]| = {len(syl2_deriv)}")
    
    # Frattini of Sylow-2
    syl2_sq = set(tuple(compose(list(g), list(g))) for g in syl2_list)
    syl2_frat = close_subgroup(syl2_sq | syl2_deriv, syl2)
    print(f"  |Φ(Syl₂)| = {len(syl2_frat)}")
    
    # Exponent of Sylow-2
    max_2_order = max(o for o in syl2_orders if syl2_orders[o] > 0)
    print(f"  Exponent of Syl₂ = {max_2_order}")
    
    # Nilpotency class of Sylow-2
    gamma_s = [None, syl2]
    for i in range(2, 8):
        gi = commutator_subgroup(gamma_s[i-1], syl2, syl2)
        gamma_s.append(gi)
        print(f"  γ_{i}(Syl₂) order = {len(gi)}")
        if len(gi) == 1:
            print(f"  Syl₂ has nilpotency class {i-1}")
            break

# ── Summary fingerprint ──────────────────────────────────────────────
print("\n" + "="*60)
print("COMPLETE FINGERPRINT FOR SMALLGROUP IDENTIFICATION")
print("="*60)

fingerprint = {
    "order": 192,
    "exponent": 12,
    "centre": 1,
    "derived_series": "192 > 48 > 16 > 1",
    "derived_length": 3,
    "abelianisation": "C2^2",
    "conjugacy_classes": 14,
    "class_fingerprint": sorted(class_data),
    "num_involutions": 43,
    "num_ord3": 32,
    "num_ord4": 84,
    "num_ord6": 32,
    "structure": "C2^4 : D6 (faithful action)",
    "quotient_N/C2^4": "D6 = S3 x C2",
    "num_Sylow3_subgroups": num_syl3_N,
}

for k, v in fingerprint.items():
    print(f"  {k}: {v}")

with open("N_phase3_fingerprint.json", "w") as f:
    json.dump(fingerprint, f, indent=2, default=str)
print("\nSaved N_phase3_fingerprint.json")
