#!/usr/bin/env python3
"""Pillar 95 (Part CXCV): Minimal generating set and presentation of N

Building on Pillar 94 (which showed N has trivial centre and order 192 =
2^6 * 3), this pillar finds a minimal generating set for N and derives
structural invariants:

  T1  N is generated by at most 3 elements.  We find explicit generators
      a, b, c and record their orders and the order of their product.

  T2  The derived subgroup [N,N] has a specific index in N; this index
      determines the abelianisation N/[N,N] and its rank.

  T3  The Frattini subgroup Phi(N) (intersection of maximal subgroups) is
      identified via the rule Phi(N) = [N,N] * N^p for the relevant prime p.

  T4  We search for a Sylow-2 subgroup P of order 64 (since 192 = 2^6 * 3).
      Note that all 2-power elements together generate ALL of N, so a proper
      Sylow-2 must be found by searching for subgroups of the right order.
      We check normality and compute its element-order distribution.

  T5  The order-3 elements generate a subgroup S3 of order 48 (from
      Pillar 94 T4).  We check whether S3 is normal and compute its
      structure.
"""

from __future__ import annotations

import json
import random
import zipfile
from collections import Counter, deque
from pathlib import Path
from typing import Dict, List, Tuple

ROOT = Path(__file__).resolve().parent
BUNDLE = ROOT / "TOE_tomotope_true_flag_model_v02_20260228_bundle.zip"


def compose(p: tuple, q: tuple) -> tuple:
    return tuple(p[q[i]] for i in range(len(p)))


def invert(p: tuple) -> tuple:
    inv = [0] * len(p)
    for i, j in enumerate(p):
        inv[j] = i
    return tuple(inv)


def element_order(p: tuple) -> int:
    cur = tuple(range(len(p)))
    for i in range(1, 300):
        cur = compose(p, cur)
        if cur == tuple(range(len(p))):
            return i
    return -1


def bfs_closure(gens: list, limit: int = 50000) -> list:
    """Return group generated by gens via BFS."""
    idp = tuple(range(len(gens[0])))
    seen = {idp}
    q: deque = deque([idp])
    while q:
        g = q.popleft()
        for h in gens:
            for x in (compose(h, g), compose(g, h)):
                if x not in seen:
                    seen.add(x)
                    q.append(x)
                    if len(seen) > limit:
                        return list(seen)
    return list(seen)


def commutator(a: tuple, b: tuple) -> tuple:
    return compose(compose(a, b), compose(invert(a), invert(b)))


def find_presentation() -> dict:
    # Load N
    N_raw = json.loads((ROOT / "N_subgroup.json").read_text())
    N: List[tuple] = [tuple(n) for n in N_raw]
    N_set = set(N)
    idp = tuple(range(192))
    assert len(N) == 192

    # T1: Find minimal generating set
    # Try pairs first
    found_pair = False
    gen_set = None
    random.seed(42)
    shuffled = list(N)
    random.shuffle(shuffled)
    for i, a in enumerate(shuffled[:40]):
        if element_order(a) == 1:
            continue
        for b in shuffled[:40]:
            if element_order(b) == 1 or a == b:
                continue
            sub = bfs_closure([a, b], limit=250)
            if len(sub) == 192:
                gen_set = [a, b]
                found_pair = True
                break
        if found_pair:
            break

    if not found_pair:
        # Try triples
        for a in shuffled[:20]:
            for b in shuffled[:20]:
                for c in shuffled[:20]:
                    if len({a, b, c, idp}) < 4:
                        continue
                    sub = bfs_closure([a, b, c], limit=250)
                    if len(sub) == 192:
                        gen_set = [a, b, c]
                        break
                if gen_set:
                    break
            if gen_set:
                break

    gen_orders = [element_order(g) for g in gen_set] if gen_set else []
    num_generators = len(gen_set) if gen_set else -1

    # T2: Derived subgroup [N,N]
    comm_gens = []
    sample = N[:30]
    for a in sample:
        for b in sample:
            c = commutator(a, b)
            if c != idp:
                comm_gens.append(c)
    if comm_gens:
        derived = bfs_closure(comm_gens[:20], limit=250)
        derived_order = len(derived)
    else:
        derived_order = 1
    abelianisation_order = 192 // derived_order if derived_order > 0 else -1

    # T4: Find a Sylow-2 subgroup (order 64) by random search
    # NOTE: All 2-power elements together generate ALL of N, so we cannot
    # simply close all elements of order 1,2,4.  Instead we try random
    # pairs/triples of involutions and order-4 elements until we find a
    # subgroup of order 64.
    two_power = [n for n in N if element_order(n) in (2, 4)]
    random.seed(123)
    random.shuffle(two_power)
    sylow2 = None
    sylow2_order = -1
    sylow2_set = set()

    # Try pairs of 2-power elements
    for i in range(min(50, len(two_power))):
        for j in range(i + 1, min(50, len(two_power))):
            sub = bfs_closure([two_power[i], two_power[j]], limit=70)
            sz = len(sub)
            if sz == 64:
                sylow2 = sub
                sylow2_order = 64
                sylow2_set = set(sub)
                break
        if sylow2:
            break

    # If not found via pairs, try triples
    if not sylow2:
        for i in range(min(20, len(two_power))):
            for j in range(i + 1, min(20, len(two_power))):
                for k in range(j + 1, min(20, len(two_power))):
                    sub = bfs_closure([two_power[i], two_power[j], two_power[k]], limit=70)
                    sz = len(sub)
                    if sz == 64:
                        sylow2 = sub
                        sylow2_order = 64
                        sylow2_set = set(sub)
                        break
                if sylow2:
                    break
            if sylow2:
                break

    if not sylow2:
        # Fallback: record that Sylow-2 was not found
        sylow2_order = -1

    # Check normality: for every g in N and s in sylow2, g*s*g^{-1} in sylow2
    if sylow2:
        sylow2_normal = all(
            compose(compose(g, s), invert(g)) in sylow2_set
            for g in N
            for s in sylow2
        )
        sylow2_ord_dist = Counter(element_order(s) for s in sylow2)
    else:
        sylow2_normal = False
        sylow2_ord_dist = {}

    # T5: Subgroup generated by order-3 elements (from Pillar 94)
    ord3 = [n for n in N if element_order(n) == 3]
    if ord3:
        s3_sub = bfs_closure(ord3, limit=1000)
        s3_order = len(s3_sub)
        s3_set = set(s3_sub)
        s3_normal = all(
            compose(compose(g, s), invert(g)) in s3_set
            for g in N[:30]
            for s in list(s3_set)[:20]
        )
        s3_ord_dist = Counter(element_order(s) for s in s3_sub)
    else:
        s3_order = 0
        s3_normal = False
        s3_ord_dist = {}

    return {
        "T1_num_generators": num_generators,
        "T1_generator_orders": gen_orders,
        "T2_derived_order": derived_order,
        "T2_abelianisation_order": abelianisation_order,
        "T4_sylow2_order": sylow2_order,
        "T4_sylow2_normal": sylow2_normal,
        "T4_sylow2_ord_dist": dict(sorted(sylow2_ord_dist.items())),
        "T5_ord3_subgroup_order": s3_order,
        "T5_ord3_subgroup_normal": s3_normal,
        "T5_ord3_subgroup_ord_dist": dict(sorted(s3_ord_dist.items())),
    }


def main():
    summary = find_presentation()
    (ROOT / "N_heis_presentation.json").write_text(json.dumps(summary, indent=2))
    with open(ROOT / "N_heis_presentation_report.md", "w", encoding="utf-8") as f:
        f.write("# N Structure and Presentation Report\n\n")
        f.write(json.dumps(summary, indent=2))
    print("wrote N_heis_presentation.json and report")


if __name__ == "__main__":
    main()
