#!/usr/bin/env python3
"""Pillar 93 (Part CXCIII): Construct the regular subgroup N of Gamma

This module searches inside the monodromy group \Gamma (order 18 432) for the
regular subgroup N of order 192 described in Pillar 85.  The subgroup N is
characterised by acting sharply transitively on the 192 tomotope flags: each
flag is moved to every other flag by exactly one element of N.  Equivalently,
for a chosen base flag (we take 0) the map g\mapsto g(0) from N to flags is a
bijection.

The code samples random generating sets of \Gamma and closes them until a
subgroup is obtained.  When a candidate subgroup has order 192 it is tested
for regularity.  Once found, the subgroup is recorded in a JSON file and
several sanity checks are performed (element orders, closure, relation to
other known structures such as the conjugacy classes computed in Pillar 91).

A complimentary function relates each element of N to the corresponding flag
it sends 0 to, giving an explicit bijection between N and the set of 192
flags.
"""
from __future__ import annotations

import json
import random
from collections import deque, Counter
from pathlib import Path

from THEORY_PART_CXCVII_AUT_NORMALISER import load_permutations, build_gamma

ROOT = Path(__file__).resolve().parent


def compose(p: tuple[int, ...], q: tuple[int, ...]) -> tuple[int, ...]:
    return tuple(p[q[i]] for i in range(len(p)))


def invert(p: tuple[int, ...]) -> tuple[int, ...]:
    inv = [0] * len(p)
    for i, j in enumerate(p):
        inv[j] = i
    return tuple(inv)


def subgroup_generated_by(gens: list[tuple[int, ...]], limit: int = None) -> list[tuple[int, ...]]:
    """Return list of group elements generated by gens (BFS closure)."""
    idp = tuple(range(len(gens[0])))
    seen = {idp}
    queue = deque([idp])
    while queue:
        g = queue.popleft()
        for h in gens:
            gh = compose(h, g)
            if gh not in seen:
                seen.add(gh)
                queue.append(gh)
                if limit is not None and len(seen) > limit:
                    return list(seen)
            hg = compose(g, h)
            if hg not in seen:
                seen.add(hg)
                queue.append(hg)
                if limit is not None and len(seen) > limit:
                    return list(seen)
    return list(seen)


def is_regular(sub: list[tuple[int, ...]], base: int = 0) -> bool:
    if len(sub) != 192:
        return False
    images = {g[base] for g in sub}
    return len(images) == 192


def search_for_N(Gamma: list[tuple[int, ...]], trials: int = 10000) -> list[tuple[int, ...]] | None:
    """Randomly search for a regular subgroup of order 192."""
    for t in range(trials):
        # pick 2 or 3 random generators
        gens = random.sample(Gamma, k=random.choice([2, 3]))
        H = subgroup_generated_by(gens, limit=400)
        if len(H) == 192 and is_regular(H):
            return H
    return None


def main():
    print("building Gamma...")
    perms = load_permutations()
    Gamma = build_gamma(perms)
    print("Gamma size", len(Gamma))

    print("searching for N (this may take a few minutes)...")
    N = search_for_N(Gamma, trials=20000)
    if N is None:
        raise RuntimeError("failed to find regular subgroup N")
    print("found N of size", len(N))

    # verify group structure
    assert is_regular(N)
    # check closure
    closure = subgroup_generated_by(N)
    assert len(closure) == 192, "N not closed?"

    # compute element orders distribution
    def order(p):
        cur = tuple(range(len(p)))
        for i in range(1,1000):
            cur = compose(p, cur)
            if cur == tuple(range(len(p))):
                return i
        return None
    orddist = Counter(order(g) for g in N)
    print("N order distribution", orddist)

    # map to flags
    flag_map = {i: None for i in range(192)}
    for g in N:
        flag_map[g[0]] = g
    assert all(flag_map.values())

    # write files
    open(ROOT / "N_subgroup.json", "w").write(json.dumps(N, indent=2))
    open(ROOT / "N_flag_map.json", "w").write(json.dumps({str(k): v for k, v in flag_map.items()}, indent=2))
    print("wrote N_subgroup.json and N_flag_map.json")


if __name__ == "__main__":
    main()
