#!/usr/bin/env python3
"""Pillar 79 (Part CLXXXVII):  Build the 27×10 quotient transport object

Using the results of Pillars 77 and 78 we now convert the 270 directed K-
Schreier edges into an explicit 27×10 coordinate system.  Each of the 27
"qids" coming from the Heisenberg assignment (Pillar 77) carries exactly ten
directed edges: five generators leaving the pocket and five entering it.
Orienting the generator gives the second coordinate, so we obtain a natural
bijection

    {directed edges of Schreier graph}  ≅  27 × 10

The script outputs a CSV listing the coordinates for every directed edge, as
well as a JSON object arranging the edges into a 27×10 array.  The produced
bundle (written alongside earlier artifacts) can be used by later code to
check transport laws or to construct the 270-element quotient acting by
Heisenberg⋊C₆ with the axis/tomotope block twist.

Files generated:
  * edges_27x10.csv      -- one row per directed edge with qid, orient, idx
  * 27x10_table.json     -- nested list [qid][orient_index] -> edge dict

The theoretical justification is recorded in THEORY_PART_CLXXXV and
THEORY_PART_CLXXXVI, and the test ensures the combinatorics match.
"""

from __future__ import annotations

import csv
import json
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent
PILLAR_DATA = ROOT / "pillar77_data"
SHEET_DATA = ROOT / "sheet_data"

# enumerated generators in canonical order
GENS = ["g2", "g3", "g5", "g8", "g9"]
GEN_INDEX = {g: i for i, g in enumerate(GENS)}

# twin mapping: pocket -> (qid, twin_bit)

def load_twin_map() -> dict[int, tuple[int, int]]:
    path = PILLAR_DATA / "K54_to_K27_twin_map.csv"
    m = {}
    with open(path) as f:
        reader = csv.DictReader(f)
        for r in reader:
            m[int(r["pocket_id"])] = (int(r["qid"]), int(r["twin_bit"]))
    return m


def load_sheet_ids() -> dict[int, int]:
    """Return mapping orbit_idx -> sheet_id (0..5).
    """
    sheet = {}
    with open(SHEET_DATA / "coords_9x6.csv") as f:
        reader = csv.DictReader(f)
        for r in reader:
            sheet[int(r["orbit_idx"])] = int(r["sheet_id"])
    return sheet


def load_edges():
    """Yield rows from the K54_edges_with_coords_voltage.csv file."""
    path = PILLAR_DATA / "K54_edges_with_coords_voltage.csv"
    with open(path) as f:
        for r in csv.DictReader(f):
            r["u"] = int(r["u"])
            r["v"] = int(r["v"])
            r["qid_u"] = int(r["qid_u"])
            r["qid_v"] = int(r["qid_v"])
            r["cocycle_Z3_exp"] = int(r["cocycle_Z3_exp"])
            yield r


def build_27x10():
    sheet_ids = load_sheet_ids()
    twin_map = load_twin_map()

    # store edge-list and also organize by qid for the 27×10 table
    table: dict[int, list[dict]] = defaultdict(lambda: [None] * 10)
    rows = []

    for edge in load_edges():
        u = edge["u"]
        gen = edge["gen"]
        gi = GEN_INDEX[gen]
        qid, twin_bit = twin_map[u]
        orient_index = twin_bit * len(GENS) + gi  # 0..9
        e = edge["cocycle_Z3_exp"]
        # compute qid/twin for the target vertex as well
        qid_v, twin_v = twin_map[edge["v"]]
        row = {
            "u": u,
            "qid": qid,
            "twin_bit": twin_bit,
            "gen": gen,
            "cocycle_Z3_exp": e,
            "orient_index": orient_index,
            "target_qid": qid_v,
            "target_twin": twin_v,
            "v": edge["v"],
            "sheet_id": sheet_ids[u],
        }
        rows.append(row)
        assert table[qid][orient_index] is None, (qid, orient_index, u)
        table[qid][orient_index] = row

    return rows, table


def write_outputs(rows, table):
    # edges csv
    with open(ROOT / "edges_27x10.csv", "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)

    # json table
    with open(ROOT / "27x10_table.json", "w") as f:
        json.dump(table, f, indent=2)

    print("wrote edges_27x10.csv and 27x10_table.json")

    # also create a convenience bundle
    bundle = ROOT / "TOE_27x10_quotient_v01_20260228_bundle.zip"
    import zipfile
    with zipfile.ZipFile(bundle, "w") as bz:
        bz.write(str(ROOT / "edges_27x10.csv"), arcname="edges_27x10.csv")
        bz.write(str(ROOT / "27x10_table.json"), arcname="27x10_table.json")
        bz.writestr("README.txt", (
            "27x10 quotient bundle generated by THEORY_PART_CLXXXVII_27x10_quotient.py\n"
            "contains explicit coordinates for the 270 directed edges of the K-\n"
            "Schreier graph.  The first coordinate is the qid (0..26) coming from\n"
            "the Heisenberg assignment, the second is an orientation-index 0..9\n"
            "(five outgoing generators followed by five incoming).\n"
        ))
    print("wrote bundle", bundle)


def main():
    rows, table = build_27x10()
    # sanity checks
    assert len(rows) == 270, len(rows)
    for q, lst in table.items():
        assert len(lst) == 10, (q, len(lst))
        assert all(x is not None for x in lst), (q, lst)
    write_outputs(rows, table)


if __name__ == "__main__":
    main()
