"""
VERIFY_AUT_C2xQ8.py  —  Phase 5: Definitive Identification
===========================================================
Compute Aut(C₂ × Q₈) from scratch and verify its invariants match N.

C₂ × Q₈ has order 16.  Elements: (ε, g) where ε ∈ {0,1} (Z/2) and g ∈ Q₈.

Q₈ = {1, -1, i, -i, j, -j, k, -k} with the standard quaternion multiplication.

An automorphism of C₂ × Q₈ is a bijection φ: C₂ × Q₈ → C₂ × Q₈ preserving 
the group operation.

Strategy:
  1. Build the Cayley table of G = C₂ × Q₈
  2. Find all automorphisms by checking where generators map
  3. Compose automorphisms to form Aut(G) as a permutation group on 16 points
  4. Compute invariants and compare with N from N_subgroup.json
"""

import json, itertools
from collections import Counter

# ── Q₈ multiplication table ──────────────────────────────────────────
# Represent Q₈ elements as integers 0..7:
# 0=1, 1=-1, 2=i, 3=-i, 4=j, 5=-j, 6=k, 7=-k
Q8_labels = ['1', '-1', 'i', '-i', 'j', '-j', 'k', '-k']

def q8_mul(a, b):
    """Multiply two Q₈ elements (as integers 0..7)."""
    # Build table from quaternion rules
    # i² = j² = k² = ijk = -1
    table = {}
    # Using (sign, unit) representation: each element = sign * unit
    # units: 1, i, j, k  (indices 0,1,2,3)
    # sign: +1 or -1
    
    def to_pair(x):
        """Convert 0..7 to (sign, unit_index)"""
        # 0=+1, 1=-1, 2=+i, 3=-i, 4=+j, 5=-j, 6=+k, 7=-k
        signs = [1, -1, 1, -1, 1, -1, 1, -1]
        units = [0, 0, 1, 1, 2, 2, 3, 3]
        return signs[x], units[x]
    
    def from_pair(s, u):
        """Convert (sign, unit_index) back to 0..7"""
        base = u * 2
        return base if s == 1 else base + 1
    
    s_a, u_a = to_pair(a)
    s_b, u_b = to_pair(b)
    
    # Unit multiplication table: (sign, result_unit) for unit_a * unit_b
    # 1*x = x, x*1 = x
    # i*i = -1, j*j = -1, k*k = -1
    # i*j = k, j*k = i, k*i = j
    # j*i = -k, k*j = -i, i*k = -j
    unit_mul = {
        (0,0): (1,0), (0,1): (1,1), (0,2): (1,2), (0,3): (1,3),
        (1,0): (1,1), (2,0): (1,2), (3,0): (1,3),
        (1,1): (-1,0), (2,2): (-1,0), (3,3): (-1,0),
        (1,2): (1,3),  (2,3): (1,1),  (3,1): (1,2),
        (2,1): (-1,3), (3,2): (-1,1), (1,3): (-1,2),
    }
    
    s_prod, u_prod = unit_mul[(u_a, u_b)]
    return from_pair(s_a * s_b * s_prod, u_prod)

# Build full Q₈ table and verify
print("=== Building Q₈ multiplication table ===")
q8_table = [[q8_mul(a, b) for b in range(8)] for a in range(8)]

# Verify Q₈ properties
assert q8_table[0] == list(range(8)), "1 is identity"
assert q8_mul(2, 2) == 1, "i² = -1"  # i*i should give -1 (index 1)
assert q8_mul(4, 4) == 1, "j² = -1"
assert q8_mul(6, 6) == 1, "k² = -1"
assert q8_mul(2, 4) == 6, "ij = k"
assert q8_mul(4, 2) == 7, "ji = -k"
print("Q₈ verified ✓")

# ── G = C₂ × Q₈ ─────────────────────────────────────────────────────
# Elements: (c, q) where c ∈ {0,1}, q ∈ {0..7}
# Encode as integer: g = c * 8 + q, giving elements 0..15
# Multiplication: (c1,q1)*(c2,q2) = (c1+c2 mod 2, q1*q2)

def g_encode(c, q):
    return c * 8 + q

def g_decode(g):
    return g // 8, g % 8

def g_mul(a, b):
    c1, q1 = g_decode(a)
    c2, q2 = g_decode(b)
    return g_encode((c1 + c2) % 2, q8_mul(q1, q2))

def g_inv(a):
    c, q = g_decode(a)
    # In Q₈: inv(1)=1, inv(-1)=-1, inv(i)=-i, inv(j)=-j, inv(k)=-k
    q8_inv_table = [0, 1, 3, 2, 5, 4, 7, 6]
    return g_encode(c, q8_inv_table[q])

def g_order(a):
    x = a
    for n in range(1, 17):
        if x == 0:  # identity
            return n
        x = g_mul(x, a)
    return None

# Build Cayley table
print("\n=== Building C₂ × Q₈ Cayley table ===")
G_table = [[g_mul(a, b) for b in range(16)] for a in range(16)]

# Verify group axioms
identity = 0
for a in range(16):
    assert G_table[a][0] == a and G_table[0][a] == a, f"Identity fails for {a}"
    inv_a = g_inv(a)
    assert G_table[a][inv_a] == 0 and G_table[inv_a][a] == 0, f"Inverse fails for {a}"

# Verify associativity (spot check)
import random
random.seed(42)
for _ in range(1000):
    a, b, c = random.randint(0, 15), random.randint(0, 15), random.randint(0, 15)
    assert G_table[G_table[a][b]][c] == G_table[a][G_table[b][c]]

print(f"|G| = 16 ✓")
orders = Counter(g_order(a) for a in range(16))
print(f"Element orders: {dict(sorted(orders.items()))}")

# Center of G
Z_G = [a for a in range(16) if all(G_table[a][b] == G_table[b][a] for b in range(16))]
print(f"|Z(G)| = {len(Z_G)}, Z(G) = {Z_G}")

# ── Compute Aut(G) ───────────────────────────────────────────────────
# G = C₂ × Q₈ has:
#   - C₂ factor generated by a = (1, 1)  [element 8]
#   - Q₈ factor generated by i = (0, i) [element 2] and j = (0, j) [element 4]
# So G = ⟨a, i, j⟩ with relations:
#   a² = 1, i⁴ = 1, j⁴ = 1, i² = j² (both = (0, -1) = element 1)
#   ij = k (element 6), ji = -k (element 7)
#   a commutes with i and j
#
# An automorphism φ is determined by φ(a), φ(i), φ(j) subject to:
#   - φ(a) has order 2 and is central (in Z(G))
#   - φ(i) has order 4
#   - φ(j) has order 4
#   - φ(i)² = φ(j)²
#   - φ(a) commutes with φ(i) and φ(j)
#
# Actually, that's not quite right. We need φ to preserve ALL relations.
# Let's be more careful.

print("\n=== Computing Aut(C₂ × Q₈) ===")

# Elements of each order
order_1 = [a for a in range(16) if g_order(a) == 1]
order_2 = [a for a in range(16) if g_order(a) == 2]
order_4 = [a for a in range(16) if g_order(a) == 4]
print(f"Order 1: {len(order_1)} elements")
print(f"Order 2: {len(order_2)} elements")
print(f"Order 4: {len(order_4)} elements")

# Generators of G: a = 8 (C₂ generator), i = 2 (Q₈ gen), j = 4 (Q₈ gen)
gen_a = 8   # (1, 1) = C₂ generator
gen_i = 2   # (0, i) = Q₈ generator
gen_j = 4   # (0, j) = Q₈ generator

# Verify these generate G
from functools import reduce

def close_under_gens(gens):
    """Generate group from generators using Cayley table."""
    S = set(gens) | {0}  # include identity
    changed = True
    while changed:
        changed = False
        new = set()
        for a in S:
            for b in S:
                p = G_table[a][b]
                if p not in S:
                    new.add(p)
        if new:
            S |= new
            changed = True
    return S

gen_set = close_under_gens([gen_a, gen_i, gen_j])
assert len(gen_set) == 16, f"Generators don't generate full group: {len(gen_set)}"
print(f"⟨a, i, j⟩ generates G ✓")

# An automorphism is determined by images of a, i, j
# Requirements:
# 1. φ(a)² = e  (a has order 2)
# 2. φ(i)⁴ = e  (i has order 4)
# 3. φ(j)⁴ = e  (j has order 4)
# 4. φ(i)² = φ(j)²  (since i² = j² = -1 in Q₈, and this must be preserved)
# 5. G_table[φ(i)][φ(j)] != G_table[φ(j)][φ(i)]  (non-commuting pair in Q₈ image)
# 6. φ(a) commutes with φ(i) and φ(j)  (a is central)
# 7. The map must be a bijection (images must generate all of G)

# Actually, let's be more systematic: enumerate all homomorphisms by
# checking where the generators can go, then filter for bijections.

automorphisms = []

# φ(a) must be an element of order 2 in Z(G) (since a is central of order 2)
# Z(G) elements of order 2:
z_order2 = [z for z in Z_G if g_order(z) == 2]
print(f"Central elements of order 2: {z_order2}")

# φ(i) must have order 4
# φ(j) must have order 4
# φ(i)² = φ(j)²  (since i²=j²=(0,-1) and φ must preserve this)
# φ(a) must commute with φ(i) and φ(j) — automatically true if φ(a) ∈ Z(G)
# The images must generate all of G

count = 0
for img_a in z_order2:
    for img_i in order_4:
        sq_i = G_table[img_i][img_i]  # φ(i)²
        for img_j in order_4:
            sq_j = G_table[img_j][img_j]  # φ(j)²
            if sq_i != sq_j:
                continue
            # Check that φ(i) and φ(j) don't commute
            # (In Q₈, ij ≠ ji, so their images must also not commute)
            if G_table[img_i][img_j] == G_table[img_j][img_i]:
                continue
            # Check that {img_a, img_i, img_j} generate all 16 elements
            gen = close_under_gens([img_a, img_i, img_j])
            if len(gen) != 16:
                continue
            # Valid automorphism! Build the full map.
            count += 1

print(f"\nValid generator images found: {count}")

# Now build explicit automorphisms as permutations of {0..15}
print("\n=== Building automorphism permutations ===")

def build_automorphism(img_a, img_i, img_j):
    """Build full automorphism from generator images.
    
    Every element of G = C₂ × Q₈ can be written as a^ε * w
    where ε ∈ {0,1} and w is a word in i, j.
    
    We compute φ(g) for every g by expressing g in terms of generators
    and applying φ.
    """
    # Build the map by evaluating φ on each element
    # First, express each element as a product of generators
    # Use BFS from identity
    phi = [None] * 16
    phi[0] = 0  # φ(identity) = identity
    
    # Map generators
    phi[gen_a] = img_a
    phi[gen_i] = img_i
    phi[gen_j] = img_j
    
    # For each unmapped element, try to express it as g1 * g2 where g1, g2 are mapped
    changed = True
    while changed:
        changed = False
        for x in range(16):
            if phi[x] is not None:
                continue
            # Try x = g1 * g2
            for g1 in range(16):
                if phi[g1] is None:
                    continue
                for g2 in range(16):
                    if phi[g2] is None:
                        continue
                    if G_table[g1][g2] == x:
                        candidate = G_table[phi[g1]][phi[g2]]
                        if phi[x] is None:
                            phi[x] = candidate
                            changed = True
                        else:
                            assert phi[x] == candidate, "Inconsistent automorphism!"
                        break
                if phi[x] is not None:
                    break
    
    assert None not in phi, f"Could not map all elements: {phi}"
    assert len(set(phi)) == 16, "Not a bijection!"
    
    # Verify it's a homomorphism
    for x in range(16):
        for y in range(16):
            assert phi[G_table[x][y]] == G_table[phi[x]][phi[y]], \
                f"Not a homomorphism at ({x},{y})"
    
    return tuple(phi)

aut_perms = set()
for img_a in z_order2:
    for img_i in order_4:
        sq_i = G_table[img_i][img_i]
        for img_j in order_4:
            sq_j = G_table[img_j][img_j]
            if sq_i != sq_j:
                continue
            if G_table[img_i][img_j] == G_table[img_j][img_i]:
                continue
            gen = close_under_gens([img_a, img_i, img_j])
            if len(gen) != 16:
                continue
            perm = build_automorphism(img_a, img_i, img_j)
            aut_perms.add(perm)

aut_list = sorted(aut_perms)
print(f"|Aut(C₂ × Q₈)| = {len(aut_list)}")

if len(aut_list) != 192:
    print("WARNING: Expected 192, got different size!")
    print("Checking if we missed some generator constraints...")
else:
    print("✓ |Aut(C₂ × Q₈)| = 192 confirmed!")

# ── Compute invariants of Aut(G) ─────────────────────────────────────
print("\n=== Computing Aut(G) invariants ===")

def compose(p, q):
    """Compose p ∘ q as permutations on 0..15."""
    return tuple(p[q[i]] for i in range(16))

def inv_perm(p):
    """Inverse permutation."""
    inv = [0] * len(p)
    for i, v in enumerate(p):
        inv[v] = i
    return tuple(inv)

def perm_order(p):
    x = p
    for n in range(1, 200):
        if all(x[i] == i for i in range(len(p))):
            return n
        x = compose(x, p)
    return None

# Identity
aut_identity = tuple(range(16))
assert aut_identity in aut_perms

# Element orders
aut_orders = Counter(perm_order(p) for p in aut_list)
print(f"Element orders: {dict(sorted(aut_orders.items()))}")

# Center
print("\nComputing center...")
center = []
for p in aut_list:
    is_central = True
    for q in aut_list:
        if compose(p, q) != compose(q, p):
            is_central = False
            break
    if is_central:
        center.append(p)
print(f"|Z(Aut(G))| = {len(center)}")

# Commutator subgroup [Aut(G), Aut(G)]
print("\nComputing commutator subgroup...")
commutators = set()
for p in aut_list:
    for q in aut_list:
        # [p,q] = p*q*p⁻¹*q⁻¹
        comm = compose(compose(compose(p, q), inv_perm(p)), inv_perm(q))
        commutators.add(comm)

# Close under multiplication
derived = set(commutators)
changed = True
while changed:
    changed = False
    new = set()
    for a in list(derived):
        for b in commutators:  # only need to multiply by generators
            p = compose(a, b)
            if p not in derived:
                new.add(p)
    if new:
        derived |= new
        changed = True

print(f"|[Aut(G), Aut(G)]| = {len(derived)}")

# Second derived subgroup
print("Computing second derived subgroup...")
comm2 = set()
derived_list = list(derived)
for p in derived_list:
    for q in derived_list:
        comm = compose(compose(compose(p, q), inv_perm(p)), inv_perm(q))
        comm2.add(comm)

derived2 = set(comm2)
changed = True
while changed:
    changed = False
    new = set()
    for a in list(derived2):
        for b in comm2:
            p = compose(a, b)
            if p not in derived2:
                new.add(p)
    if new:
        derived2 |= new
        changed = True

print(f"|[[Aut(G), Aut(G)], ...]| = {len(derived2)}")

# Conjugacy classes
print("\nComputing conjugacy classes...")
remaining = set(range(len(aut_list)))
conj_classes = []
while remaining:
    rep_idx = min(remaining)
    rep = aut_list[rep_idx]
    cls = set()
    for q in aut_list:
        conj = compose(compose(q, rep), inv_perm(q))
        idx = aut_list.index(conj) if conj in aut_perms else None
        if idx is not None:
            cls.add(idx)
    conj_classes.append(cls)
    remaining -= cls

cc_fingerprint = sorted((perm_order(aut_list[min(cls)]), len(cls)) for cls in conj_classes)
print(f"Number of conjugacy classes: {len(conj_classes)}")
print(f"Fingerprint (order, size): {cc_fingerprint}")

# ── Compare with N ───────────────────────────────────────────────────
print("\n" + "="*60)
print("COMPARISON WITH N FROM N_subgroup.json")
print("="*60)

# Load N invariants from Phase 3
try:
    with open('N_phase3_fingerprint.json') as f:
        n_data = json.load(f)
    n_fingerprint = [tuple(x) for x in n_data['conjugacy_class_fingerprint']]
    n_fingerprint_sorted = sorted(n_fingerprint)
    
    print(f"\nAut(C₂×Q₈) fingerprint: {cc_fingerprint}")
    print(f"N fingerprint:           {n_fingerprint_sorted}")
    
    if cc_fingerprint == n_fingerprint_sorted:
        print("\n╔══════════════════════════════════════════════════════════╗")
        print("║  CONJUGACY CLASS FINGERPRINTS MATCH PERFECTLY! ✓       ║")
        print("╚══════════════════════════════════════════════════════════╝")
    else:
        print("\n⚠ FINGERPRINTS DO NOT MATCH ⚠")
except Exception as e:
    print(f"Could not load N_phase3_fingerprint.json: {e}")

# Load N deep invariants
try:
    with open('N_deep_identification.json') as f:
        deep = json.load(f)
    
    n_center = deep.get('center_order', '?')
    n_derived = deep.get('derived_subgroup_order', '?')
    n_derived2 = deep.get('second_derived_order', '?')
    n_num_cc = deep.get('num_conjugacy_classes', '?')
    
    print(f"\n{'Property':<30} {'Aut(C₂×Q₈)':<15} {'N':<15} {'Match?'}")
    print("-" * 75)
    print(f"{'|Z|':<30} {len(center):<15} {n_center:<15} {'✓' if len(center) == n_center else '✗'}")
    print(f"{'|G′|':<30} {len(derived):<15} {n_derived:<15} {'✓' if len(derived) == n_derived else '✗'}")
    print(f"{'|G″|':<30} {len(derived2):<15} {n_derived2:<15} {'✓' if len(derived2) == n_derived2 else '✗'}")
    print(f"{'# conjugacy classes':<30} {len(conj_classes):<15} {n_num_cc:<15} {'✓' if len(conj_classes) == n_num_cc else '✗'}")
    
    # Element orders comparison
    print(f"\nAut(C₂×Q₈) element orders: {dict(sorted(aut_orders.items()))}")
    n_orders = deep.get('element_orders', {})
    print(f"N element orders:           {n_orders}")
    
except Exception as e:
    print(f"Could not load N_deep_identification.json: {e}")

# ── O₂ analysis ──────────────────────────────────────────────────────
print("\n=== O₂(Aut(G)) analysis ===")

# Find normal 2-subgroups
def is_normal(subgroup_set, group_list):
    """Check if subgroup is normal in group."""
    for g in group_list:
        g_inv = inv_perm(g)
        for h in subgroup_set:
            conj = compose(compose(g, h), g_inv)
            if conj not in subgroup_set:
                return False
    return True

# Find 2-subgroups: start with elements of 2-power order
two_elements = [p for p in aut_list if perm_order(p) in [1, 2, 4, 8, 16, 32, 64]]
print(f"Elements of 2-power order: {len(two_elements)}")

# Sylow-2 subgroups: order 64
# Find one Sylow-2 by building from a specific element
# Actually, let's find O₂ more directly: find the largest normal 2-subgroup

# O₂ = intersection of all Sylow-2 subgroups
# First find Sylow-2 subgroups (order 64)
# Use random closure: pick 2-elements and close

def close_subgroup_set(gens, all_perms_set):
    """Close a set of generators under composition and inverse."""
    S = set(gens) | {aut_identity}
    changed = True
    while changed:
        changed = False
        new = set()
        for a in list(S):
            for b in list(S):
                p = compose(a, b)
                if p in all_perms_set and p not in S:
                    new.add(p)
        if new:
            S |= new
            changed = True
    return S

# Find elements of order 3 (there should be |Syl₃| * 2 = 32 elements of order 3)
order3_elts = [p for p in aut_list if perm_order(p) == 3]
print(f"Elements of order 3: {len(order3_elts)}")

# Sylow-3 subgroups: order 3
# To find Sylow-2: take centralizer of a Sylow-3
# Or: just find all subgroups of order 64

# More efficient: find O₂ directly
# O₂ = largest normal 2-subgroup
# = intersection of all Sylow 2-subgroups
# = Fitting 2-part

# Let's find by brute force: among all normal subgroups of 2-power order,
# find the largest

# Alternative: since |G|=192=2⁶·3, O₂ has order dividing 64
# From N analysis: O₂(N) has order 32

# Find ALL subgroups of order 32 and check normality
# This is expensive. Instead, use the known structure.

# Approach: compute O₂ as ∩ Sylow-2
# Find Sylow-2 subgroups

print("\nFinding Sylow-2 subgroups...")

# A Sylow-2 has order 64 = 192/3
# Find one by taking all elements that are 2-elements and closing
# Actually, need to be more careful. Let me find one Sylow-2 by 
# picking a maximal 2-subgroup.

# Take an element of order 4, generate a subgroup, extend it
# Actually let's just close random sets of 2-elements

import random
random.seed(123)

sylow2_subgroups = []
for trial in range(100):
    # Pick random 2-elements and close
    gens = random.sample(two_elements, min(6, len(two_elements)))
    S = close_subgroup_set(gens, aut_perms)
    if len(S) == 64:
        frozen = frozenset(S)
        if frozen not in [frozenset(s) for s in sylow2_subgroups]:
            sylow2_subgroups.append(S)

print(f"Found {len(sylow2_subgroups)} Sylow-2 subgroups")

if len(sylow2_subgroups) >= 2:
    # Compute intersection
    O2_set = sylow2_subgroups[0]
    for S in sylow2_subgroups[1:]:
        O2_set = O2_set & S
    print(f"|∩ Sylow-2| = {len(O2_set)}")
    
    if is_normal(O2_set, aut_list):
        print("Normal in Aut(G) ✓")
    
    # Element orders in O₂
    o2_orders = Counter(perm_order(p) for p in O2_set)
    print(f"O₂ element orders: {dict(sorted(o2_orders.items()))}")
    
    # Check non-abelian
    is_abelian = True
    o2_list = list(O2_set)
    for p in o2_list:
        for q in o2_list:
            if compose(p, q) != compose(q, p):
                is_abelian = False
                break
        if not is_abelian:
            break
    print(f"O₂ abelian: {is_abelian}")

# ── Save results ──────────────────────────────────────────────────────
results = {
    'aut_order': len(aut_list),
    'center_order': len(center),
    'derived_order': len(derived),
    'second_derived_order': len(derived2),
    'num_conjugacy_classes': len(conj_classes),
    'conjugacy_class_fingerprint': cc_fingerprint,
    'element_orders': dict(sorted(aut_orders.items())),
    'O2_order': len(O2_set) if len(sylow2_subgroups) >= 2 else None,
}

with open('N_phase5_aut_verification.json', 'w') as f:
    json.dump(results, f, indent=2)

print(f"\nResults saved to N_phase5_aut_verification.json")

print("\n" + "="*60)
print("FINAL VERDICT")
print("="*60)
