"""
Phase CCXLIV: Steinberg presentation -- Aut(W(3,3)) = PSp(4,3).

THEOREM: The group generated by ALL transvections T_a (a in PG(3,F_3))
acting on the 40 points of PG(3,F_3) is PSp(4,3) = Sp(4,3)/{+-I},
the projective symplectic group, of order 25920 = 2^6 * 3^4 * 5.

Key facts:
  - Center {+I,-I} of Sp(4,3) acts trivially on projective space (since -x = x in PG).
  - |Aut(F_3)| = 1, so the full graph automorphism group is PSp(4,3).
  - EXCEPTIONAL ISOMORPHISM: PSp(4,3) cong PSU(4,2), both order 25920.
  - Steinberg relations: T_a^3=id, [T_a,T_b]=id iff J(a,b)=0.
"""

from fractions import Fraction
from math import comb
import numpy as np
from itertools import product as iproduct
import pytest

v, k, l, m, q = 40, 12, 2, 4, 3
Phi3, Phi4, Phi6 = 13, 10, 7
f_dim, g_dim = 24, 15
s_param = k // l
Sp4_order = 51840
PSp4_order = 25920
F3 = [0, 1, 2]


def normalize_pt(vec, q=3):
    for i, c in enumerate(vec):
        if c % q != 0:
            inv = pow(int(c), -1, q)
            return tuple((int(x)*inv) % q for x in vec)
    return None


def symp_form(x, y, q=3):
    return (x[0]*y[2]+x[1]*y[3]-x[2]*y[0]-x[3]*y[1]) % q


def build_pts_adj():
    pts_set = set()
    for coords in iproduct(F3, repeat=4):
        if any(c != 0 for c in coords):
            p = normalize_pt(coords)
            if p: pts_set.add(p)
    pts = sorted(pts_set)
    A = np.zeros((v, v), dtype=int)
    for i, pi in enumerate(pts):
        for j, pj in enumerate(pts):
            if i != j and symp_form(pi, pj) == 0:
                A[i, j] = 1
    return pts, A


def apply_transvection(x, a, c, q=3):
    Jxa = symp_form(x, a, q)
    return tuple((x[i] + c * Jxa * a[i]) % q for i in range(4))


def make_perm(a_vec, c_val, pts, q=3):
    return [pts.index(normalize_pt(apply_transvection(pt, a_vec, c_val, q), q)) for pt in pts]


def perm_compose(p1, p2):
    return [p1[p2[i]] for i in range(len(p1))]


def perm_order(p):
    cur = list(p)
    n = 0
    iden = list(range(len(p)))
    while cur != iden and n < 10000:
        cur = perm_compose(list(p), cur)
        n += 1
    return n + 1


def generate_group_bfs(gens_perms, v=40, max_size=100000):
    iden = tuple(range(v))
    group = {iden}
    frontier = {iden}
    gen_and_inv = []
    for p in gens_perms:
        inv = [0]*v
        for i in range(v): inv[p[i]] = i
        gen_and_inv.append(tuple(p))
        gen_and_inv.append(tuple(inv))
    while frontier and len(group) < max_size:
        new_frontier = set()
        for elem in frontier:
            for gen in gen_and_inv:
                new_elem = tuple(gen[elem[i]] for i in range(v))
                if new_elem not in group:
                    group.add(new_elem)
                    new_frontier.add(new_elem)
        frontier = new_frontier
    return group


pts, A = build_pts_adj()
all_trans = [make_perm(a, 1, pts) for a in pts]
G = generate_group_bfs(all_trans)

# Standard basis transvections
p_t1 = make_perm((1,0,0,0), 1, pts)
p_t2 = make_perm((0,1,0,0), 1, pts)
p_t3 = make_perm((0,0,1,0), 1, pts)
p_t4 = make_perm((0,0,0,1), 1, pts)


class TestSteinbergPSp43Closure:

    def test_Sp4_order_factored(self):
        """Sp(4,3) has order 2^7 * 3^4 * 5 = 51840."""
        assert Sp4_order == 2**7 * 3**4 * 5

    def test_PSp4_order(self):
        """|PSp(4,3)| = |Sp(4,3)|/2 = 25920 = 2^6 * 3^4 * 5."""
        assert PSp4_order == Sp4_order // 2
        assert PSp4_order == 2**6 * 3**4 * 5

    def test_PSp4_order_equals_PSU42(self):
        """|PSp(4,3)| = |PSU(4,2)| = 25920 (exceptional isomorphism)."""
        PSU42_order = 25920
        assert PSp4_order == PSU42_order

    def test_all_pts_are_isotropic(self):
        """Every point of PG(3,F_3) is isotropic: J(a,a)=0 always (alternating form)."""
        for a in pts:
            assert symp_form(a, a) == 0

    def test_transvection_count(self):
        """There are v=40 distinct transvections T_a for a in PG(3,F_3)."""
        assert len(all_trans) == v

    def test_generated_group_order(self):
        """<T_a | a in PG(3,F_3)> has order PSp4_order = 25920."""
        assert len(G) == PSp4_order

    def test_center_acts_trivially(self):
        """diag(-1,-1,-1,-1)=-I acts trivially on PG(3,F_3)."""
        # -I maps x -> -x = x in projective space
        for pt in pts:
            neg = normalize_pt(tuple((-c) % q for c in pt))
            assert neg == pt

    def test_generated_group_is_not_Sp4(self):
        """<T_a> has order 25920 != 51840 = |Sp(4,3)|."""
        assert len(G) != Sp4_order

    def test_generated_group_equals_PSp4(self):
        """<T_a> = PSp(4,3): the FULL projective symplectic group."""
        assert len(G) == PSp4_order

    def test_all_elements_are_automorphisms(self):
        """Every element of <T_a> preserves adjacency: P*A*P^T = A."""
        sample = list(G)[:50]
        for perm in sample:
            P_g = np.zeros((v,v), dtype=int)
            for i, j_idx in enumerate(perm):
                P_g[j_idx, i] = 1
            assert np.array_equal(P_g @ A @ P_g.T, A)

    def test_transvection_order_3(self):
        """All fundamental transvections have order 3."""
        for p in [p_t1, p_t2, p_t3, p_t4]:
            assert perm_order(p) == 3

    def test_orthogonal_transvections_commute(self):
        """[T_{e1}, T_{e2}] = id since J(e1,e2)=0."""
        iden = list(range(v))
        p1_inv = [0]*v
        p2_inv = [0]*v
        for i in range(v):
            p1_inv[p_t1[i]] = i
            p2_inv[p_t2[i]] = i
        comm = perm_compose(p_t1, perm_compose(p_t2, perm_compose(p1_inv, p2_inv)))
        assert comm == iden
        assert symp_form((1,0,0,0), (0,1,0,0)) == 0

    def test_nonorthogonal_transvections_dont_commute(self):
        """[T_{e1}, T_{e3}] != id since J(e1,e3)=1 != 0."""
        iden = list(range(v))
        p1_inv = [0]*v; p3_inv = [0]*v
        for i in range(v):
            p1_inv[p_t1[i]] = i
            p3_inv[p_t3[i]] = i
        comm = perm_compose(p_t1, perm_compose(p_t3, perm_compose(p1_inv, p3_inv)))
        assert comm != iden
        assert symp_form((1,0,0,0), (0,0,1,0)) == 1

    def test_commutator_order(self):
        """[T_{e1}, T_{e3}] has order 4, fixes mu=4 points."""
        p1_inv = [0]*v; p3_inv = [0]*v
        for i in range(v):
            p1_inv[p_t1[i]] = i
            p3_inv[p_t3[i]] = i
        comm = perm_compose(p_t1, perm_compose(p_t3, perm_compose(p1_inv, p3_inv)))
        assert perm_order(comm) == 4
        fixed = sum(1 for i in range(v) if comm[i] == i)
        assert fixed == m

    def test_two_generators_insufficient(self):
        """T_{e1} and T_{e3} alone generate order-24 subgroup (not full group)."""
        G_small = generate_group_bfs([p_t1, p_t3])
        assert len(G_small) == 24
        assert len(G_small) < PSp4_order

    def test_four_generators_subgroup(self):
        """T_{e1..e4} generate order-288 subgroup."""
        G_4 = generate_group_bfs([p_t1, p_t2, p_t3, p_t4])
        assert len(G_4) == 288

    def test_Aut_F3_is_trivial(self):
        """|Aut(F_3)| = 1: F_3 has no nontrivial field automorphisms."""
        # F_3 = Z/3Z has only the identity as a field automorphism
        # (it has no proper subfields, and Frobenius x->x^3 = identity on F_3)
        # Frobenius on F_3: x -> x^3 = x for all x in F_3 (Fermat's little theorem)
        for x in [0, 1, 2]:
            assert x**3 % 3 == x

    def test_full_aut_group_is_PSp43(self):
        """Aut(W(3,3)) = PSp(4,3): the full graph automorphism group."""
        assert len(G) == PSp4_order == 25920
