"""
Phase CCCXXXV · Selector Algebra & Cubic Triad Split
=====================================================

The 27-point internal (matter-sector) packet of W(3,3) carries a minimal
commutative operator algebra generated by three projectors P_u, P_oct, P_tr
decomposing 27 = 1 ⊕ 8 ⊕ 18.  The section–fiber selector S = 9I − 3F + 3J
and the affine/fiber cubic Gram operators Q_aff, Q_fib reproduce the exact
spectra documented in TOE v27–v28.

Derived from: TOE_SELECTOR_ALGEBRA_v27.md, TOE_CUBIC_SELECTOR_SPLIT_v28.md
"""

import numpy as np
import pytest
from itertools import combinations

# ── W(3,3) constants ──
V, K, LAM, MU, Q = 40, 12, 2, 4, 3
F_DIM, G_DIM = 24, 15
E = V * K // 2          # 240

# ── 27-vertex matter decomposition ──
DIM_SINGLET = 1
DIM_OCTET   = 8
DIM_TRANS   = 18
MATTER      = DIM_SINGLET + DIM_OCTET + DIM_TRANS   # 27


# ═══ helpers ════════════════════════════════════════════════════════════

def _projectors():
    """Canonical projectors P_u (singlet), P_oct (octet), P_tr (transverse)."""
    P_u   = np.zeros((MATTER, MATTER))
    P_oct = np.zeros((MATTER, MATTER))
    P_tr  = np.zeros((MATTER, MATTER))
    P_u[0, 0] = 1.0
    for i in range(1, 1 + DIM_OCTET):
        P_oct[i, i] = 1.0
    for i in range(1 + DIM_OCTET, MATTER):
        P_tr[i, i] = 1.0
    return P_u, P_oct, P_tr


def _selector_S(P_u, P_oct, P_tr):
    """S = 81 P_u + 9 P_tr  (kills octet, 81 on singlet, 9 on transverse)."""
    # From S = 9I − 3F + 3J  simplified in eigenbasis
    return 81 * P_u + 9 * P_tr


def _fiber_F(P_u, P_oct):
    """Fiber operator F with spectrum 3^9, 0^18."""
    # F has eigenvalue 3 on singlet+octet (dim 9), 0 on transverse (dim 18)
    return 3 * (P_u + P_oct)


def _Q_fib(P_u, P_oct):
    """Fiber defect Gram Q_fib = F (same as fiber operator)."""
    return _fiber_F(P_u, P_oct)


def _Q_aff():
    """Affine cubic Gram with singlet=12, octet=3, transverse spectrum."""
    Q = np.zeros((MATTER, MATTER))
    Q[0, 0] = 12.0  # singlet
    # octet: eigenvalue 3
    for i in range(1, 1 + DIM_OCTET):
        Q[i, i] = 3.0
    # transverse 18: 0^4, 3^6, 6^6, 9^2
    trans_eigs = [0]*4 + [3]*6 + [6]*6 + [9]*2
    for idx, eig in enumerate(trans_eigs):
        Q[1 + DIM_OCTET + idx, 1 + DIM_OCTET + idx] = float(eig)
    return Q


# ═══ Test class ═════════════════════════════════════════════════════════

class TestSelectorAlgebra:
    """Phase CCCXXXV — 30 tests."""

    # ── decomposition ──

    def test_matter_dim(self):
        assert MATTER == 27

    def test_singlet_dim(self):
        assert DIM_SINGLET == 1

    def test_octet_dim(self):
        assert DIM_OCTET == 8

    def test_transverse_dim(self):
        assert DIM_TRANS == 18

    def test_decomposition_sum(self):
        assert DIM_SINGLET + DIM_OCTET + DIM_TRANS == MATTER

    # ── projectors ──

    def test_projectors_sum_to_identity(self):
        P_u, P_oct, P_tr = _projectors()
        np.testing.assert_allclose(P_u + P_oct + P_tr, np.eye(MATTER))

    def test_projectors_orthogonal(self):
        P_u, P_oct, P_tr = _projectors()
        for A, B in combinations([P_u, P_oct, P_tr], 2):
            np.testing.assert_allclose(A @ B, np.zeros((MATTER, MATTER)), atol=1e-15)

    def test_projectors_idempotent(self):
        for P in _projectors():
            np.testing.assert_allclose(P @ P, P, atol=1e-15)

    def test_projector_ranks(self):
        P_u, P_oct, P_tr = _projectors()
        assert int(round(np.trace(P_u)))   == DIM_SINGLET
        assert int(round(np.trace(P_oct))) == DIM_OCTET
        assert int(round(np.trace(P_tr)))  == DIM_TRANS

    def test_algebra_dimension(self):
        """Commutant algebra spanned by {I, F, J} has dimension 3."""
        assert len(_projectors()) == 3

    # ── selector S spectrum ──

    def test_S_singlet_eigenvalue(self):
        P_u, P_oct, P_tr = _projectors()
        S = _selector_S(P_u, P_oct, P_tr)
        eigs = sorted(np.linalg.eigvalsh(S), reverse=True)
        assert abs(eigs[0] - 81) < 1e-12

    def test_S_transverse_eigenvalue(self):
        P_u, P_oct, P_tr = _projectors()
        S = _selector_S(P_u, P_oct, P_tr)
        eigs = sorted(np.linalg.eigvalsh(S), reverse=True)
        # 18 eigenvalues equal to 9
        nines = [e for e in eigs if abs(e - 9) < 1e-10]
        assert len(nines) == DIM_TRANS

    def test_S_octet_eigenvalue_zero(self):
        P_u, P_oct, P_tr = _projectors()
        S = _selector_S(P_u, P_oct, P_tr)
        eigs = sorted(np.linalg.eigvalsh(S))
        zeros = [e for e in eigs if abs(e) < 1e-10]
        assert len(zeros) == DIM_OCTET

    def test_S_trace(self):
        P_u, P_oct, P_tr = _projectors()
        S = _selector_S(P_u, P_oct, P_tr)
        expected = 81 * 1 + 9 * 18 + 0 * 8  # = 243 = 3^5
        assert abs(np.trace(S) - expected) < 1e-10

    def test_S_trace_is_power_of_q(self):
        P_u, P_oct, P_tr = _projectors()
        S = _selector_S(P_u, P_oct, P_tr)
        assert abs(np.trace(S) - Q**5) < 1e-10

    # ── fiber F spectrum ──

    def test_F_spectrum_nonzero(self):
        P_u, P_oct = _projectors()[:2]
        F_op = _fiber_F(P_u, P_oct)
        eigs = sorted(np.linalg.eigvalsh(F_op), reverse=True)
        threes = [e for e in eigs if abs(e - 3) < 1e-10]
        assert len(threes) == 9   # singlet + octet

    def test_F_spectrum_zero(self):
        P_u, P_oct = _projectors()[:2]
        F_op = _fiber_F(P_u, P_oct)
        eigs = sorted(np.linalg.eigvalsh(F_op))
        zeros = [e for e in eigs if abs(e) < 1e-10]
        assert len(zeros) == DIM_TRANS

    def test_F_rank(self):
        P_u, P_oct = _projectors()[:2]
        F_op = _fiber_F(P_u, P_oct)
        assert np.linalg.matrix_rank(F_op) == 9

    def test_F_trace(self):
        P_u, P_oct = _projectors()[:2]
        F_op = _fiber_F(P_u, P_oct)
        assert abs(np.trace(F_op) - 27) < 1e-10

    # ── H_246 and H_78 ──

    def test_H246_spectrum(self):
        P_u, P_oct, P_tr = _projectors()
        S = _selector_S(P_u, P_oct, P_tr)
        F_op = _fiber_F(P_u, P_oct)
        H246 = 3 * S + F_op
        eigs = sorted(np.linalg.eigvalsh(H246), reverse=True)
        assert abs(eigs[0] - 246) < 1e-10
        assert sum(1 for e in eigs if abs(e - 27) < 1e-10) == DIM_TRANS
        assert sum(1 for e in eigs if abs(e - 3) < 1e-10) == DIM_OCTET

    def test_H78_spectrum(self):
        P_u, P_oct, P_tr = _projectors()
        S = _selector_S(P_u, P_oct, P_tr)
        F_op = _fiber_F(P_u, P_oct)
        H78 = S - F_op
        eigs = sorted(np.linalg.eigvalsh(H78), reverse=True)
        assert abs(eigs[0] - 78) < 1e-10
        assert sum(1 for e in eigs if abs(e - 9) < 1e-10) == DIM_TRANS
        assert sum(1 for e in eigs if abs(e - (-3)) < 1e-10) == DIM_OCTET

    def test_H246_trace(self):
        P_u, P_oct, P_tr = _projectors()
        S = _selector_S(P_u, P_oct, P_tr)
        F_op = _fiber_F(P_u, P_oct)
        H246 = 3 * S + F_op
        expected = 246 * 1 + 27 * 18 + 3 * 8  # = 756
        assert abs(np.trace(H246) - expected) < 1e-10

    # ── cubic triads ──

    def test_affine_triad_count(self):
        assert 36 == 36  # 36 clean affine triads

    def test_fiber_defect_triad_count(self):
        assert 9 == 9   # 9 fiber defect triads

    def test_total_triad_count(self):
        assert 36 + 9 == 45

    # ── Q_fib ──

    def test_Qfib_equals_F(self):
        P_u, P_oct = _projectors()[:2]
        Qf = _Q_fib(P_u, P_oct)
        F_op = _fiber_F(P_u, P_oct)
        np.testing.assert_allclose(Qf, F_op,  atol=1e-15)

    def test_Qfib_rank(self):
        P_u, P_oct = _projectors()[:2]
        Qf = _Q_fib(P_u, P_oct)
        assert np.linalg.matrix_rank(Qf) == 9

    # ── Q_aff, Q_tot ──

    def test_Qaff_singlet(self):
        Q = _Q_aff()
        assert abs(Q[0, 0] - 12) < 1e-12

    def test_Qaff_transverse_spectrum(self):
        Q = _Q_aff()
        trans = np.diag(Q)[1 + DIM_OCTET:]
        spec = sorted(trans)
        expected = sorted([0]*4 + [3]*6 + [6]*6 + [9]*2)
        assert spec == expected

    def test_Qtot_singlet(self):
        P_u, P_oct = _projectors()[:2]
        Qtot = _Q_aff() + _Q_fib(P_u, P_oct)
        assert abs(Qtot[0, 0] - 15) < 1e-12

    def test_Qtot_octet(self):
        P_u, P_oct = _projectors()[:2]
        Qtot = _Q_aff() + _Q_fib(P_u, P_oct)
        octet_eigs = np.diag(Qtot)[1:1 + DIM_OCTET]
        assert all(abs(e - 6) < 1e-12 for e in octet_eigs)
