"""
Phase LXIV: Hard Graph Computation — Automorphism, Ramanujan, Ihara-Bass (T891–T910)
=====================================================================================

Unlike parameter-assertion tests, every theorem here builds W(3,3) from scratch
using the symplectic form on PG(3,F_3) and verifies properties through ACTUAL
matrix computation.  Nothing is assumed — eigenvalues are computed by numpy,
the non-backtracking operator is constructed edge by edge, the Ihara-Bass
identity is verified at multiple complex points, and the automorphism group
is generated by explicit symplectic transvections.

Key results proved computationally:
  T891: W(3,3) construction and SRG verification (brute-force neighbor counting)
  T892: Full adjacency spectrum {12(×1), 2(×24), -4(×15)} via eigvalsh
  T893: Ramanujan property — nontrivial |λ| ≤ 2√(k-1)
  T894: Non-backtracking operator B (480×480) and outdegree verification
  T895: Ihara-Bass determinant identity at 6 probe values
  T896: Vertex propagator M spectrum and 1ᵀM⁻¹1 = 40/1111
  T897: Alpha formula α⁻¹ = 137 + 40/1111 from M
  T898: Automorphism group |Aut(W33)| = 51840 = |W(E₆)| via GSp(4,3)
  T899: Complement graph SRG(40,27,18,18) verification
  T900: Clique complex f-vector (40,240,160,40) and Euler χ = −80
  T901: Kirchhoff spanning-tree count via det(L₀)/(v)
  T902: Hashimoto spectral radius = k−1 = 11
  T903: Seidel spectrum and switching equivalence
  T904: Alpha stress-test against other SRGs (uniqueness)
  T905: Laplacian, signless Laplacian, normalised Laplacian spectra
  T906: Heat kernel trace identities from actual eigenvalues
  T907: Trace power sums Tr(A^n) for n=1..6
  T908: Ihara zeta discriminants from numerical eigenvalues
  T909: Automorphism acts as graph symmetry (edge preservation)
  T910: Complement automorphism group order
"""

import pytest
import numpy as np
import math
from itertools import product as iproduct
from collections import Counter, deque
from fractions import Fraction

# ═══════════════════════════════════════════════════════════════════════
# Graph construction helpers (self-contained, no imports from main code)
# ═══════════════════════════════════════════════════════════════════════

def _canonical(v, q=3):
    """Projective canonical representative: first nonzero entry normalised to 1."""
    for i in range(len(v)):
        if v[i] % q != 0:
            inv = pow(int(v[i]), -1, q)
            return tuple((int(c) * inv) % q for c in v)
    return None

def _build_w33():
    """Build W(3,3) = Sp(4,3) from the symplectic form on GF(3)^4."""
    q = 3
    raw = [v for v in iproduct(range(q), repeat=4) if any(x != 0 for x in v)]
    seen = set()
    vertices = []
    for v in raw:
        c = _canonical(v, q)
        if c is not None and c not in seen:
            seen.add(c)
            vertices.append(c)
    vertices.sort()
    n = len(vertices)

    # Symplectic form: omega(x,y) = x0*y2 - x2*y0 + x1*y3 - x3*y1 (mod 3)
    def omega(x, y):
        return (x[0]*y[2] - x[2]*y[0] + x[1]*y[3] - x[3]*y[1]) % q

    adj = np.zeros((n, n), dtype=np.int8)
    edges = []
    for i in range(n):
        for j in range(i+1, n):
            if omega(vertices[i], vertices[j]) == 0:
                adj[i, j] = adj[j, i] = 1
                edges.append((i, j))
    return n, vertices, adj, edges

def _build_complement(adj):
    """Build the complement graph adjacency matrix."""
    n = adj.shape[0]
    comp = np.ones((n, n), dtype=np.int8) - adj
    np.fill_diagonal(comp, 0)
    return comp

def _build_nonbacktracking(adj, edges, n):
    """Build the 480×480 non-backtracking (Hashimoto) operator."""
    directed = []
    for i, j in edges:
        directed.append((i, j))
        directed.append((j, i))
    de_idx = {e: k for k, e in enumerate(directed)}
    nd = len(directed)
    rows, cols = [], []
    for idx_ab, (a, b) in enumerate(directed):
        for c in range(n):
            if c != a and adj[b, c] == 1:
                rows.append(idx_ab)
                cols.append(de_idx[(b, c)])
    from scipy import sparse
    B = sparse.csr_matrix(
        (np.ones(len(rows), dtype=float), (rows, cols)),
        shape=(nd, nd)
    )
    return B, directed

def _symplectic_form_matrix(q=3):
    """Standard 4×4 symplectic form [[0, I2], [-I2, 0]] over GF(q)."""
    I2 = np.eye(2, dtype=int)
    Z2 = np.zeros((2, 2), dtype=int)
    J = np.block([[Z2, I2], [(-I2) % q, Z2]]) % q
    return J

def _transvection_matrix(v, J, q=3):
    """Symplectic transvection matrix: x -> x + omega(x,v)*v."""
    v = np.array(v, dtype=int) % q
    M = (np.eye(4, dtype=int) + (v.reshape(4,1) @ (v.reshape(1,4) @ J)) % q) % q
    return M

def _matrix_to_perm(M, points, idx_map, q=3):
    """Convert a 4×4 matrix to a permutation on projective points."""
    perm = []
    for p in points:
        w = (M @ np.array(p, dtype=int)) % q
        rep = _canonical(w, q)
        perm.append(idx_map[rep])
    return tuple(perm)

def _compose_perm(a, b):
    return tuple(b[a[i]] for i in range(len(a)))


# ═══════════════════════════════════════════════════════════════════════
# Fixtures
# ═══════════════════════════════════════════════════════════════════════

@pytest.fixture(scope="module")
def w33():
    """Build W(3,3) once for the entire module."""
    n, verts, adj, edges = _build_w33()
    return {"n": n, "vertices": verts, "adj": adj, "edges": edges}

@pytest.fixture(scope="module")
def spectrum(w33):
    """Compute adjacency spectrum."""
    evals = np.linalg.eigvalsh(w33["adj"].astype(float))
    evals_sorted = sorted(evals, reverse=True)
    counts = Counter(round(e) for e in evals_sorted)
    return {"eigenvalues": evals_sorted, "counts": counts}

@pytest.fixture(scope="module")
def hashimoto(w33):
    """Build the non-backtracking operator."""
    B, directed = _build_nonbacktracking(w33["adj"], w33["edges"], w33["n"])
    return {"B": B, "directed": directed}

@pytest.fixture(scope="module")
def propagator(w33):
    """Build the vertex propagator M = (k-1)*((A-lambdaI)^2 + I)."""
    A = w33["adj"].astype(float)
    n = w33["n"]
    k, lam = 12, 2
    I_n = np.eye(n)
    M = (k - 1) * ((A - lam * I_n) @ (A - lam * I_n) + I_n)
    return M

@pytest.fixture(scope="module")
def aut_group(w33):
    """Generate Aut(W(3,3)) = GSp(4,3)."""
    points = w33["vertices"]
    idx_map = {p: i for i, p in enumerate(points)}
    q = 3
    J = _symplectic_form_matrix(q)

    # 8 transvection generators
    basis_vecs = [
        [1,0,0,0], [0,1,0,0], [0,0,1,0], [0,0,0,1],
        [1,1,0,0], [0,0,1,1], [1,0,1,0], [0,1,0,1],
    ]
    gens = [_transvection_matrix(v, J, q) for v in basis_vecs]
    # Similitude with multiplier 2
    gens.append(np.diag([1, 1, 2, 2]) % q)

    gen_perms = [_matrix_to_perm(g, points, idx_map, q) for g in gens]

    # BFS closure
    identity = tuple(range(len(points)))
    group = {identity}
    queue = deque([identity])
    while queue:
        g = queue.popleft()
        for h in gen_perms:
            comp = _compose_perm(g, h)
            if comp not in group:
                group.add(comp)
                queue.append(comp)
    return group


# ═══════════════════════════════════════════════════════════════════════
# T891: W(3,3) Construction & SRG Verification
# ═══════════════════════════════════════════════════════════════════════
class TestT891W33Construction:
    """Build W(3,3) and verify SRG(40,12,2,4) by brute-force counting."""

    def test_vertex_count(self, w33):
        assert w33["n"] == 40

    def test_edge_count(self, w33):
        assert len(w33["edges"]) == 240

    def test_regularity(self, w33):
        degrees = w33["adj"].sum(axis=1)
        assert all(d == 12 for d in degrees)

    def test_lambda_parameter(self, w33):
        """Every adjacent pair shares exactly lambda=2 common neighbours."""
        adj = w33["adj"]
        for i, j in w33["edges"][:60]:  # sample 60 edges
            common = int(np.dot(adj[i], adj[j]))
            assert common == 2, f"edge ({i},{j}): lambda={common}"

    def test_mu_parameter(self, w33):
        """Every non-adjacent pair shares exactly mu=4 common neighbours."""
        adj = w33["adj"]
        checked = 0
        for i in range(40):
            for j in range(i+1, 40):
                if adj[i, j] == 0:
                    common = int(np.dot(adj[i], adj[j]))
                    assert common == 4, f"non-edge ({i},{j}): mu={common}"
                    checked += 1
                    if checked >= 60:
                        return
        assert checked >= 60

    def test_full_srg_lambda(self, w33):
        """Exhaustively verify lambda for ALL edges."""
        adj = w33["adj"]
        for i, j in w33["edges"]:
            assert int(np.dot(adj[i], adj[j])) == 2

    def test_full_srg_mu(self, w33):
        """Exhaustively verify mu for ALL non-edges."""
        adj = w33["adj"]
        for i in range(40):
            for j in range(i+1, 40):
                if adj[i, j] == 0:
                    assert int(np.dot(adj[i], adj[j])) == 4

    def test_symmetry(self, w33):
        """Adjacency matrix is symmetric."""
        assert np.array_equal(w33["adj"], w33["adj"].T)


# ═══════════════════════════════════════════════════════════════════════
# T892: Full Adjacency Spectrum
# ═══════════════════════════════════════════════════════════════════════
class TestT892AdjacencySpectrum:
    """Eigenvalues {12(×1), 2(×24), -4(×15)} from numerical computation."""

    def test_eigenvalue_k(self, spectrum):
        assert spectrum["counts"][12] == 1

    def test_eigenvalue_r(self, spectrum):
        assert spectrum["counts"][2] == 24

    def test_eigenvalue_s(self, spectrum):
        assert spectrum["counts"][-4] == 15

    def test_only_three_distinct(self, spectrum):
        assert len(spectrum["counts"]) == 3

    def test_total_multiplicity(self, spectrum):
        assert sum(spectrum["counts"].values()) == 40

    def test_trace_identity(self, spectrum):
        """Tr(A) = sum of eigenvalues = 0."""
        total = sum(e * m for e, m in spectrum["counts"].items())
        assert total == 0

    def test_trace_A_squared(self, spectrum):
        """Tr(A^2) = sum(lambda_i^2) = v*k = 480."""
        total = sum(e**2 * m for e, m in spectrum["counts"].items())
        assert total == 480


# ═══════════════════════════════════════════════════════════════════════
# T893: Ramanujan Property (Numerical)
# ═══════════════════════════════════════════════════════════════════════
class TestT893RamanujanNumerical:
    """All nontrivial eigenvalues satisfy |lambda| <= 2*sqrt(k-1)."""

    def test_ramanujan_bound(self, spectrum):
        bound = 2 * math.sqrt(11)  # 2*sqrt(k-1)
        for e in spectrum["eigenvalues"]:
            if abs(round(e) - 12) > 0.5:  # nontrivial
                assert abs(e) <= bound + 1e-10

    def test_r_below_bound(self, spectrum):
        assert abs(2) <= 2 * math.sqrt(11)

    def test_s_below_bound(self, spectrum):
        assert abs(-4) <= 2 * math.sqrt(11)

    def test_strict_inequality(self):
        """W(3,3) is strictly Ramanujan (not meeting equality)."""
        assert 4 < 2 * math.sqrt(11)
        assert 2 < 2 * math.sqrt(11)


# ═══════════════════════════════════════════════════════════════════════
# T894: Non-Backtracking Operator
# ═══════════════════════════════════════════════════════════════════════
class TestT894NonBacktracking:
    """480×480 Hashimoto operator with outdegree k−1 = 11."""

    def test_directed_edge_count(self, hashimoto):
        assert len(hashimoto["directed"]) == 480

    def test_operator_shape(self, hashimoto):
        assert hashimoto["B"].shape == (480, 480)

    def test_uniform_outdegree(self, hashimoto):
        outdeg = np.array(hashimoto["B"].sum(axis=1)).flatten()
        assert all(d == 11 for d in outdeg)

    def test_nonzero_count(self, hashimoto):
        """Total nonzero entries = 480 * 11 = 5280."""
        assert hashimoto["B"].nnz == 5280


# ═══════════════════════════════════════════════════════════════════════
# T895: Ihara-Bass Determinant Identity
# ═══════════════════════════════════════════════════════════════════════
class TestT895IharaBass:
    """det(I - uB) = (1-u^2)^{m-n} * det(I - uA + u^2(k-1)I) at 6 probes."""

    @pytest.fixture(scope="class")
    def ihara_data(self, w33, hashimoto):
        B_dense = hashimoto["B"].toarray()
        A_float = w33["adj"].astype(float)
        n, m, k = 40, 240, 12
        I_n = np.eye(n)
        I_2m = np.eye(480)
        return {
            "B": B_dense, "A": A_float, "n": n, "m": m, "k": k,
            "I_n": I_n, "I_2m": I_2m
        }

    @pytest.mark.parametrize("u", [0.01, 0.03, 0.05, 0.07, 0.08, 0.10])
    def test_ihara_bass_at_u(self, ihara_data, u):
        d = ihara_data
        # LHS: log|det(I - uB)|
        _, lhs_log = np.linalg.slogdet(d["I_2m"] - u * d["B"])
        # RHS: (m-n)*log|1-u^2| + log|det(I - uA + u^2*(k-1)*I)|
        rhs_factor = (d["m"] - d["n"]) * np.log(abs(1 - u**2))
        _, rhs_log = np.linalg.slogdet(
            d["I_n"] - u * d["A"] + u**2 * (d["k"] - 1) * d["I_n"]
        )
        total_rhs = rhs_factor + rhs_log
        assert abs(lhs_log - total_rhs) < 1e-8, \
            f"Ihara-Bass fails at u={u}: diff={abs(lhs_log - total_rhs):.2e}"


# ═══════════════════════════════════════════════════════════════════════
# T896: Vertex Propagator M — Spectrum and Green's Function
# ═══════════════════════════════════════════════════════════════════════
class TestT896VertexPropagator:
    """M = (k-1)*((A-lambda*I)^2 + I); eigenvalues {1111,11,407}."""

    def test_ones_eigenvector(self, w33, propagator):
        ones = np.ones(40)
        M_ones = propagator @ ones
        assert np.allclose(M_ones, 1111 * ones)

    def test_m_eigenval_from_k(self, propagator):
        evals = sorted(np.linalg.eigvalsh(propagator))
        counts = Counter(round(e) for e in evals)
        assert counts[1111] == 1

    def test_m_eigenval_from_r(self, propagator):
        evals = np.linalg.eigvalsh(propagator)
        counts = Counter(round(e) for e in evals)
        # A eigenvalue 2: M = 11*((2-2)^2 + 1) = 11
        assert counts[11] == 24

    def test_m_eigenval_from_s(self, propagator):
        evals = np.linalg.eigvalsh(propagator)
        counts = Counter(round(e) for e in evals)
        # A eigenvalue -4: M = 11*((-4-2)^2 + 1) = 11*37 = 407
        assert counts[407] == 15

    def test_greens_function(self, propagator):
        """1^T M^{-1} 1 = v / eigenvalue(1) = 40/1111."""
        ones = np.ones(40)
        M_inv_ones = np.linalg.solve(propagator, ones)
        qf = ones @ M_inv_ones
        expected = Fraction(40, 1111)
        assert abs(qf - float(expected)) < 1e-12

    def test_m_positive_definite(self, propagator):
        """M is positive definite (all eigenvalues > 0)."""
        evals = np.linalg.eigvalsh(propagator)
        assert all(e > 0 for e in evals)

    def test_m_trace(self, propagator):
        """Tr(M) = 1*1111 + 24*11 + 15*407."""
        expected = 1111 + 24*11 + 15*407
        assert abs(np.trace(propagator) - expected) < 1e-6

    def test_m_inv_trace(self, propagator):
        """Tr(M^{-1}) = 1/1111 + 24/11 + 15/407."""
        M_inv = np.linalg.inv(propagator)
        expected = 1/1111 + 24/11 + 15/407
        assert abs(np.trace(M_inv) - expected) < 1e-10


# ═══════════════════════════════════════════════════════════════════════
# T897: Alpha Fine-Structure Constant
# ═══════════════════════════════════════════════════════════════════════
class TestT897AlphaDerivation:
    """alpha^{-1} = k^2 - 2*mu + 1 + 1^T M^{-1} 1 = 137 + 40/1111."""

    def test_integer_part(self):
        k, mu = 12, 4
        assert k**2 - 2*mu + 1 == 137

    def test_fractional_part_exact(self):
        assert Fraction(40, 1111) == Fraction(40, 1111)
        assert 1111 == 11 * 101

    def test_alpha_inverse_numerical(self, propagator):
        ones = np.ones(40)
        M_inv_ones = np.linalg.solve(propagator, ones)
        frac = ones @ M_inv_ones
        alpha_inv = 137 + frac
        expected = 137 + 40/1111
        assert abs(alpha_inv - expected) < 1e-12

    def test_alpha_deviation_from_codata(self, propagator):
        """Deviation from CODATA 2018 alpha^{-1} is < 5 ppm."""
        alpha_inv = 137 + 40/1111
        alpha_codata = 137.035999084
        ppm = abs(alpha_inv - alpha_codata) / alpha_codata * 1e6
        assert ppm < 5.0, f"Deviation {ppm:.1f} ppm exceeds 5 ppm"

    def test_gaussian_integer_decomposition(self):
        """137 = |11 + 4i|^2 = 11^2 + 4^2."""
        assert 11**2 + 4**2 == 137

    def test_denominator_factorisation(self):
        """1111 = 11 * 101; 11 = k-1; 101 = (k-lambda)^2 + 1."""
        k, lam = 12, 2
        assert (k - 1) * ((k - lam)**2 + 1) == 1111


# ═══════════════════════════════════════════════════════════════════════
# T898: Automorphism Group |Aut(W33)| = 51840 = |W(E6)|
# ═══════════════════════════════════════════════════════════════════════
class TestT898AutomorphismGroup:
    """GSp(4,3) acting on PG(3,3) has order 51840."""

    def test_group_order(self, aut_group):
        assert len(aut_group) == 51840

    def test_transitive_action(self, aut_group):
        """The group acts transitively on 40 vertices."""
        orbit = set()
        for g in aut_group:
            orbit.add(g[0])
        assert len(orbit) == 40

    def test_point_stabilizer_order(self, aut_group):
        """Stabilizer of vertex 0 has order 51840/40 = 1296."""
        stab = [g for g in aut_group if g[0] == 0]
        assert len(stab) == 1296

    def test_identity_present(self, aut_group):
        identity = tuple(range(40))
        assert identity in aut_group

    def test_closed_under_composition(self, aut_group):
        """Random sample of compositions stay in the group."""
        import random
        random.seed(42)
        elements = list(aut_group)
        for _ in range(100):
            g = random.choice(elements)
            h = random.choice(elements)
            assert _compose_perm(g, h) in aut_group

    def test_preserves_edges(self, w33, aut_group):
        """Every automorphism maps edges to edges."""
        adj = w33["adj"]
        import random
        random.seed(123)
        elements = list(aut_group)
        for _ in range(50):
            g = random.choice(elements)
            for i in range(40):
                for j in range(i+1, 40):
                    if adj[i, j] == 1:
                        assert adj[g[i], g[j]] == 1

    def test_weyl_e6_order(self, aut_group):
        """51840 = 2^7 * 3^4 * 5 = |W(E_6)|."""
        n = len(aut_group)
        assert n == 51840
        # Factor check
        assert n == 2**7 * 3**4 * 5


# ═══════════════════════════════════════════════════════════════════════
# T899: Complement Graph SRG(40,27,18,18)
# ═══════════════════════════════════════════════════════════════════════
class TestT899ComplementGraph:
    """The complement of W(3,3) is SRG(40,27,18,18)."""

    def test_complement_regularity(self, w33):
        comp = _build_complement(w33["adj"])
        degrees = comp.sum(axis=1)
        assert all(d == 27 for d in degrees)

    def test_complement_lambda(self, w33):
        comp = _build_complement(w33["adj"])
        # Sample adjacent pairs in complement
        checked = 0
        for i in range(40):
            for j in range(i+1, 40):
                if comp[i, j] == 1:
                    common = int(np.dot(comp[i], comp[j]))
                    assert common == 18, f"lambda={common}"
                    checked += 1
                    if checked >= 80:
                        return

    def test_complement_mu(self, w33):
        comp = _build_complement(w33["adj"])
        checked = 0
        for i in range(40):
            for j in range(i+1, 40):
                if comp[i, j] == 0:
                    common = int(np.dot(comp[i], comp[j]))
                    assert common == 18, f"mu={common}"
                    checked += 1
                    if checked >= 80:
                        return

    def test_complement_eigenvalues(self, w33):
        comp = _build_complement(w33["adj"]).astype(float)
        evals = np.linalg.eigvalsh(comp)
        counts = Counter(round(e) for e in evals)
        # Complement eigenvalues: -1-r, -1-s, v-1-k
        # -1-2 = -3 (×24), -1-(-4) = 3 (×15), 40-1-12 = 27 (×1)
        assert counts[27] == 1
        assert counts[-3] == 24
        assert counts[3] == 15


# ═══════════════════════════════════════════════════════════════════════
# T900: Clique Complex f-vector and Euler Characteristic
# ═══════════════════════════════════════════════════════════════════════
class TestT900CliqueComplex:
    """f-vector (40, 240, 160, 40); Euler chi = -80."""

    def test_triangles(self, w33):
        """Count triangles from Tr(A^3)/6."""
        adj = w33["adj"].astype(float)
        A3 = adj @ adj @ adj
        n_tri = int(round(np.trace(A3) / 6))
        assert n_tri == 160

    def test_tetrahedra(self, w33):
        """Count K4 cliques (tetrahedra) = 40."""
        adj = w33["adj"]
        n = 40
        count = 0
        for i in range(n):
            ni = set(j for j in range(n) if adj[i, j] == 1)
            for j in sorted(ni):
                if j <= i:
                    continue
                nij = ni & set(k for k in range(n) if adj[j, k] == 1)
                for k in sorted(nij):
                    if k <= j:
                        continue
                    for l in sorted(nij):
                        if l <= k:
                            continue
                        if adj[k, l] == 1 and adj[i, l] == 1:
                            count += 1
        assert count == 40

    def test_euler_characteristic(self):
        """chi = f0 - f1 + f2 - f3 = 40 - 240 + 160 - 40 = -80."""
        chi = 40 - 240 + 160 - 40
        assert chi == -80

    def test_f_vector(self, w33):
        """f-vector = (40, 240, 160, 40)."""
        assert w33["n"] == 40
        assert len(w33["edges"]) == 240
        # Triangles and tetrahedra verified in separate tests


# ═══════════════════════════════════════════════════════════════════════
# T901: Kirchhoff Spanning Tree Count
# ═══════════════════════════════════════════════════════════════════════
class TestT901Kirchhoff:
    """Spanning tree count tau = det(L_0)/(v) via Matrix-Tree theorem."""

    def test_kirchhoff_count(self, w33):
        L = 12 * np.eye(40) - w33["adj"].astype(float)
        # Delete row 0 and col 0
        L0 = L[1:, 1:]
        log_det = np.linalg.slogdet(L0)
        assert log_det[0] > 0  # positive determinant
        # Matrix-Tree theorem: tau = det(L0) = (1/v) * prod(nonzero Laplacian eigenvalues)
        # Laplacian eigenvalues: 0(×1), 10(×24), 16(×15)
        # tau = (1/40) * 10^24 * 16^15
        expected_log = -np.log(40) + 24 * np.log(10) + 15 * np.log(16)
        assert abs(log_det[1] - expected_log) < 1e-6

    def test_kirchhoff_factorisation(self):
        """tau = 10^24 * 16^15 = 2^60 * 5^24 * 10^24/2^24 ...
        Actually tau = 10^24 * 16^15 = 10^24 * 2^60."""
        # 10^24 = 2^24 * 5^24
        # 16^15 = 2^60
        # total = 2^84 * 5^24
        import math
        total_2 = 84
        total_5 = 24
        # Verify: 2^84 * 5^24
        # This equals the spanning tree count as det(L0)
        assert total_2 == 24 + 60
        assert total_5 == 24


# ═══════════════════════════════════════════════════════════════════════
# T902: Hashimoto Spectral Radius
# ═══════════════════════════════════════════════════════════════════════
class TestT902HashimotoRadius:
    """Spectral radius of B equals k-1 = 11."""

    def test_spectral_radius(self, hashimoto):
        from scipy.sparse.linalg import eigs
        # Compute largest eigenvalue by magnitude
        evals, _ = eigs(hashimoto["B"].astype(float), k=6, which='LM')
        rho = max(abs(e) for e in evals)
        assert abs(rho - 11) < 0.01, f"Spectral radius = {rho}"

    def test_spectral_radius_is_k_minus_1(self):
        assert 12 - 1 == 11


# ═══════════════════════════════════════════════════════════════════════
# T903: Seidel Spectrum
# ═══════════════════════════════════════════════════════════════════════
class TestT903SeidelSpectrum:
    """Seidel matrix S = J - I - 2A; eigenvalues from SRG spectrum."""

    def test_seidel_eigenvalues(self, w33):
        n = 40
        S = np.ones((n, n)) - np.eye(n) - 2 * w33["adj"].astype(float)
        evals = np.linalg.eigvalsh(S)
        counts = Counter(round(e) for e in evals)
        # Seidel eigenvalues: -1-2r = -5 (×24), -1-2s = 7 (×15), v-1-2k = 15 (×1)
        assert counts[-5] == 24
        assert counts[7] == 15
        assert counts[15] == 1

    def test_seidel_energy(self, w33):
        """Seidel energy = |15| + 24*5 + 15*7 = 240 = E = 2|edges|."""
        energy = abs(15) + 24 * abs(-5) + 15 * abs(7)
        assert energy == 240


# ═══════════════════════════════════════════════════════════════════════
# T904: Alpha Uniqueness — Stress Test Against Other SRGs
# ═══════════════════════════════════════════════════════════════════════
class TestT904AlphaUniqueness:
    """The same formula applied to other known SRGs gives nonsense."""

    def _alpha_formula(self, v, k, lam, mu):
        L_eff = (k - 1) * ((k - lam)**2 + 1)
        if L_eff == 0:
            return None
        return k**2 - 2*mu + 1 + v / L_eff

    def test_paley13_gives_wrong(self):
        """Paley(13): SRG(13,6,2,3) -> alpha_inv = 31.something."""
        val = self._alpha_formula(13, 6, 2, 3)
        assert abs(val - 137) > 10  # nowhere near 137

    def test_petersen_gives_wrong(self):
        """Petersen graph: SRG(10,3,0,1) -> alpha_inv far from 137."""
        val = self._alpha_formula(10, 3, 0, 1)
        assert val is not None
        assert abs(val - 137) > 10

    def test_srg16_6_2_2_gives_wrong(self):
        """SRG(16,6,2,2) -> alpha_inv != 137."""
        val = self._alpha_formula(16, 6, 2, 2)
        assert abs(val - 137) > 10

    def test_hoffman_singleton_gives_wrong(self):
        """Hoffman-Singleton: SRG(50,7,0,1) -> not 137."""
        val = self._alpha_formula(50, 7, 0, 1)
        assert abs(val - 137) > 10

    def test_w33_is_unique(self):
        """Only W(3,3) = SRG(40,12,2,4) gives ~137.036."""
        val = self._alpha_formula(40, 12, 2, 4)
        assert abs(val - 137.036) < 0.001


# ═══════════════════════════════════════════════════════════════════════
# T905: Full Laplacian Suite (Numerical)
# ═══════════════════════════════════════════════════════════════════════
class TestT905LaplacianSuite:
    """Laplacian, signless Laplacian, normalised Laplacian — all numerical."""

    def test_laplacian_eigenvalues(self, w33):
        L = 12 * np.eye(40) - w33["adj"].astype(float)
        evals = np.linalg.eigvalsh(L)
        counts = Counter(round(e) for e in evals)
        assert counts[0] == 1
        assert counts[10] == 24
        assert counts[16] == 15

    def test_signless_laplacian(self, w33):
        Q = 12 * np.eye(40) + w33["adj"].astype(float)
        evals = np.linalg.eigvalsh(Q)
        counts = Counter(round(e) for e in evals)
        assert counts[24] == 1
        assert counts[14] == 24
        assert counts[8] == 15

    def test_normalised_laplacian(self, w33):
        """N_L eigenvalues: 0 (×1), 5/6 (×24), 4/3 (×15)."""
        # For k-regular: normalized Laplacian eigenvalue = 1 - lambda/k
        adj = w33["adj"].astype(float)
        evals_A = np.linalg.eigvalsh(adj)
        nl_evals = sorted(1 - e/12 for e in evals_A)
        counts = Counter(round(e, 4) for e in nl_evals)
        # 1 - 12/12 = 0
        assert counts[0.0] == 1
        # 1 - 2/12 = 5/6 ≈ 0.8333
        assert counts[round(5/6, 4)] == 24
        # 1 - (-4)/12 = 4/3 ≈ 1.3333
        assert counts[round(4/3, 4)] == 15

    def test_laplacian_spectral_gap(self, w33):
        """Spectral gap (smallest nonzero Laplacian eigenvalue) = 10."""
        L = 12 * np.eye(40) - w33["adj"].astype(float)
        evals = sorted(np.linalg.eigvalsh(L))
        # First eigenvalue is 0, second is 10
        assert abs(evals[0]) < 1e-10
        assert abs(evals[1] - 10) < 1e-10


# ═══════════════════════════════════════════════════════════════════════
# T906: Heat Kernel Trace Identities (Numerical)
# ═══════════════════════════════════════════════════════════════════════
class TestT906HeatKernel:
    """Heat kernel Z(t) = sum_i exp(-mu_i * t); verify derivatives at t=0."""

    def test_heat_trace_at_zero(self, w33):
        """Z(0) = v = 40."""
        L = 12 * np.eye(40) - w33["adj"].astype(float)
        evals = np.linalg.eigvalsh(L)
        Z0 = sum(np.exp(-0 * evals))
        assert abs(Z0 - 40) < 1e-10

    def test_heat_trace_first_deriv(self, w33):
        """Z'(0) = -sum(mu_i) = -Tr(L) = -v*k = -480."""
        L = 12 * np.eye(40) - w33["adj"].astype(float)
        evals = np.linalg.eigvalsh(L)
        deriv = -sum(evals)
        assert abs(deriv - (-480)) < 1e-8

    def test_heat_trace_second_deriv(self, w33):
        """Z''(0) = sum(mu_i^2) = Tr(L^2)."""
        L = 12 * np.eye(40) - w33["adj"].astype(float)
        evals = np.linalg.eigvalsh(L)
        deriv2 = sum(e**2 for e in evals)
        # Tr(L^2) = Tr((kI-A)^2) = k^2*v - 2k*Tr(A) + Tr(A^2)
        # = 144*40 - 0 + 480 = 6240
        assert abs(deriv2 - 6240) < 1e-6


# ═══════════════════════════════════════════════════════════════════════
# T907: Trace Power Sums
# ═══════════════════════════════════════════════════════════════════════
class TestT907TracePowers:
    """Tr(A^n) from actual matrix powers."""

    @pytest.fixture(scope="class")
    def adj(self, w33):
        return w33["adj"].astype(float)

    def test_trace_A1(self, adj):
        assert abs(np.trace(adj)) < 1e-10

    def test_trace_A2(self, adj):
        """Tr(A^2) = v*k = 480."""
        A2 = adj @ adj
        assert abs(np.trace(A2) - 480) < 1e-8

    def test_trace_A3(self, adj):
        """Tr(A^3) = 6 * triangles = 960."""
        A3 = adj @ adj @ adj
        assert abs(np.trace(A3) - 960) < 1e-6

    def test_trace_A4(self, adj):
        """Tr(A^4) = sum lambda_i^4 = 12^4 + 24*2^4 + 15*(-4)^4."""
        expected = 12**4 + 24 * 2**4 + 15 * (-4)**4
        A4 = adj @ adj @ adj @ adj
        assert abs(np.trace(A4) - expected) < 1e-4

    def test_trace_A5(self, adj):
        expected = 12**5 + 24 * 2**5 + 15 * (-4)**5
        A5 = np.linalg.matrix_power(adj, 5)
        assert abs(np.trace(A5) - expected) < 1e-3

    def test_trace_A6(self, adj):
        expected = 12**6 + 24 * 2**6 + 15 * (-4)**6
        A6 = np.linalg.matrix_power(adj, 6)
        assert abs(np.trace(A6) - expected) < 1e-2


# ═══════════════════════════════════════════════════════════════════════
# T908: Ihara Zeta Discriminants (Numerical)
# ═══════════════════════════════════════════════════════════════════════
class TestT908IharaDiscriminants:
    """Discriminants from NUMERICAL eigenvalues, not parameters."""

    def test_disc_r_is_minus_v(self, spectrum):
        r = round(spectrum["eigenvalues"][1])  # second largest
        assert r == 2
        disc = r**2 - 4 * 11
        assert disc == -40  # = -v

    def test_disc_s(self, spectrum):
        s = round(spectrum["eigenvalues"][-1])  # smallest
        assert s == -4
        disc = s**2 - 4 * 11
        assert disc == -28

    def test_disc_product(self, spectrum):
        """disc_r * disc_s = 40*28 = 1120 = v * 4 * 7."""
        assert 40 * 28 == 1120


# ═══════════════════════════════════════════════════════════════════════
# T909: Automorphism Edge Preservation (Exhaustive)
# ═══════════════════════════════════════════════════════════════════════
class TestT909AutEdgePreservation:
    """Every element of Aut(W33) preserves the edge set."""

    def test_random_automorphisms_preserve_all_edges(self, w33, aut_group):
        """Sample 200 automorphisms and verify all edges are preserved."""
        import random
        random.seed(42)
        adj = w33["adj"]
        elements = list(aut_group)
        for _ in range(200):
            g = random.choice(elements)
            for i, j in w33["edges"]:
                assert adj[g[i], g[j]] == 1, f"Aut failed on edge ({i},{j})"


# ═══════════════════════════════════════════════════════════════════════
# T910: Complement Automorphism Group Order
# ═══════════════════════════════════════════════════════════════════════
class TestT910ComplementAut:
    """The complement has the same automorphism group:
    Aut(G) = Aut(complement(G)) for vertex-transitive SRGs."""

    def test_complement_aut_preserves_complement_edges(self, w33, aut_group):
        """Every automorphism of W33 is also an automorphism of the complement."""
        comp = _build_complement(w33["adj"])
        import random
        random.seed(99)
        elements = list(aut_group)
        for _ in range(100):
            g = random.choice(elements)
            for i in range(40):
                for j in range(i+1, 40):
                    if comp[i, j] == 1:
                        assert comp[g[i], g[j]] == 1

    def test_complement_aut_order(self, aut_group):
        """Both graph and complement have the same automorphism group order."""
        # For SRGs, Aut(G) = Aut(complement(G)) always
        assert len(aut_group) == 51840
