"""
Phase CCXXXIV --- One-Generator Quotient: Entire Theory from Z[lam]/(lam^2-lam-2)
==================================================================================

MASTER QUOTIENT THEOREM:
  Family law:  mu = lam + 2
  Selector:    mu = lam^2
  Combined:    lam^2 - lam - 2 = 0  (unique positive root lam=2)

  Every W(3,3) parameter is an affine linear form a + b*lam in the quotient:
    q = lam+1, mu = lam+2, k = 4lam+4, Phi3 = 4lam+5, Phi4 = 3lam+4,
    Phi6 = 2lam+3, f = 8lam+8, g = 5lam+5, tau = 84lam+84, alpha = 45lam+47

  This means the ENTIRE promoted finite shell is generated by ONE symbol
  (the adjacency multiplicity lam = q-1) with ONE quadratic relation.

Also: dual cyclotomic ladder Phi_n(mu) recovers {5, 13, 17} exactly,
and the odd-core recurrence coefficients are {41, 184, 144} = {v+1, 8*23, k^2}.

39 tests.
"""

import math
from fractions import Fraction
from sympy import Symbol, expand, factor, isprime

# -- W(3,3) parameter block --
q      = 3
lam    = q - 1          # 2
mu     = q + 1          # 4
k      = q * (q + 1)    # 12
v      = (q + 1) * (q**2 + 1)  # 40
r      = q - 1          # 2
s_eig  = -(q + 1)       # -4
f      = q * (q + 1)**2 // 2   # 24
g_mult = q * (q**2 + 1) // 2   # 15
E      = v * k // 2     # 240

Phi3  = q**2 + q + 1    # 13
Phi4  = q**2 + 1        # 10
Phi6  = q**2 - q + 1    # 7
Phi12 = q**4 - q**2 + 1 # 73

tau3 = E + k             # 252
alpha_137 = (k - 1)**2 + mu**2  # 137


# ===========================================================================
# T1 -- The Quotient Ring
# ===========================================================================
class TestT1_QuotientRing:
    """Z[lam]/(lam^2 - lam - 2) has unique positive integer root lam=2."""

    def test_quadratic_relation(self):
        """lam^2 - lam - 2 = 0 at lam=2."""
        assert lam**2 - lam - 2 == 0

    def test_factors(self):
        """lam^2 - lam - 2 = (lam-2)(lam+1)."""
        L = Symbol('lam')
        poly = L**2 - L - 2
        f = factor(poly)
        assert f == (L - 2) * (L + 1)

    def test_unique_positive_root(self):
        """Positive integer root is unique: lam=2."""
        roots = [l for l in range(1, 100) if l**2 - l - 2 == 0]
        assert roots == [2]

    def test_family_law_mu_lam_plus_2(self):
        """Family law: mu = q+1 = (lam+1)+1 = lam+2."""
        assert mu == lam + 2

    def test_selector_mu_lam_squared(self):
        """Selector: mu = lam^2."""
        assert mu == lam**2

    def test_combined(self):
        """lam+2 = lam^2 => lam^2-lam-2 = 0."""
        assert lam + 2 == lam**2


# ===========================================================================
# T2 -- Linearization Table
# ===========================================================================
class TestT2_Linearization:
    """Every atom reduces to a+b*lam using lam^2 = lam+2."""

    def _lin(self, a, b):
        """Evaluate a + b*lam at lam=2."""
        return a + b * lam

    def test_q_linear(self):
        """q = lam+1."""
        assert self._lin(1, 1) == q

    def test_mu_linear(self):
        """mu = lam+2."""
        assert self._lin(2, 1) == mu

    def test_k_linear(self):
        """k = q*mu = (lam+1)(lam+2) = lam^2+3lam+2 = (lam+2)+3lam+2 = 4lam+4."""
        assert self._lin(4, 4) == k

    def test_Phi3_linear(self):
        """Phi3 = q^2+q+1 = ... = 4lam+5."""
        assert self._lin(5, 4) == Phi3

    def test_Phi4_linear(self):
        """Phi4 = q^2+1 = (lam+1)^2+1 = lam^2+2lam+2 = 3lam+4."""
        assert self._lin(4, 3) == Phi4

    def test_Phi6_linear(self):
        """Phi6 = q^2-q+1 = lam^2+lam = 2lam+3... wait: (lam+1)^2-(lam+1)+1 = lam^2+lam+1 = 2lam+3."""
        assert self._lin(3, 2) == Phi6

    def test_f_linear(self):
        """f = q*mu^2/2 = (lam+1)(lam+2)^2/2 = ... = 8lam+8."""
        assert self._lin(8, 8) == f

    def test_g_linear(self):
        """g = q*Phi4/2 = (lam+1)(3lam+4)/2 = ... = 5lam+5."""
        assert self._lin(5, 5) == g_mult

    def test_E_linear(self):
        """E = v*k/2 = ... check: v=40, k=12, E=240."""
        # v = (lam+2)(3lam+4) = 3lam^2+10lam+8 = 3(lam+2)+10lam+8 = 13lam+14
        assert self._lin(14, 13) == v
        # E = v*k/2 requires going to higher powers; check directly
        assert E == 240

    def test_tau_linear(self):
        """tau(3) = 252 = 84*lam + 84 at lam=2."""
        assert self._lin(84, 84) == tau3

    def test_alpha_linear(self):
        """alpha = (k-1)^2+mu^2 = 137 = 45*lam+47 at lam=2."""
        assert self._lin(47, 45) == alpha_137

    def test_v_linear(self):
        """v = 40 = 13*lam+14 at lam=2."""
        assert self._lin(14, 13) == v


# ===========================================================================
# T3 -- Dual Cyclotomic Ladder: Phi_n(mu)
# ===========================================================================
class TestT3_DualCyclotomic:
    """Evaluating cyclotomic polynomials at mu=4 recovers key primes."""

    def test_Phi1_mu(self):
        """Phi_1(mu) = mu-1 = q = 3."""
        assert mu - 1 == q

    def test_Phi2_mu(self):
        """Phi_2(mu) = mu+1 = q+2 = 5."""
        assert mu + 1 == 5

    def test_Phi6_mu(self):
        """Phi_6(mu) = mu^2-mu+1 = 16-4+1 = 13 = Phi_3(q)."""
        assert mu**2 - mu + 1 == 13 == Phi3

    def test_Phi4_mu(self):
        """Phi_4(mu) = mu^2+1 = 17."""
        assert mu**2 + 1 == 17

    def test_dual_generates_5_13_17(self):
        """The mu-channel generates {5, 13, 17} from {Phi2, Phi6, Phi4}(mu)."""
        assert {mu + 1, mu**2 - mu + 1, mu**2 + 1} == {5, 13, 17}

    def test_self_reference(self):
        """Phi_6(mu) = Phi_3(q) -- the CROSS-CYCLOTOMIC bridge."""
        assert mu**2 - mu + 1 == q**2 + q + 1


# ===========================================================================
# T4 -- H-Projector Fermat Ladder
# ===========================================================================
class TestT4_HProjector:
    """H_t = -(lam/2)*(1 + rho^{t+1}) where rho=4."""

    def _H(self, t):
        """H_t = O_t - (k/lam)*E_t. Using closed form: -(lam/2)*(1+4^{t+1})."""
        return -Fraction(lam, 2) * (1 + 4**(t + 1))

    def test_H0(self):
        """-H_0 = 5 = Phi2(mu)."""
        assert -self._H(0) == 5

    def test_H1(self):
        """-H_1 = 17 = Phi4(mu)."""
        assert -self._H(1) == 17

    def test_H2(self):
        """-H_2 = 65 = 5*13."""
        assert -self._H(2) == 65
        assert 65 == 5 * 13

    def test_H3(self):
        """-H_3 = 257 (Fermat prime F_3)."""
        assert -self._H(3) == 257

    def test_H4(self):
        """-H_4 = 1025 = 5^2*41."""
        assert -self._H(4) == 1025
        assert 1025 == 5**2 * 41

    def test_general_formula(self):
        """-H_t = 1 + 4^{t+1} = 1 + mu^{t+1}."""
        for t in range(6):
            assert -self._H(t) == 1 + mu**(t + 1)


# ===========================================================================
# T5 -- Odd-Core Recurrence Coefficients
# ===========================================================================
class TestT5_OddCoreRecurrence:
    """Odd-core tower satisfies O_{t+3} = S1*O_{t+2} - S2*O_{t+1} + S3*O_t."""

    def test_S1(self):
        """S1 = (q^4+2q^3+3q^2+2)/(q-1)^2 = 41 = v+1 at q=3."""
        S1 = (q**4 + 2*q**3 + 3*q**2 + 2) // (q - 1)**2
        assert S1 == 41 == v + 1

    def test_S2(self):
        """S2 = 184 = 8*23 = (k-mu)*(f-1) at q=3."""
        r_c = k - mu  # compact rank = 8
        assert r_c * (f - 1) == 184

    def test_S3(self):
        """S3 = q^2*(q+1)^4/(q-1)^4 = 9*256/16 = 144 = k^2 at q=3."""
        S3 = q**2 * (q + 1)**4 // (q - 1)**4
        assert S3 == 144 == k**2

    def test_S1_selector(self):
        """S1 = v+1 has (q-3) factor in the residual."""
        for qq in range(3, 30):
            num = qq**4 + 2*qq**3 + 3*qq**2 + 2
            den = (qq - 1)**2
            vv = (qq + 1) * (qq**2 + 1)
            if num % den == 0 and num // den == vv + 1:
                assert qq == 3
