"""
Phase CCLXX — One-Generator Quotient: Z[λ]/(λ²−λ−2)
=======================================================

THEOREM (Master Quotient):

The principal selector μ = λ² combined with the family law μ = λ+2 gives:

  λ² − λ − 2 = 0    ⟹    (λ−2)(λ+1) = 0

Unique positive integer root: λ = 2, hence q = 3, μ = 4.

Inside this quotient, λ² = λ + 2, so every promoted atom linearizes:

  q = λ+1 = 3        Φ₃ = 4λ+5 = 13      f = 8λ+8 = 24
  μ = λ+2 = 4        Φ₄ = 3λ+4 = 10      g = 5λ+5 = 15
  k = 4λ+4 = 12      Φ₆ = 2λ+3 = 7       α = 45λ+47 = 137
  E = 40λ+40 = 120   τ = 84λ+84 = 252

The entire W(3,3) theory is generated by ONE symbol with ONE quadratic relation.

SOURCE: W33_one_generator_quotient_20260330.zip
"""
import pytest

# ── The quotient ──
lam = 2   # unique positive root of λ²−λ−2=0


def _lin(a, b):
    """Evaluate a + b·λ in the quotient."""
    return a + b * lam


# ================================================================
# T1: The selector equation
# ================================================================
class TestT1_SelectorEquation:
    """λ²−λ−2 = 0 with unique positive root λ=2."""

    def test_equation_satisfied(self):
        assert lam**2 - lam - 2 == 0

    def test_factored(self):
        assert (lam - 2) * (lam + 1) == 0

    def test_unique_positive(self):
        """Only positive integer root is 2."""
        for x in range(1, 20):
            if x**2 - x - 2 == 0:
                assert x == 2

    def test_from_mu_equals_lam2(self):
        """μ=λ² and μ=λ+2 give λ²−λ−2=0."""
        # μ = λ² and μ = λ+2 ⟹ λ²=λ+2 ⟹ λ²−λ−2=0
        assert lam**2 == lam + 2


# ================================================================
# T2: Linearization table
# ================================================================
class TestT2_LinearizationTable:
    """Every atom = a + b·λ evaluated at λ=2."""

    def test_q(self):
        assert _lin(1, 1) == 3

    def test_mu(self):
        assert _lin(2, 1) == 4

    def test_k(self):
        assert _lin(4, 4) == 12

    def test_Phi3(self):
        assert _lin(5, 4) == 13

    def test_Phi4(self):
        assert _lin(4, 3) == 10

    def test_Phi6(self):
        assert _lin(3, 2) == 7

    def test_f(self):
        assert _lin(8, 8) == 24

    def test_g(self):
        assert _lin(5, 5) == 15

    def test_E(self):
        assert _lin(40, 40) == 120

    def test_tau(self):
        assert _lin(84, 84) == 252

    def test_alpha(self):
        assert _lin(47, 45) == 137

    def test_mu_squared(self):
        assert _lin(6, 5) == 16


# ================================================================
# T3: Lambda-squared reduction rule
# ================================================================
class TestT3_ReductionRule:
    """λ² = λ + 2 is the only reduction needed."""

    def test_lam_squared(self):
        assert lam**2 == lam + 2

    def test_lam_cubed(self):
        """λ³ = λ·λ² = λ(λ+2) = λ²+2λ = (λ+2)+2λ = 3λ+2."""
        assert lam**3 == 3*lam + 2

    def test_lam_fourth(self):
        """λ⁴ = (3λ+2)λ = 3λ²+2λ = 3(λ+2)+2λ = 5λ+6."""
        assert lam**4 == 5*lam + 6


# ================================================================
# T4: Cross-verification with standard W(3,3) values
# ================================================================
class TestT4_CrossVerification:
    """Linearized values match the standard W(3,3) parameters."""

    def test_v(self):
        """v = (q+1)(q²+1) = μ·Φ₄ = (λ+2)(3λ+4) = ...evaluate..."""
        q = lam + 1
        v = (q + 1) * (q**2 + 1)
        assert v == 40

    def test_k_from_q_mu(self):
        q = lam + 1
        mu = lam + 2
        assert q * mu == 12

    def test_alpha_from_atoms(self):
        k = 4 * lam + 4
        mu = lam + 2
        assert (k - 1)**2 + mu**2 == 137

    def test_neutrino_sum(self):
        """Σmν = λ(v−k+1) = 2·29 = 58 (in meV units)."""
        v, k_ = 40, 12
        assert lam * (v - k_ + 1) == 58


# ================================================================
# T5: All selectors have (λ−2) factor
# ================================================================
class TestT5_SelectorIdeal:
    """Every q=3-only identity factors through (λ−2)."""

    def test_mu_minus_lam2(self):
        """μ − λ² = −(λ−2)(λ+1)."""
        assert -(lam - 2) * (lam + 1) == 0

    def test_k_minus_3mu(self):
        """k − 3μ = (λ−2)(λ+2)."""
        k = (lam + 1) * (lam + 2)
        mu = lam + 2
        assert k - 3*mu == (lam - 2) * (lam + 2)

    def test_rho_equals_mu(self):
        """ρ = μ in the quotient."""
        rho = ((lam + 2) // lam)**2 if lam != 0 else None
        mu = lam + 2
        assert rho == mu
