"""
Phase CCXXX --- Master Selector Ideal: All q=3 Uniqueness from One Principal Selector
=====================================================================================

MASTER THEOREM:  mu = lam^2  <==>  (q+1) = (q-1)^2  <==>  q(q-3) = 0

All promoted exact identities in the W(3,3) theory split into:
  1. FAMILY identities: hold for all GQ(q,q) (any prime power q)
  2. SELECTOR identities: vanish at q=3 with numerators factoring through (q-3)

The entire selector ideal is generated by the single principal selector mu = lam^2.
This is NOT a pile of unrelated miracles -- it is ONE family skeleton + ONE selector.

Also encodes: spectral moment ratio M5/M3 = 244, multiplicity bootstrap,
Gaussian selector ladder (13 = N(3+2i), 41 = N(4+5i)), hexad closure.

52 tests verifying the master selector structure.
"""

import math
from fractions import Fraction
from sympy import Symbol, expand, factor, isprime

# -- W(3,3) parameter block --
q      = 3
lam    = q - 1          # 2
mu     = q + 1          # 4
k      = q * (q + 1)    # 12
v      = (q + 1) * (q**2 + 1)  # 40
r      = q - 1          # 2
s      = -(q + 1)       # -4
f      = q * (q + 1)**2 // 2   # 24
g_mult = q * (q**2 + 1) // 2   # 15
E      = v * k // 2     # 240

Phi3  = q**2 + q + 1    # 13
Phi4  = q**2 + 1        # 10
Phi6  = q**2 - q + 1    # 7
Phi12 = q**4 - q**2 + 1 # 73

alpha_137 = (k - 1)**2 + mu**2  # 137

# Symbolic q for family/selector factorization proofs
Q = Symbol('q')
LAM = Q - 1
MU = Q + 1
K = Q * (Q + 1)
V = (Q + 1) * (Q**2 + 1)
F_sym = Q * (Q + 1)**2 / 2
G_sym = Q * (Q**2 + 1) / 2
PHI3 = Q**2 + Q + 1
PHI4 = Q**2 + 1
PHI6 = Q**2 - Q + 1


# ===========================================================================
# T1 -- Principal Selector: mu = lam^2
# ===========================================================================
class TestT1_PrincipalSelector:
    """mu - lam^2 = -(q)(q-3). The MASTER selector."""

    def test_mu_equals_lam_squared(self):
        """At q=3: mu = 4 = lam^2 = 2^2."""
        assert mu == lam**2

    def test_principal_selector_polynomial(self):
        """mu - lam^2 = (q+1) - (q-1)^2 = -q^2 + 3q = -q(q-3)."""
        expr = expand(MU - LAM**2)
        assert expr == expand(-Q * (Q - 3))

    def test_unique_positive_root(self):
        """q(q-3) = 0 has unique positive solution q=3 over prime powers."""
        for qq in range(2, 100):
            if (qq + 1) == (qq - 1)**2:
                assert qq == 3

    def test_mu_squared_equals_k_plus_mu(self):
        """FAMILY: mu^2 = k + mu (always, since (q+1)^2 = q(q+1) + (q+1))."""
        assert mu**2 == k + mu
        # Symbolic verification
        assert expand(MU**2 - K - MU) == 0

    def test_Phi3_minus_mu_minus_Phi6_minus_lam(self):
        """FAMILY: Phi3 - mu - Phi6 - lam = 0 for all q."""
        assert Phi3 - mu - Phi6 - lam == 0
        assert expand(PHI3 - MU - PHI6 - LAM) == 0


# ===========================================================================
# T2 -- Selector Ideal: All Factor Through (q-3)
# ===========================================================================
class TestT2_SelectorIdeal:
    """Every promoted q=3-only identity has (q-3) as a factor."""

    def test_k_minus_3mu(self):
        """k - 3*mu factors as (q-3)*(q+1)."""
        diff = expand(K - 3 * MU)
        assert diff.subs(Q, 3) == 0
        assert expand(diff - (Q - 3) * (Q + 1)) == 0

    def test_Phi4_plus_mu2_minus_lam_Phi3(self):
        """Phi4 + mu^2 - lam*Phi3 factors through (q-3)."""
        expr = expand(PHI4 + MU**2 - LAM * PHI3)
        assert expr.subs(Q, 3) == 0
        # Factor out (q-3)
        f = factor(expr)
        assert f.subs(Q, 3) == 0

    def test_Phi6_plus_k_minus_mu_minus_g(self):
        """Phi6 + k - mu - g has (q-3) factor."""
        expr = expand(PHI6 + K - MU - G_sym)
        assert expr.subs(Q, 3) == 0

    def test_numerical_k_3mu(self):
        """k - 3*mu = 12 - 12 = 0 at q=3."""
        assert k == 3 * mu

    def test_numerical_rho_equals_mu(self):
        """rho = ((q+1)/(q-1))^2 = mu at q=3: 4/1 = 4."""
        rho = Fraction(mu, lam)**2
        assert rho == mu

    def test_kappa_equals_mu_q2(self):
        """kappa = (k/lam)^2 = mu*q^2 at q=3: 36 = 4*9."""
        kappa = Fraction(k, lam)**2
        assert kappa == mu * q**2


# ===========================================================================
# T3 -- Family Identities (hold for ALL q)
# ===========================================================================
class TestT3_FamilyIdentities:
    """Identities that are NOT q=3 specific; they hold for entire GQ(q,q) family."""

    def test_mu_squared_family(self):
        """mu^2 = k + mu for all q."""
        for qq in range(2, 20):
            assert (qq + 1)**2 == qq * (qq + 1) + (qq + 1)

    def test_cyclotomic_sum_family(self):
        """Phi3 = mu + Phi6 + lam for all q."""
        for qq in range(2, 20):
            p3 = qq**2 + qq + 1
            p6 = qq**2 - qq + 1
            assert p3 == (qq + 1) + p6 + (qq - 1)

    def test_edge_count_family(self):
        """E = v*k/2 for all q."""
        for qq in range(2, 20):
            vv = (qq + 1) * (qq**2 + 1)
            kk = qq * (qq + 1)
            assert vv * kk % 2 == 0

    def test_f_plus_g_equals_v_minus_1(self):
        """f + g = v - 1 for all q."""
        assert f + g_mult == v - 1
        for qq in range(2, 20):
            ff = qq * (qq + 1)**2 // 2
            gg = qq * (qq**2 + 1) // 2
            vv = (qq + 1) * (qq**2 + 1)
            assert ff + gg == vv - 1

    def test_f_minus_g_equals_q_squared(self):
        """f - g = q^2 for all q."""
        assert f - g_mult == q**2
        for qq in range(2, 20):
            ff = qq * (qq + 1)**2 // 2
            gg = qq * (qq**2 + 1) // 2
            assert ff - gg == qq**2


# ===========================================================================
# T4 -- Multiplicity Bootstrap: (f,g) = (24,15) Reconstructs Everything
# ===========================================================================
class TestT4_MultiplicityBootstrap:
    """The pair (f,g) = (24,15) alone reconstructs the full W(3,3) parameter set."""

    def test_q_from_fg(self):
        """q = sqrt(f-g) = sqrt(9) = 3."""
        assert math.isqrt(f - g_mult) == q

    def test_v_from_fg(self):
        """v = 1 + f + g = 40."""
        assert 1 + f + g_mult == v

    def test_E_from_fg(self):
        """E = 2*f*g/q = 2*24*15/3 = 240."""
        assert 2 * f * g_mult // q == E

    def test_k_from_fg(self):
        """k = 2E/v = 480/40 = 12."""
        assert 2 * E // v == k

    def test_mu_from_fg(self):
        """mu^2 = 2f/q = 48/3 = 16, mu = 4."""
        assert 2 * f // q == mu**2

    def test_Phi4_from_fg(self):
        """Phi4 = 2g/q = 30/3 = 10."""
        assert 2 * g_mult // q == Phi4

    def test_24_15_are_leech_moonshine(self):
        """f=24 = dim(Leech lattice); g=15 = kissing number of D_4."""
        assert f == 24
        assert g_mult == 15


# ===========================================================================
# T5 -- Spectral Moment Ratio: M5/M3 = 244
# ===========================================================================
class TestT5_SpectralMomentRatio:
    """M5/M3 = 244 = v*Phi6 - mu*q^2 = g*Phi3 + Phi6^2 (both q=3 only)."""

    def _M(self, n):
        """Compute M_n = sum of n-th powers of adjacency eigenvalues with multiplicities."""
        return 1 * k**n + f * r**n + g_mult * s**n

    def test_M3_value(self):
        """M3 = k^3 + f*r^3 + g*s^3 = 1728 + 192 + (-960) = 960."""
        assert self._M(3) == 960

    def test_M5_value(self):
        """M5 = k^5 + f*r^5 + g*s^5 = 248832 + 768 + (-15360) = 234240."""
        assert self._M(5) == 234240

    def test_M5_over_M3(self):
        """M5/M3 = 234240/960 = 244."""
        assert self._M(5) // self._M(3) == 244
        assert self._M(5) % self._M(3) == 0

    def test_244_decomposition_A(self):
        """244 = v*Phi6 - mu*q^2 = 280 - 36."""
        assert v * Phi6 - mu * q**2 == 244

    def test_244_decomposition_B(self):
        """244 = g*Phi3 + Phi6^2 = 195 + 49."""
        assert g_mult * Phi3 + Phi6**2 == 244

    def test_decomposition_A_selector(self):
        """v*Phi6 - mu*q^2 - M5/M3 has factor (q-3) for family GQ(q,q)."""
        for qq in range(2, 30):
            kk = qq * (qq + 1)
            rr = qq - 1
            ss = -(qq + 1)
            ff = qq * (qq + 1)**2 // 2
            gg = qq * (qq**2 + 1) // 2
            vv = (qq + 1) * (qq**2 + 1)
            pp6 = qq**2 - qq + 1
            M3 = kk**3 + ff * rr**3 + gg * ss**3
            M5 = kk**5 + ff * rr**5 + gg * ss**5
            ratio = M5 // M3
            decomp_A = vv * pp6 - (qq + 1) * qq**2
            diff = ratio - decomp_A
            if qq != 3:
                assert diff != 0
            else:
                assert diff == 0

    def test_decomposition_B_selector(self):
        """g*Phi3 + Phi6^2 - M5/M3 has factor (q-3) for family GQ(q,q)."""
        for qq in range(2, 30):
            kk = qq * (qq + 1)
            rr = qq - 1
            ss = -(qq + 1)
            ff = qq * (qq + 1)**2 // 2
            gg = qq * (qq**2 + 1) // 2
            pp3 = qq**2 + qq + 1
            pp6 = qq**2 - qq + 1
            M3 = kk**3 + ff * rr**3 + gg * ss**3
            M5 = kk**5 + ff * rr**5 + gg * ss**5
            ratio = M5 // M3
            decomp_B = gg * pp3 + pp6**2
            diff = ratio - decomp_B
            if qq != 3:
                assert diff != 0
            else:
                assert diff == 0


# ===========================================================================
# T6 -- Gaussian Selector Ladder
# ===========================================================================
class TestT6_GaussianSelectors:
    """W(3,3) key primes are Gaussian integer norms at q=3."""

    def test_13_is_gaussian_norm(self):
        """Phi3 = 13 = N(q + (q-1)*i) = N(3+2i) = 9+4."""
        N = q**2 + (q - 1)**2
        assert N == 13 == Phi3

    def test_41_is_gaussian_norm(self):
        """v+1 = 41 = N((q+1) + (q+2)*i) = N(4+5i) = 16+25."""
        N = (q + 1)**2 + (q + 2)**2
        assert N == 41 == v + 1

    def test_13_gaussian_selector(self):
        """N(q+(q-1)i) = Phi3 only at q=3 (scan 2..80)."""
        hits = []
        for qq in range(2, 81):
            N = qq**2 + (qq - 1)**2
            p3 = qq**2 + qq + 1
            if N == p3:
                hits.append(qq)
        assert hits == [3]

    def test_41_gaussian_selector(self):
        """N((q+1)+(q+2)i) = v+1 only at q=3 (scan 2..80)."""
        hits = []
        for qq in range(2, 81):
            N = (qq + 1)**2 + (qq + 2)**2
            vv = (qq + 1) * (qq**2 + 1) + 1
            if N == vv:
                hits.append(qq)
        assert hits == [3]


# ===========================================================================
# T7 -- Hexad: 6-Prime Shell {2,3,5,7,11,13}
# ===========================================================================
class TestT7_Hexad:
    """The initial Monster/Bernoulli shell {2,3,5,7,11,13} = W(3,3) atoms."""

    def test_hexad_atoms(self):
        """Six atoms: lam=2, q=3, Phi4/lam=5, Phi6=7, k-1=11, Phi3=13."""
        atoms = {lam, q, Phi4 // lam, Phi6, k - 1, Phi3}
        assert atoms == {2, 3, 5, 7, 11, 13}

    def test_den_B12(self):
        """den(B_12) = 2730 = 2*3*5*7*13 (all hexad primes except 11)."""
        assert 2730 == 2 * 3 * 5 * 7 * 13

    def test_den_B10(self):
        """den(B_10) = 66 = 2*3*11 = lam*q*(k-1)."""
        assert 66 == lam * q * (k - 1)
        assert 66 == 2 * 3 * 11

    def test_1_plus_2k_is_perfect_square(self):
        """1+2k = 25 = 5^2. Unique among prime powers q=2..80."""
        assert 1 + 2 * k == 25
        assert math.isqrt(1 + 2 * k)**2 == 1 + 2 * k
        # Build prime power set
        pp_set = set()
        for p in range(2, 81):
            if isprime(int(p)):
                pp_set.add(p)
                pk = p
                while pk * p <= 80:
                    pk *= p
                    pp_set.add(pk)
        hits = []
        for qq in sorted(pp_set):
            kk = qq * (qq + 1)
            val = 1 + 2 * kk
            sqrt_val = math.isqrt(val)
            if sqrt_val * sqrt_val == val:
                hits.append(qq)
        assert hits == [3]

    def test_den_B2_selector(self):
        """den(B_2) = lam*q = 6. Equation (q-1)*q = 6 has unique solution q=3."""
        assert lam * q == 6
        hits = []
        for qq in range(2, 81):
            if (qq - 1) * qq == 6:
                hits.append(qq)
        assert hits == [3]

    def test_hexad_all_prime(self):
        """All 6 hexad members are prime."""
        for p in [2, 3, 5, 7, 11, 13]:
            assert isprime(p)
