"""
Phase CCLXXIV: r/s sector asymmetry.

THEOREM: The W(3,3) j-tower is entirely generated by the s-eigenspace sector (p2).
  s-sector (p2): disc = -4*Phi6 = -28, h = 1 (Heegner)
  r-sector (p1): disc = -4*Phi4 = -40, h = 2
The j-values of the s-sector are clean cubes in the W(3,3) parameter ring.
The j-values of the r-sector are NOT W(3,3) parameter ring members.
"""

import sympy
import pytest

v, k, l, m, q = 40, 12, 2, 4, 3
Phi3, Phi4, Phi6 = 13, 10, 7
f_dim, g_dim = 24, 15
ev_r, ev_s = 2, -4

heegner = {1, 2, 3, 4, 7, 8, 11, 19, 43, 67, 163}

cm_j_s_sector = {-7: -3375, -28: 16581375}
cm_j_standard = {-4: 1728, -8: 8000, -11: -32768}


class TestRSSectorAsymmetry:

    def test_p2_disc_is_neg4_Phi6(self):
        assert ev_s**2 - 4*(k-1) == -4 * Phi6

    def test_p1_disc_is_neg4_Phi4(self):
        assert ev_r**2 - 4*(k-1) == -4 * Phi4

    def test_s_sector_field_class_number_1(self):
        assert Phi6 in heegner

    def test_r_sector_field_class_number_2(self):
        assert Phi4 not in heegner

    def test_s_sector_j_neg7_clean(self):
        assert cm_j_s_sector[-7] == -(g_dim**3)

    def test_s_sector_j_neg28_clean(self):
        assert cm_j_s_sector[-28] == 255**3
        assert q * (Phi4//2) * (Phi4+Phi6) == 255

    def test_shimura_ratio_is_Phi4_Phi6_cube(self):
        assert cm_j_s_sector[-28] // abs(cm_j_s_sector[-7]) == (Phi4+Phi6)**3

    def test_all_s_sector_j_are_cubes(self):
        for D, j_val in cm_j_s_sector.items():
            cr = round(abs(j_val)**(1/3))
            assert cr**3 == abs(j_val)

    def test_C4_is_s_sector_heegner(self):
        """C4 = Phi6(q) Heegner = s-sector CM field has h=1."""
        assert Phi6 in heegner
        assert Phi4 not in heegner

    def test_j_tower_all_five_entries_are_cubes(self):
        all_j = {**cm_j_standard, **cm_j_s_sector}
        for D, j_val in all_j.items():
            cr = round(abs(j_val)**(1/3))
            assert cr**3 == abs(j_val), f"|j({D})| not a perfect cube"

    def test_r_sector_not_in_W33_ring(self):
        W33_params = [k, g_dim, f_dim, v, v//2, Phi3, Phi4, Phi6, q, m, k-1]
        j_r_approx = [425671415, 21385]
        for j_val in j_r_approx:
            for p in W33_params:
                for power in range(2, 8):
                    assert p**power != j_val

    def test_255_W33_factorization(self):
        assert 255 == q * (Phi4//2) * (Phi4+Phi6)
        assert sympy.factorint(255) == {3: 1, 5: 1, 17: 1}
        assert Phi4 + Phi6 == 17
