#!/usr/bin/env python3
"""Pillar 86 (Part CXCII): Twist Transport, Reye Configurations, and Hard Conjugacy Obstruction

Six theorems characterising how the true tomotope maniplex relates to the
axis-192 flag model via the conjugating bijection pi, and why no axis-192
index-2 subgroup can reproduce the tomotope's published edge symmetry group P:

  T1  The bijection pi: {0..191} -> {0..191} is a permutation with 50 fixed
      points and cycle structure {1:50, 4:1, 9:2, 27:2, 66:1}.  It maps the
      true tomotope generators into axis-192 coordinates fixing r0 and r3
      exactly (transported r0 = axis r0, transported r3 = axis r3).

  T2  The transported generators tr0..tr3 satisfy the correct tomotope
      Coxeter diagram: |r0r1|=3, |r1r2|=12, |r2r3|=4, and |r0r2|=|r0r3|=
      |r1r3|=2.  All four transported generators are involutions (order 2).

  T3  The twist elements d1 = (transported r1) * (axis r1)^-1 and
      d2 = (transported r2) * (axis r2)^-1 have no fixed points.  d1 has
      cycle structure {2:4, 6:4, 15:4, 25:4} (order 150) and d2 has cycle
      structure {2:4, 46:4} (order 46), confirming a non-trivial geometric
      twist.

  T4  The tomotope edge symmetry group P has order 96, generated by four
      involutions p0..p3 acting on 12 edge labels.  Its element order
      distribution is {1:1, 2:27, 3:32, 4:36}; all generators square to
      identity.  P acts on 2-subsets of {0..11} with orbit signature
      [48, 6, 6, 6] (three small orbits of size 6).

  T5  P has exactly four orbits of size 16 on 3-subsets of {0..11}.  Each
      gives a valid Reye (12, 16)-configuration: 16 lines on 12 points where
      every point lies on exactly 4 lines and any two lines share at most 1
      point.

  T6  Hard conjugacy obstruction: every index-2 subgroup of the axis-192
      stabilizer H (all three, of order 96 each) induces an edge-action group
      with 2-subset orbit signature [48, 12, 6], which differs from the
      tomotope P's signature [48, 6, 6, 6].  No relabeling can conjugate any
      axis-192 edge action to match the tomotope's published edge group P.
      This is the definitive structural proof that the axis-192 model is not
      the tomotope maniplex.
"""
from __future__ import annotations

import json
import zipfile
from collections import Counter
from itertools import combinations
from pathlib import Path

ROOT = Path(__file__).resolve().parent
TWIST_BUNDLE  = ROOT / "TOE_tomotope_twist_transport_v01_20260228_bundle.zip"
EDGE_BUNDLE   = ROOT / "TOE_tomotope_edge_action_compare_v01_20260228_bundle.zip"
CONJ_BUNDLE   = ROOT / "TOE_tomotope_flag_model_conjugacy_v01_20260228_bundle.zip"
EDGE_BASE     = "TOE_tomotope_edge_action_compare_v01_20260228"
CONJ_BASE     = "TOE_tomotope_flag_model_conjugacy_v01_20260228"


def compose(p: tuple, q: tuple) -> tuple:
    return tuple(p[q[i]] for i in range(len(q)))


def inv_perm(p: tuple) -> tuple:
    n = len(p)
    out = [0] * n
    for i, a in enumerate(p):
        out[a] = i
    return tuple(out)


def perm_order(p: tuple, max_ord: int = 500) -> int:
    n = len(p)
    idn = tuple(range(n))
    cur = tuple(p)
    k = 1
    while cur != idn:
        cur = compose(cur, p)
        k += 1
        if k > max_ord:
            return -1
    return k


def cycle_structure(p: tuple) -> dict:
    n = len(p)
    visited = [False] * n
    cycs: list[int] = []
    for i in range(n):
        if not visited[i]:
            c = 0
            j = i
            while not visited[j]:
                visited[j] = True
                c += 1
                j = p[j]
            cycs.append(c)
    return dict(sorted(Counter(cycs).items()))


def gen_group_bfs(gens: list[tuple], max_size: int = 500) -> set:
    n = len(gens[0])
    idn = tuple(range(n))
    group: set[tuple] = {idn}
    frontier = [idn]
    while frontier and len(group) <= max_size:
        nf = []
        for g in frontier:
            for gen in gens:
                h = compose(gen, g)
                if h not in group:
                    group.add(h)
                    nf.append(h)
        frontier = nf
    return group


def main() -> None:
    out: dict = {"status": "ok"}

    # ------------------------------------------------------------------ load
    with zipfile.ZipFile(TWIST_BUNDLE) as zf:
        pi       = tuple(json.loads(zf.read("pi_mapping.json")))
        trans    = json.loads(zf.read("transported_r_generators.json"))

    with zipfile.ZipFile(CONJ_BUNDLE) as zf:
        axis_adj = json.loads(
            zf.read(CONJ_BASE + "/flag_adjacency_r0_r3_permutations.json")
        )

    with zipfile.ZipFile(EDGE_BUNDLE) as zf:
        stats_data    = json.loads(zf.read(EDGE_BASE + "/axis192_index2_edge_action_stats.json"))
        p_gens_data   = json.loads(zf.read(EDGE_BASE + "/tomotope_p_generators.json"))
        reye_data     = json.loads(zf.read(EDGE_BASE + "/reye_line_orbits_from_P.json"))

    tr = {k: tuple(v) for k, v in trans.items()}
    ar = {k: tuple(v) for k, v in axis_adj.items()}

    # ==================================================================
    # T1: pi bijection — 50 fixed points, cycle structure, fixes r0 & r3
    # ==================================================================
    assert sorted(pi) == list(range(192)), "pi is not a permutation of {0..191}"
    pi_cyc = cycle_structure(pi)
    assert pi_cyc.get(1, 0) == 50, f"pi fixed points = {pi_cyc.get(1,0)}, expected 50"
    assert pi_cyc == {1: 50, 4: 1, 9: 2, 27: 2, 66: 1}, f"pi cycle structure = {pi_cyc}"
    assert tr["r0"] == ar["r0"], "transported r0 != axis r0"
    assert tr["r3"] == ar["r3"], "transported r3 != axis r3"
    assert tr["r1"] != ar["r1"], "transported r1 should differ from axis r1"
    assert tr["r2"] != ar["r2"], "transported r2 should differ from axis r2"

    out["T1_pi_fixed_points"]     = 50
    out["T1_pi_cycle_structure"]  = pi_cyc
    out["T1_pi_is_permutation"]   = True
    out["T1_r0_r3_fixed"]         = True
    out["T1_r1_r2_twisted"]       = True
    print("T1: pi has 50 fixed points, cycle struct {1:50,4:1,9:2,27:2,66:1}; r0,r3 fixed  OK")

    # ==================================================================
    # T2: Transported Coxeter relations (3, 12, 4, 2, 2, 2)
    # ==================================================================
    coxeter_pairs = {
        "r0r1": (0, 1, 3),
        "r1r2": (1, 2, 12),
        "r2r3": (2, 3, 4),
        "r0r2": (0, 2, 2),
        "r0r3": (0, 3, 2),
        "r1r3": (1, 3, 2),
    }
    coxeter_orders: dict = {}
    for label, (i, j, expected) in coxeter_pairs.items():
        prod = compose(tr[f"r{i}"], tr[f"r{j}"])
        ord_ = perm_order(prod)
        assert ord_ == expected, f"|{label}| = {ord_}, expected {expected}"
        coxeter_orders[label] = ord_

    # All generators are involutions
    for i in range(4):
        ri2 = compose(tr[f"r{i}"], tr[f"r{i}"])
        assert ri2 == tuple(range(192)), f"transported r{i}^2 != id"

    out["T2_coxeter_orders"]             = coxeter_orders
    out["T2_all_generators_involutions"] = True
    out["T2_tomotope_coxeter_holds"]     = True
    print("T2: Transported generators satisfy tomotope Coxeter diagram (3,12,4,2,2,2)  OK")

    # ==================================================================
    # T3: Twist elements d1, d2 — no fixed points, cycle structures
    # ==================================================================
    r1_t = tr["r1"]
    r1_a = ar["r1"]
    d1 = compose(r1_t, inv_perm(r1_a))
    d1_cyc  = cycle_structure(d1)
    d1_ord  = perm_order(d1)
    d1_fixed = d1_cyc.get(1, 0)
    assert d1_fixed == 0, f"d1 has {d1_fixed} fixed points, expected 0"
    assert d1_cyc == {2: 4, 6: 4, 15: 4, 25: 4}, f"d1 cycle structure = {d1_cyc}"
    assert d1_ord == 150, f"d1 order = {d1_ord}, expected 150"

    r2_t = tr["r2"]
    r2_a = ar["r2"]
    d2 = compose(r2_t, inv_perm(r2_a))
    d2_cyc  = cycle_structure(d2)
    d2_ord  = perm_order(d2)
    d2_fixed = d2_cyc.get(1, 0)
    assert d2_fixed == 0, f"d2 has {d2_fixed} fixed points, expected 0"
    assert d2_cyc == {2: 4, 46: 4}, f"d2 cycle structure = {d2_cyc}"
    assert d2_ord == 46, f"d2 order = {d2_ord}, expected 46"

    out["T3_d1_order"]           = d1_ord
    out["T3_d1_fixed_points"]    = 0
    out["T3_d1_cycle_structure"] = d1_cyc
    out["T3_d2_order"]           = d2_ord
    out["T3_d2_fixed_points"]    = 0
    out["T3_d2_cycle_structure"] = d2_cyc
    print(f"T3: Twist d1 order={d1_ord} cycles={{2:4,6:4,15:4,25:4}}; d2 order={d2_ord} cycles={{2:4,46:4}}  OK")

    # ==================================================================
    # T4: Tomotope edge group P — order 96, signature [48,6,6,6]
    # ==================================================================
    p_gens_0based: list[tuple] = []
    for k in ["p0", "p1", "p2", "p3"]:
        perm_1based = p_gens_data[k]["perm_1based"]
        p_gens_0based.append(tuple(x - 1 for x in perm_1based))

    P_group = gen_group_bfs(p_gens_0based, max_size=200)
    assert len(P_group) == 96, f"|P| = {len(P_group)}, expected 96"

    # All generators are involutions
    idn12 = tuple(range(12))
    for i, pg in enumerate(p_gens_0based):
        assert compose(pg, pg) == idn12, f"p{i} is not an involution"

    # Order distribution of P
    P_ord_dist = Counter(perm_order(g) for g in P_group)
    assert dict(P_ord_dist) == {1: 1, 2: 27, 3: 32, 4: 36}, (
        f"P order dist = {dict(P_ord_dist)}"
    )

    # 2-subset orbit signature
    two_subsets = list(combinations(range(12), 2))
    assert len(two_subsets) == 66

    def act_2sub(p: tuple, s: tuple) -> tuple:
        return tuple(sorted(p[x] for x in s))

    visited_2: set = set()
    orbit_2_sizes: list[int] = []
    for s in two_subsets:
        if s not in visited_2:
            orb: set = set()
            for g in P_group:
                orb.add(act_2sub(g, s))
            orbit_2_sizes.append(len(orb))
            visited_2.update(orb)

    sig = sorted(orbit_2_sizes, reverse=True)
    assert sig == [48, 6, 6, 6], f"P 2-subset signature = {sig}"

    out["T4_P_order"]                   = 96
    out["T4_P_order_distribution"]      = {str(k): v for k, v in sorted(P_ord_dist.items())}
    out["T4_P_generators_involutions"]  = True
    out["T4_P_2subset_signature"]       = sig
    out["T4_P_2subset_orbit_count"]     = len(orbit_2_sizes)
    print("T4: |P|=96, order dist {1:1,2:27,3:32,4:36}; 2-subset signature [48,6,6,6]  OK")

    # ==================================================================
    # T5: Four Reye (12,16) configurations from P orbits on 3-subsets
    # ==================================================================
    three_subsets = list(combinations(range(12), 3))
    assert len(three_subsets) == 220

    def act_3sub(p: tuple, s: tuple) -> frozenset:
        return frozenset(p[x] for x in s)

    visited_3: set = set()
    orbit_3_sizes: list[int] = []
    for s in three_subsets:
        sf = frozenset(s)
        if sf not in visited_3:
            orb3: set = set()
            for g in P_group:
                orb3.add(act_3sub(g, s))
            orbit_3_sizes.append(len(orb3))
            visited_3.update(orb3)

    size16_count = sum(1 for s in orbit_3_sizes if s == 16)
    assert size16_count == 4, f"size-16 orbits = {size16_count}, expected 4"

    # Verify each size-16 orbit is a valid Reye config
    reye_valid_count = 0
    for orb_info in reye_data["size16_orbits"]:
        lines = [tuple(sorted(x - 1 for x in ln)) for ln in orb_info["lines_1based"]]
        assert len(lines) == 16
        pt_count = Counter(pt for ln in lines for pt in ln)
        all_deg4 = all(v == 4 for v in pt_count.values())
        all_12pts = len(pt_count) == 12
        max_inter = max(
            len(set(lines[i]) & set(lines[j]))
            for i in range(16)
            for j in range(i + 1, 16)
        )
        if all_deg4 and all_12pts and max_inter <= 1:
            reye_valid_count += 1

    assert reye_valid_count == 4, f"valid Reye configs = {reye_valid_count}, expected 4"

    out["T5_3subset_orbit_sizes"]     = sorted(orbit_3_sizes, reverse=True)
    out["T5_size16_orbit_count"]      = 4
    out["T5_reye_configs_valid"]      = 4
    out["T5_reye_point_count"]        = 12
    out["T5_reye_line_count"]         = 16
    out["T5_reye_point_degree"]       = 4
    out["T5_reye_max_intersection"]   = 1
    print("T5: 4 orbits of size-16 on 3-subsets; all 4 give valid Reye (12,16) configs  OK")

    # ==================================================================
    # T6: Hard conjugacy obstruction — axis-192 signatures differ from P
    # ==================================================================
    tomo_sig = stats_data["tomotope_P_orbits_on_2subsets_sizes"]
    assert sorted(tomo_sig, reverse=True) == [48, 6, 6, 6]

    idx2_subs = stats_data["index2_subgroups"]
    assert len(idx2_subs) == 3, f"Expected 3 index-2 subgroups, got {len(idx2_subs)}"

    axis_signatures: list[list[int]] = []
    for sub in idx2_subs:
        sig_ax = sorted(sub["orbits_on_2subsets_sizes"], reverse=True)
        assert sig_ax == [48, 12, 6], (
            f"{sub['id']} signature = {sig_ax}, expected [48,12,6]"
        )
        axis_signatures.append(sig_ax)
        assert sig_ax != sorted(tomo_sig, reverse=True), (
            f"{sub['id']} accidentally matches tomotope signature!"
        )

    # All axis-192 subgroups have order 96 but different signature
    for sub in idx2_subs:
        assert sub["size"] == 96
        assert sub["induced_edge_action_group_order"] == 96

    out["T6_tomotope_P_signature"]         = sorted(tomo_sig, reverse=True)
    out["T6_axis_index2_count"]            = 3
    out["T6_all_axis_signatures"]          = [[48, 12, 6]] * 3
    out["T6_obstruction_confirmed"]        = True
    out["T6_tomotope_not_axis_model"]      = True
    print(
        "T6: All 3 axis-192 index-2 subgroups have signature [48,12,6] != [48,6,6,6]; "
        "hard obstruction confirmed  OK"
    )

    # Summary
    out["summary"] = {
        "pi_bijection": (
            "pi has 50 fixed points, cycle struct {1:50,4:1,9:2,27:2,66:1}; "
            "fixes r0,r3 exactly; twists r1,r2"
        ),
        "coxeter_diagram": (
            "transported r0..r3 satisfy tomotope Coxeter (3,12,4,2,2,2); all involutions"
        ),
        "twist_elements": (
            "d1 order=150 cycles {2:4,6:4,15:4,25:4}; d2 order=46 cycles {2:4,46:4}; "
            "both have 0 fixed points"
        ),
        "edge_group_P": (
            "|P|=96; order dist {1:1,2:27,3:32,4:36}; 2-subset signature [48,6,6,6]"
        ),
        "reye_configs": (
            "P has 4 orbits of size 16 on 3-subsets; each is a valid Reye (12,16) config"
        ),
        "hard_obstruction": (
            "all 3 axis-192 index-2 subgroups have 2-subset signature [48,12,6] "
            "!= [48,6,6,6]; tomotope != axis-192 model"
        ),
    }

    out_path = ROOT / "data" / "w33_twist_transport_reye.json"
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(out, indent=2), encoding="utf-8")
    print(f"Wrote {out_path}")
    print("All theorems verified OK")


if __name__ == "__main__":
    main()
