#!/usr/bin/env python3
"""Produce explicit words for tomotope flags from the 54-sheet basepoints.

Using the refined coordinate model, each of the 54 pockets has been
assigned a unique tomotope flag.  Here we compute a shortest word in the
four tomotope generators (r0,r1,r2,r3) that carries that base flag to
*every* flag in the 192-flag tomotope.  The output files are:

  * flag_word_map.json   -- mapping flag -> {"pocket":p, "word":list}
  * flag_word_table.csv  -- csv listing the same information

The word is recorded as a sequence of integers 0..3 corresponding to
(r0,r1,r2,r3).  A breadth-first search from the 54 base flags produces
the minimal-length words.

The mapping demonstrates that the tomotope is generated by the 54
basepoints, with explicit transport instructions.  This is the concrete
'coordinate proof' of the full 192-flag lift of the 54-sheet model.
"""

from __future__ import annotations

import json
import csv
from collections import deque
from pathlib import Path

ROOT = Path(__file__).resolve().parent
REFINED = ROOT / "K54_54sheet_coords_refined.csv"
GEN_FILE = ROOT / "axis_bundle_content" / "TOE_tomotope_axis_block_twist_v02_20260228" / "tomotope_r_generators_in_axis_coords.json"

OUT_MAP = ROOT / "flag_word_map.json"
OUT_CSV = ROOT / "flag_word_table.csv"

GENS = []

def load_generators():
    global GENS
    with open(GEN_FILE) as f:
        rgens = json.load(f)
    GENS = [tuple(rgens[k]) for k in ("r0","r1","r2","r3")]


def load_base_flags():
    flags = []
    with open(REFINED) as f:
        for r in csv.DictReader(f):
            if r.get("unique_flag") != "":
                flags.append((int(r["pocket"]), int(r["unique_flag"])))
    return flags


def compute_words(base):
    # BFS: each queue element is (flag, word, origin_pocket)
    visited = {}  # flag -> (pocket, word)
    q = deque()
    for p,f in base:
        visited[f] = (p, [])
        q.append((f, [], p))
    while q:
        f, w, p = q.popleft()
        for gi, g in enumerate(GENS):
            f2 = g[f]
            if f2 not in visited:
                visited[f2] = (p, w + [gi])
                q.append((f2, w + [gi], p))
    return visited


def write_outputs(mapping):
    # json
    open(OUT_MAP, "w").write(json.dumps(mapping, indent=2))
    # csv
    with open(OUT_CSV, "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["flag","pocket","word"])
        for flag,(p,word) in sorted(mapping.items()):
            w.writerow([flag,p," ".join(str(x) for x in word)])


def main():
    load_generators()
    base = load_base_flags()
    mapping = compute_words(base)
    write_outputs(mapping)
    print(f"wrote explicit flag-word map ({len(mapping)} flags)")

if __name__ == '__main__':
    main()
