#!/usr/bin/env python3
"""Find a one-to-one assignment of 54 pockets to distinct tomotope flags.

Uses the candidate lists generated by the 54-sheet model; solves a
bipartite matching problem by augmenting paths.  Outputs:

  * pocket_to_unique_flag.json -- mapping pocket->chosen flag
  * K54_54sheet_coords_refined.csv -- updated coords file with the unique flag
  * SUMMARY_matching.json -- simple diagnostics (matched/failed counts)

If a perfect matching cannot be found a warning will be printed and the
best partial matching left in the JSON.

This script should be run after generating the initial 54sheet coords and
pocket_to_flags.json.
"""

from __future__ import annotations

import json
import csv
from collections import deque
from pathlib import Path

ROOT = Path(__file__).resolve().parent
CAND_FILE = ROOT / "pocket_to_flags.json"
COORD_FILE = ROOT / "K54_54sheet_coords.csv"
OUT_JSON = ROOT / "pocket_to_unique_flag.json"
OUT_CSV = ROOT / "K54_54sheet_coords_refined.csv"
OUT_SUM = ROOT / "SUMMARY_matching.json"


def load_candidates():
    return {int(k): v for k,v in json.load(open(CAND_FILE)).items()}


def bipartite_matching(cands):
    # simple DFS-based augmenting path algorithm
    # pockets -> flags
    match_flag = {}  # flag -> pocket
    match_pocket = {}  # pocket -> flag

    def find_augment(pocket, visited):
        for flag in cands.get(pocket, []):
            if flag in visited: continue
            visited.add(flag)
            if flag not in match_flag or find_augment(match_flag[flag], visited):
                match_flag[flag] = pocket
                match_pocket[pocket] = flag
                return True
        return False

    # greedy initial pass
    for p, flags in cands.items():
        for f in flags:
            if f not in match_flag:
                match_flag[f] = p
                match_pocket[p] = f
                break
    # augment until no improvement
    improved = True
    while improved:
        improved = False
        for p in cands:
            if p in match_pocket: continue
            if find_augment(p, set()):
                improved = True
    return match_pocket, match_flag


def write_outputs(match, summary):
    # save JSON
    open(OUT_JSON, "w").write(json.dumps(match, indent=2))
    # update coords CSV
    rows = []
    with open(COORD_FILE) as f:
        reader = csv.DictReader(f)
        fieldnames = reader.fieldnames + ["unique_flag"]
        for r in reader:
            p = int(r["pocket"])
            r["unique_flag"] = match.get(p)
            rows.append(r)
    with open(OUT_CSV, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)
    # write summary
    open(OUT_SUM, "w").write(json.dumps(summary, indent=2))


def main():
    cands = load_candidates()
    # ensure all 54 pockets are present; missing ones may be given full flag set
    all_pockets = set(range(54))
    max_flag = 192
    for p in all_pockets:
        if p not in cands:
            # allow any flag; matching will choose unused ones
            cands[p] = list(range(max_flag))
    match_p, match_f = bipartite_matching(cands)
    matched = len(match_p)
    summary = {
        "total_pockets": len(cands),
        "matched": matched,
        "unmatched_pockets": [p for p in cands if p not in match_p]
    }
    write_outputs(match_p, summary)
    print(f"matched {matched} of {len(cands)} pockets")
    if matched < len(cands):
        print("WARNING: perfect matching not achieved")

if __name__=='__main__':
    main()
