#!/usr/bin/env python3
"""Utility analysis for the 54-sheet coordinate model (next moves).

This script performs the three next-move tasks:

1. Load `K54_54sheet_coords.csv` and compute summary statistics (qid/twin/L
   distribution, block coverage, flag usage).  The output is written to
   `54sheet_coord_stats.json` and a human-readable report `54sheet_coord_report.md`.

2. Inspect the existing `SUMMARY_54sheet.json` for cycle-phase correlations and
   guess-refinement details.  A textual interpretation of those figures is also
   appended to the report.

3. Prepare a narrative bundle directory to be consumed by the next pillar.
   This means copying the CSV/JSON outputs into a folder `next_pillar_bundle`
   and zipping it as `TOE_54sheet_pillar82_bundle.zip`.

The script can be re-run whenever data change or when building the next
bundle.  It does not modify the core coordinate files.
"""

from __future__ import annotations

import csv
import json
import zipfile
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent
COORD_CSV = ROOT / "K54_54sheet_coords.csv"
SUMMARY_JSON = ROOT / "SUMMARY_54sheet.json"

STAT_JSON = ROOT / "54sheet_coord_stats.json"
REPORT_MD = ROOT / "54sheet_coord_report.md"
BUNDLE_DIR = ROOT / "next_pillar_bundle"
BUNDLE_ZIP = ROOT / "TOE_54sheet_pillar82_bundle.zip"


def load_coords(refined=False):
    path = ROOT / ("K54_54sheet_coords_refined.csv" if refined else "K54_54sheet_coords.csv")
    rows = []
    with open(path) as f:
        for r in csv.DictReader(f):
            for k in ("pocket","qid","twin_bit","L","canonical_flag","canonical_block"):
                if r.get(k) != "":
                    r[k] = int(r[k])
                else:
                    r[k] = None
            if refined and r.get("unique_flag") != "":
                r["unique_flag"] = int(r["unique_flag"])
            rows.append(r)
    return rows


def analyze_coords(rows):
    stats = {}
    stats["total_pockets"] = len(rows)
    stats["qid_distribution"] = Counter(r["qid"] for r in rows)
    stats["twin_distribution"] = Counter(r["twin_bit"] for r in rows)
    stats["L_distribution"] = Counter(r["L"] for r in rows)
    stats["block_coverage"] = Counter(r["canonical_block"] for r in rows if r["canonical_block"] is not None)
    stats["flag_coverage"] = Counter(r["canonical_flag"] for r in rows if r["canonical_flag"] is not None)
    return stats


def load_summary():
    return json.loads(open(SUMMARY_JSON).read())


def report_stats(stats, summary):
    with open(REPORT_MD, "w", encoding="utf-8") as f:
        f.write("# 54‑Sheet Coordinate Analysis Report\n\n")
        f.write("## Basic counts\n")
        f.write(f"Total pockets: {stats['total_pockets']}\n")
        f.write("\n## Distributions\n")
        f.write(f"qid distribution: {dict(stats['qid_distribution'])}\n")
        f.write(f"twin distribution: {dict(stats['twin_distribution'])}\n")
        f.write(f"L distribution: {dict(stats['L_distribution'])}\n")
        f.write("\n## Coverage\n")
        f.write(f"blocks seen (count): {dict(stats['block_coverage'])}\n")
        f.write(f"flags seen (count): {len(stats['flag_coverage'])} unique, {sum(stats['flag_coverage'].values())} total\n")

        f.write("\n## Guess refinement\n")
        guesses = summary.get("guess_to_actual_flag_counts", {})
        f.write(f"This summary object contains {len(guesses)} guessed blocks that were actual.\n")
        for g,v in guesses.items():
            f.write(f"  guess {g}: used {v['count']} times, flags {v['flags']}\n")

        f.write("\n## t^4 cycle vs L\n")
        cycles = summary.get("canonical_flag_t4_cycle_vs_L", {})
        for k,v in cycles.items():
            f.write(f"  {k} -> {v} pockets\n")
        f.write("\nNote: (1,*) are fixed points; (3,*) are 3-cycles under t^4.\n")

        f.write("\nReport generated by THEORY_PART_COCYCLE_HEISENBERG_TOMOTOPE_54SHEET_ANALYSIS.py\n")


def make_bundle():
    # create directory, copy relevant files
    BUNDLE_DIR.mkdir(exist_ok=True)
    for fn in (COORD_CSV, SUMMARY_JSON, STAT_JSON, REPORT_MD):
        dest = BUNDLE_DIR / fn.name
        dest.write_bytes(fn.read_bytes())
    # zip
    with zipfile.ZipFile(BUNDLE_ZIP, "w") as zf:
        for path in sorted(BUNDLE_DIR.iterdir()):
            zf.write(str(path), path.name)
        # also include refined files if present
        for extra in (ROOT / "K54_54sheet_coords_refined.csv", ROOT / "pocket_to_unique_flag.json", ROOT / "PILLAR_82.md"):
            if extra.exists():
                zf.write(str(extra), extra.name)
    print(f"Created next pillar bundle: {BUNDLE_ZIP}")


def main():
    # analyse original coords
    coords = load_coords(refined=False)
    stats = analyze_coords(coords)
    summary = load_summary()
    # write stats JSON
    open(STAT_JSON, "w").write(json.dumps(stats, indent=2))
    report_stats(stats, summary)
    # perform additional tomotope computations if summary contains t4 info
    try:
        # compute full orbit under tomotope generators for unique flags
        zf = zipfile.ZipFile(ROOT / "TOE_tomotope_true_flag_model_v02_20260228_bundle.zip")
        rgens = json.loads(zf.read("tomotope_r_generators_192.json"))
        r0 = tuple(rgens["r0"]); r1 = tuple(rgens["r1"])
        r2 = tuple(rgens["r2"]); r3 = tuple(rgens["r3"])
        # build list of unique flags from refined coords if available else canonical
        unique_flags = []
        refined_path = ROOT / "K54_54sheet_coords_refined.csv"
        csvpath = refined_path if refined_path.exists() else COORD_CSV
        with open(csvpath) as f2:
            for row in csv.DictReader(f2):
                uf = row.get("unique_flag") or row.get("canonical_flag")
                if uf and uf != "":
                    unique_flags.append(int(uf))
        gens = [r0,r1,r2,r3]
        orb = set(unique_flags)
        queue = list(unique_flags)
        while queue:
            fflag = queue.pop()
            for g in gens:
                new = g[fflag]
                if new not in orb:
                    orb.add(new); queue.append(new)
        diagnostics = summary
        diagnostics["full_orbit_size"] = len(orb)
        diagnostics["full_orbit_all_flags"] = (len(orb) == 192)
        # record mapping of flag->representative pocket
        mapping = {}
        with open(csvpath) as f3:
            for row in csv.DictReader(f3):
                p = int(row["pocket"])
                uf = int(row.get("unique_flag") or row.get("canonical_flag"))
                mapping[uf] = p
        # propagate mapping along orbit (simple BFS)
        queue = list(mapping.keys())
        while queue:
            fflag = queue.pop()
            for g in gens:
                new = g[fflag]
                if new not in mapping:
                    mapping[new] = mapping[fflag]
                    queue.append(new)
        diagnostics["flag_to_pocket_orbit"] = mapping
        # rewrite summary file with new diagnostics
        open(SUMMARY_JSON, "w").write(json.dumps(diagnostics, indent=2))
    except Exception:
        pass
    # now also compute refined stats if available
    refined_path = ROOT / "K54_54sheet_coords_refined.csv"
    if refined_path.exists():
        rcoords = load_coords(refined=True)
        rstats = analyze_coords(rcoords)
        with open(ROOT / "54sheet_coord_stats_refined.json", "w") as f:
            json.dump(rstats, f, indent=2)
        # append to report
        with open(REPORT_MD, "a", encoding="utf-8") as f:
            f.write("\n\n## Refined unique-flag statistics\n")
            f.write(f"blocks seen refined: {dict(rstats['block_coverage'])}\n")
            f.write(f"flags seen refined: {len(rstats['flag_coverage'])} unique\n")
    make_bundle()

if __name__ == '__main__':
    main()
