"""
PILLAR 150 (CCL): CLUSTER ALGEBRAS & COMBINATORIAL DYNAMICS
============================================================

From W(3,3) through E8 to cluster algebras, the Laurent phenomenon,
finite type classification, and deep connections to scattering amplitudes.

BREAKTHROUGH: Cluster algebras (Fomin-Zelevinsky, 2002) provide a
combinatorial-algebraic framework that has unified diverse areas:

- Total positivity & canonical bases (Lusztig)
- Teichmuller theory & hyperbolic geometry
- Scattering amplitudes (positive Grassmannian, amplituhedron)
- Integrable systems & Y-systems
- Representation theory of quivers & tilting theory
- Poisson geometry & symplectic structures

MIRACLE: Cluster algebras of FINITE TYPE are classified by
Dynkin diagrams - the SAME classification as simple Lie algebras!
So W(3,3) -> E8 -> finite type cluster algebra of type E8.

Key dates:
- 2002: Fomin-Zelevinsky introduce cluster algebras (Paper I)
- 2003: Finite type classification = Dynkin diagrams (Paper II)
- 2012: Gross-Hacking-Keel-Kontsevich prove positivity conjecture
- 2013: Amplituhedron connects to positive Grassmannian / clusters
"""

import math
from itertools import combinations


# -- 1. Cluster Algebra Foundations ----------------------------------------

def cluster_algebra_foundations():
    """
    Cluster algebras: commutative rings with distinguished generators
    (cluster variables) grouped into overlapping sets (clusters)
    related by mutation.
    """
    results = {
        'name': 'Cluster Algebra Foundations',
        'introduced_by': ['Sergey Fomin', 'Andrei Zelevinsky'],
        'year': 2002,
        'paper': 'Cluster algebras I: Foundations (JAMS 2002)',
    }

    results['definition'] = {
        'ambient_field': 'F = Q(x_1, ..., x_n) rational function field',
        'seed': '(x, B) where x = {x_1,...,x_n} cluster, B = exchange matrix',
        'exchange_matrix': 'B = (b_ij) skew-symmetrizable integer matrix',
        'mutation': 'mu_k replaces x_k by x_k_prime via exchange relation',
        'exchange_relation': "x_k * x_k' = prod_{b_ik>0} x_i^{b_ik} + prod_{b_ik<0} x_i^{-b_ik}",
        'cluster_algebra': 'Z-algebra generated by ALL cluster variables from ALL seeds',
    }

    results['key_properties'] = {
        'laurent_phenomenon': 'Every cluster variable is a Laurent polynomial in initial cluster',
        'positivity': 'Laurent polynomial has NON-NEGATIVE integer coefficients (proved 2012)',
        'finite_clusters': 'Some have finitely many clusters (finite type)',
        'mutation_involution': 'mu_k^2 = identity (mutation is an involution)',
    }

    return results


# -- 2. Laurent Phenomenon ------------------------------------------------

def laurent_phenomenon():
    """
    The Laurent phenomenon: cluster variables are always
    Laurent polynomials in the initial variables.
    This is surprising because exchange relations involve division!
    """
    results = {
        'name': 'Laurent Phenomenon',
        'theorem': 'Fomin-Zelevinsky (2002)',
    }

    results['statement'] = {
        'precise': 'Every cluster variable is a Laurent polynomial in x_1,...,x_n with integer coefficients',
        'surprising': 'Exchange relations involve DIVISION, yet results are always Laurent polynomials',
        'positivity': 'Coefficients are non-negative integers (proved by GHKK 2012)',
    }

    # Rank 2 example: A2 type
    # x1, x2 -> x3 = (1+x2)/x1 -> x4 = (1+x1+x2)/(x1*x2) -> x5 = (1+x1)/x2 -> x1
    results['a2_example'] = {
        'initial': ['x1', 'x2'],
        'x3': '(1 + x2) / x1',
        'x4': '(1 + x1 + x2) / (x1 * x2)',
        'x5': '(1 + x1) / x2',
        'period': 5,
        'all_laurent': True,
        'verification': 'x6 = x1, x7 = x2 (period 5)',
    }

    # Compute period for type A2
    results['a2_period'] = 5
    results['b2_period'] = 6
    results['g2_period'] = 8

    return results


# -- 3. Finite Type Classification ----------------------------------------

def finite_type_classification():
    """
    Fomin-Zelevinsky (2003): Cluster algebras of finite type are
    classified by Dynkin diagrams!

    This is the SAME classification as:
    - Simple Lie algebras
    - Finite Coxeter groups
    - Singularity theory (ADE)
    """
    results = {
        'name': 'Finite Type Classification',
        'theorem': 'Fomin-Zelevinsky (2003)',
        'paper': 'Cluster algebras II: Finite type classification (Inventiones 2003)',
    }

    results['classification'] = {
        'statement': 'Cluster algebra has finitely many clusters iff exchange matrix is of Dynkin type',
        'dynkin_types': ['A_n', 'B_n', 'C_n', 'D_n', 'E_6', 'E_7', 'E_8', 'F_4', 'G_2'],
        'same_as': 'Classification of simple Lie algebras!',
    }

    # Number of cluster variables = number of positive roots + n
    # Actually: number of cluster variables = positive roots + rank
    results['cluster_counts'] = {
        'A_n': {
            'cluster_variables': 'n(n+1)/2 + n = n(n+3)/2',
            'clusters': 'Catalan number C(n+1)',
            'formula_clusters': lambda n: math.comb(2*n+2, n+1) // (n+2),
        },
        'E_6': {
            'positive_roots': 36,
            'cluster_variables': 36 + 6,  # = 42
            'rank': 6,
        },
        'E_7': {
            'positive_roots': 63,
            'cluster_variables': 63 + 7,  # = 70
            'rank': 7,
        },
        'E_8': {
            'positive_roots': 120,
            'cluster_variables': 120 + 8,  # = 128
            'rank': 8,
        },
    }

    # Catalan numbers for A_n
    results['catalan_numbers'] = {
        'C_2': 2,   # A1
        'C_3': 5,   # A2
        'C_4': 14,  # A3
        'C_5': 42,  # A4
        'formula': 'C(n) = (2n)! / ((n+1)! * n!)',
    }

    return results


# -- 4. Quiver Mutations ---------------------------------------------------

def quiver_mutations():
    """
    Quiver mutations: the visual/combinatorial language of cluster algebras.
    Exchange matrix B ↔ quiver (directed graph without loops or 2-cycles).
    """
    results = {
        'name': 'Quiver Mutations',
    }

    results['definition'] = {
        'quiver': 'Directed graph Q without loops or 2-cycles',
        'from_matrix': 'Draw b_ij arrows from i to j when b_ij > 0',
        'mutation_steps': [
            '1. For each path i -> k -> j, add arrow i -> j',
            '2. Reverse all arrows incident to vertex k',
            '3. Remove any 2-cycles created',
        ],
    }

    # A2 quiver mutation example
    results['a2_example'] = {
        'initial_quiver': '1 -> 2',
        'after_mu_1': '1 <- 2 (reversed)',
        'after_mu_2': '1 -> 2 (back to original)',
        'finite_type': True,
    }

    # Dynkin quiver types
    results['dynkin_quivers'] = {
        'A_n': 'Path quiver: 1 -> 2 -> ... -> n',
        'D_n': 'Fork at vertex n-1: path with branch',
        'E_6': '6 vertices, T-shaped (like E6 Dynkin)',
        'E_7': '7 vertices',
        'E_8': '8 vertices',
    }

    # Connection to representation theory
    results['representation_theory'] = {
        'gabriel_theorem': 'Quiver has finitely many indecomposable reps iff Dynkin type',
        'year': 1972,
        'author': 'Peter Gabriel',
        'cluster_connection': 'Cluster-tilted algebras from cluster mutations',
    }

    return results


# -- 5. Cluster Algebras and Grassmannians ---------------------------------

def cluster_grassmannian():
    """
    The coordinate ring of the Grassmannian Gr(k,n) has a natural
    cluster algebra structure. Plucker coordinates provide cluster variables.
    """
    results = {
        'name': 'Cluster Algebras and Grassmannians',
    }

    results['grassmannian'] = {
        'definition': 'Gr(k,n) = space of k-planes in n-space',
        'plucker': 'Plucker coordinates p_{i1,...,ik} as cluster variables',
        'cluster_structure': 'Scott (2006): Gr(k,n) has cluster algebra structure',
    }

    # Gr(2,n) example
    results['gr_2_n'] = {
        'cluster_variables': 'Diagonals of n-gon',
        'clusters': 'Triangulations of n-gon',
        'mutation': 'Diagonal flip in triangulation',
        'frozen': 'Boundary edges (coefficient variables)',
        'count': lambda n: n * (n - 3) // 2,  # number of diagonals
    }

    # Amplituhedron connection
    results['amplituhedron'] = {
        'positive_grassmannian': 'Gr_+(k,n) = Grassmannian with all Plucker coords positive',
        'arkani_hamed_trnka': 'Amplituhedron = image of Gr_+(k,n) under positive map',
        'scattering': 'Tree-level amplitudes in N=4 SYM from positive geometry',
        'cluster_fan': 'Cluster fan of Gr(k,n) encodes amplitude singularities',
    }

    return results


# -- 6. Y-systems and Integrable Systems ----------------------------------

def y_systems():
    """
    Y-systems arise from cluster algebras and connect to
    thermodynamic Bethe ansatz in integrable systems.
    """
    results = {
        'name': 'Y-Systems and Integrability',
    }

    results['y_system'] = {
        'definition': 'Y_i(t+1) * Y_i(t-1) = prod_j (1 + Y_j(t))^{-a_ij}',
        'origin': 'Zamolodchikov (1991): thermodynamic Bethe ansatz',
        'periodicity': 'Fomin-Zelevinsky: Y-systems of Dynkin type have periodicity',
    }

    results['periodicities'] = {
        'A_n': {'period': 'n + 3', 'formula': lambda n: n + 3},
        'D_n': {'period': '2(n-1)', 'formula': lambda n: 2*(n-1)},
        'E_6': {'period': 12},
        'E_7': {'period': 18},
        'E_8': {'period': 30},
    }

    results['zamolodchikov'] = {
        'year': 1991,
        'conjecture': 'Y-system periodicity for all ADE types',
        'proved_by': 'Fomin-Zelevinsky using cluster algebras',
        'connection': 'Cluster mutations realize Y-system dynamics',
    }

    return results


# -- 7. Total Positivity ---------------------------------------------------

def total_positivity():
    """
    Total positivity: matrices with all minors positive.
    Cluster algebras were originally motivated by Lusztig's
    work on canonical bases and total positivity.
    """
    results = {
        'name': 'Total Positivity',
    }

    results['definition'] = {
        'totally_positive': 'Matrix M where ALL minors are positive',
        'totally_nonneg': 'Matrix M where all minors are non-negative',
        'classical': 'Schoenberg, Gantmacher-Krein (1930s-1950s)',
    }

    results['lusztig'] = {
        'author': 'George Lusztig',
        'year': 1994,
        'contribution': 'Total positivity in reductive groups',
        'canonical_bases': 'Connection to canonical/crystal bases',
        'positivity': 'Structure constants of canonical basis are non-negative',
        'motivation': 'Original motivation for Fomin-Zelevinsky cluster algebras',
    }

    results['applications'] = {
        'oscillatory_matrices': 'Eigenvalues are real and distinct',
        'variation_diminishing': 'Preserves sign changes in vectors',
        'electrical_networks': 'Response matrices of planar networks',
        'amplitudes': 'Positive Grassmannian in N=4 SYM',
    }

    return results


# -- 8. Cluster Categories and Tilting Theory ------------------------------

def cluster_categories():
    """
    Cluster categories: the representation-theoretic framework
    that categorifies cluster algebras.
    """
    results = {
        'name': 'Cluster Categories',
    }

    results['definition'] = {
        'introduced_by': 'Buan-Marsh-Reineke-Reiten-Todorov (2006)',
        'acronym': 'BMRRT',
        'construction': 'C_Q = D^b(mod Q) / tau^{-1}[1] (orbit category)',
        'categorification': 'Cluster variables <-> indecomposable objects in C_Q',
    }

    results['properties'] = {
        'triangulated': 'C_Q is a triangulated category (Keller)',
        'calabi_yau': 'C_Q is 2-Calabi-Yau (CY dimension 2)',
        'mesh': 'Almost split sequences become triangles',
        'cluster_tilting': 'Clusters <-> cluster-tilting objects',
    }

    results['caldero_chapoton'] = {
        'year': 2006,
        'map': 'X_M (cluster character) takes objects to Laurent polynomials',
        'formula': 'X_M = sum_{e} chi(Gr_e(M)) * x^{...}',
        'proves': 'Laurent phenomenon from representation theory',
    }

    return results


# -- 9. Cluster Algebras and Surfaces -------------------------------------

def cluster_surfaces():
    """
    Fomin-Shapiro-Thurston (2008): Cluster algebras from bordered
    surfaces with marked points.
    """
    results = {
        'name': 'Cluster Algebras from Surfaces',
        'authors': ['Fomin', 'Shapiro', 'Thurston'],
        'year': 2008,
    }

    results['construction'] = {
        'input': '(S, M) = bordered surface with marked points',
        'arcs': 'Arcs connecting marked points (up to isotopy)',
        'triangulation': 'Maximal collection of non-crossing arcs',
        'flip': 'Replace one arc in triangulation by unique alternative',
        'correspondence': {
            'cluster_variables': '<-> arcs',
            'clusters': '<-> triangulations',
            'mutations': '<-> flips',
        },
    }

    results['examples'] = {
        'disk_n_marked': 'Gr(2,n) cluster algebra, type A_{n-3}',
        'annulus': 'Type D cluster algebras',
        'once_punctured_torus': 'Type affine D_4',
        'disk_2_punctures': 'Type affine D cluster algebras',
    }

    results['teichmuller'] = {
        'connection': 'Cluster coordinates = Fock-Goncharov coordinates on Teichmuller space',
        'year': 2006,
        'authors': ['Fock', 'Goncharov'],
        'laminations': 'Tropical points = measured laminations',
    }

    return results


# -- 10. Positivity Conjecture (GHKK 2012) --------------------------------

def positivity_conjecture():
    """
    The positivity conjecture: Laurent polynomial coefficients are non-negative.
    Proved by Gross-Hacking-Keel-Kontsevich (2012/2018).
    """
    results = {
        'name': 'Positivity Conjecture',
    }

    results['conjecture'] = {
        'statement': 'All Laurent polynomial coefficients of cluster variables are non-negative integers',
        'conjectured_by': 'Fomin-Zelevinsky (2002)',
        'significance': 'Suggests deep combinatorial / geometric meaning',
    }

    results['proof'] = {
        'proved_by': ['Mark Gross', 'Paul Hacking', 'Sean Keel', 'Maxim Kontsevich'],
        'acronym': 'GHKK',
        'year': 2018,  # publication year
        'method': 'Scattering diagrams and theta functions',
        'tropical': 'Tropical geometry plays key role',
    }

    results['scattering_diagrams'] = {
        'definition': 'Collection of walls in tropical space with attached functions',
        'origin': 'Kontsevich-Soibelman wall-crossing',
        'application': 'Construct canonical basis = theta basis',
        'theta_functions': 'Canonical basis elements with positivity built in',
    }

    return results


# -- 11. E8 Cluster Algebra -----------------------------------------------

def e8_cluster_algebra():
    """
    The cluster algebra of type E8: properties and W(3,3) connection.
    """
    results = {
        'name': 'E8 Cluster Algebra',
    }

    results['properties'] = {
        'rank': 8,
        'positive_roots': 120,
        'cluster_variables': 128,  # 120 + 8
        'type': 'Finite (Dynkin E8)',
        'from_quiver': 'E8 Dynkin quiver (any orientation)',
    }

    # Number of clusters for E_8 (this is the generalized Catalan number)
    # For E8: product_{i=1}^{8} (e_i + h + 1) / (e_i + 1)
    # where e_i are exponents and h is Coxeter number
    # E8 exponents: 1, 7, 11, 13, 17, 19, 23, 29; h = 30
    results['e8_clusters'] = {
        'exponents': [1, 7, 11, 13, 17, 19, 23, 29],
        'coxeter_number': 30,
        'num_clusters': 25080,  # generalized Catalan for E8
    }

    results['y_system'] = {
        'type': 'E8',
        'period': 30,
        'zamolodchikov': 'E8 Y-system periodicity = Coxeter number h = 30',
    }

    results['w33_chain'] = {
        'path': [
            'W(3,3) -> E8 root system',
            'E8 Dynkin diagram -> exchange matrix B',
            'B -> cluster algebra of type E8',
            '128 cluster variables, 25080 clusters',
            'Y-system with period 30 (= Coxeter number)',
        ],
        'significance': 'The COMBINATORICS of W(3,3) determine the CLUSTER STRUCTURE',
    }

    return results


# -- 12. Complete Chain ---------------------------------------------------

def complete_chain():
    """
    The complete chain from W(3,3) through cluster algebras.
    """
    chain = {
        'name': 'W(3,3) to Cluster Algebras',
    }

    chain['links'] = [
        {
            'step': 1,
            'from': 'W(3,3)',
            'to': 'E8 Dynkin diagram',
            'via': 'Root system / Cartan matrix',
        },
        {
            'step': 2,
            'from': 'E8 Dynkin diagram',
            'to': 'Exchange matrix B',
            'via': 'Orient edges to get quiver',
        },
        {
            'step': 3,
            'from': 'Exchange matrix B',
            'to': 'Cluster algebra of finite type E8',
            'via': 'Fomin-Zelevinsky mutation process',
        },
        {
            'step': 4,
            'from': 'Cluster mutations',
            'to': 'Laurent phenomenon + positivity',
            'via': 'GHKK proof using scattering diagrams',
        },
        {
            'step': 5,
            'from': 'Cluster algebra',
            'to': 'Scattering amplitudes',
            'via': 'Positive Grassmannian, amplituhedron',
        },
        {
            'step': 6,
            'from': 'Y-system of type E8',
            'to': 'Integrable systems',
            'via': 'Zamolodchikov thermodynamic Bethe ansatz',
        },
    ]

    chain['miracle'] = {
        'statement': 'COMBINATORIAL DYNAMICS FROM DYNKIN CLASSIFICATION',
        'details': [
            'W(3,3) -> E8 -> cluster algebra with 128 variables, 25080 clusters',
            'Laurent phenomenon: division always yields Laurent polynomials',
            'Positivity: Laurent coefficients are non-negative (proved 2012)',
            'Same Dynkin classification as Lie algebras, singularities, etc.',
            'Connects total positivity, representation theory, integrable systems',
            'Cluster coordinates appear in scattering amplitudes!',
        ],
    }

    return chain


# -- Run All Checks -------------------------------------------------------

def run_all_checks():
    """Execute all 15 verification checks."""
    checks = []
    passed = 0

    # Check 1: Foundations
    ca = cluster_algebra_foundations()
    ok = ca['year'] == 2002 and 'Fomin' in ca['introduced_by'][0]
    checks.append(('Cluster algebras (FZ 2002)', ok))
    passed += ok

    # Check 2: Laurent phenomenon
    lp = laurent_phenomenon()
    ok2 = lp['a2_period'] == 5
    ok2 = ok2 and lp['a2_example']['all_laurent'] == True
    checks.append(('Laurent phenomenon A2 period 5', ok2))
    passed += ok2

    # Check 3: Finite type = Dynkin
    ft = finite_type_classification()
    ok3 = 'E_8' in ft['classification']['dynkin_types']
    ok3 = ok3 and ft['classification']['same_as'] == 'Classification of simple Lie algebras!'
    checks.append(('Finite type = Dynkin diagrams', ok3))
    passed += ok3

    # Check 4: Catalan numbers
    ok4 = ft['catalan_numbers']['C_3'] == 5  # A2
    ok4 = ok4 and ft['catalan_numbers']['C_4'] == 14  # A3
    checks.append(('Catalan numbers for type A', ok4))
    passed += ok4

    # Check 5: E8 cluster variables
    ok5 = ft['cluster_counts']['E_8']['cluster_variables'] == 128
    ok5 = ok5 and ft['cluster_counts']['E_8']['positive_roots'] == 120
    checks.append(('E8: 128 cluster vars (120+8)', ok5))
    passed += ok5

    # Check 6: Quiver mutations
    qm = quiver_mutations()
    ok6 = qm['representation_theory']['year'] == 1972  # Gabriel
    ok6 = ok6 and 'Gabriel' in qm['representation_theory']['author']
    checks.append(('Gabriel theorem 1972', ok6))
    passed += ok6

    # Check 7: Grassmannian
    cg = cluster_grassmannian()
    ok7 = 'Plucker' in cg['grassmannian']['plucker']
    ok7 = ok7 and 'amplituhedron' in cg['amplituhedron']['arkani_hamed_trnka'].lower()
    checks.append(('Grassmannian cluster structure', ok7))
    passed += ok7

    # Check 8: Y-systems
    ys = y_systems()
    ok8 = ys['periodicities']['E_8']['period'] == 30
    ok8 = ok8 and ys['zamolodchikov']['year'] == 1991
    checks.append(('E8 Y-system period 30', ok8))
    passed += ok8

    # Check 9: Total positivity
    tp = total_positivity()
    ok9 = tp['lusztig']['year'] == 1994
    ok9 = ok9 and 'canonical' in tp['lusztig']['canonical_bases'].lower()
    checks.append(('Total positivity (Lusztig 1994)', ok9))
    passed += ok9

    # Check 10: Cluster categories
    cc = cluster_categories()
    ok10 = 'BMRRT' in cc['definition']['acronym']
    ok10 = ok10 and cc['properties']['calabi_yau'] is not None
    checks.append(('Cluster categories (BMRRT)', ok10))
    passed += ok10

    # Check 11: Surfaces
    cs = cluster_surfaces()
    ok11 = cs['year'] == 2008
    ok11 = ok11 and 'Thurston' in cs['authors']
    checks.append(('Cluster algebras from surfaces', ok11))
    passed += ok11

    # Check 12: Positivity proof
    pc = positivity_conjecture()
    ok12 = any('Kontsevich' in a for a in pc['proof']['proved_by'])
    ok12 = ok12 and pc['proof']['year'] == 2018
    checks.append(('Positivity proved (GHKK)', ok12))
    passed += ok12

    # Check 13: E8 cluster algebra
    e8 = e8_cluster_algebra()
    ok13 = e8['properties']['cluster_variables'] == 128
    ok13 = ok13 and e8['e8_clusters']['coxeter_number'] == 30
    checks.append(('E8 cluster: 128 vars, h=30', ok13))
    passed += ok13

    # Check 14: E8 clusters count
    ok14 = e8['e8_clusters']['num_clusters'] == 25080
    checks.append(('E8 has 25080 clusters', ok14))
    passed += ok14

    # Check 15: Complete chain
    ch = complete_chain()
    ok15 = len(ch['links']) == 6
    ok15 = ok15 and 'DYNKIN' in ch['miracle']['statement']
    checks.append(('Complete chain W33->clusters', ok15))
    passed += ok15

    # Report
    print("=" * 70)
    print("PILLAR 150: CLUSTER ALGEBRAS & COMBINATORIAL DYNAMICS")
    print("=" * 70)
    for name, ok in checks:
        status = "PASS" if ok else "FAIL"
        print(f"  [{status}] {name}")
    print(f"\n  Result: {passed}/15 checks passed")

    if passed == 15:
        print("\n  ** ALL 15 CHECKS PASSED **")
        print("\n  CLUSTER ALGEBRA REVELATION:")
        print("  W(3,3) -> E8 -> finite type cluster algebra")
        print("  128 cluster variables, 25080 clusters, Y-period 30")
        print("  Laurent phenomenon: division always gives Laurent polynomials!")
        print("  Positivity: all coefficients non-negative (proved by GHKK)")
        print("  Same Dynkin classification as Lie algebras!")
        print("  COMBINATORIAL DYNAMICS FROM DYNKIN CLASSIFICATION!")

    return passed == 15


if __name__ == '__main__':
    run_all_checks()
