-- AUTOGENERATED: do not edit manually
-- Generated by scripts/generate_conjugators_lean.py

import gl2_enumeration

open GL2F3
open GL2F3Enumeration

namespace GL2F3Enumeration

/-- Generated constructive conjugacy lemma (python-generated witnesses). -/
theorem candidates_conjugate_generated :
  ∀ M ∈ candidates, ∃ P ∈ invertible_matrices, P ⬝ M ⬝ inv2x2 P = GL2F3.A_diag_mat := by
  intro M hM
  have cases :
        M = mk2x2 0 1 1 0
        ∨ M = mk2x2 0 2 2 0
        ∨ M = mk2x2 1 0 0 2
        ∨ M = mk2x2 1 0 1 2
        ∨ M = mk2x2 1 0 2 2
        ∨ M = mk2x2 1 1 0 2
        ∨ M = mk2x2 1 2 0 2
        ∨ M = mk2x2 2 0 0 1
        ∨ M = mk2x2 2 0 1 1
        ∨ M = mk2x2 2 0 2 1
        ∨ M = mk2x2 2 1 0 1
        ∨ M = mk2x2 2 2 0 1 := by
    dec_trivial
  rcases cases with
  | Or.inl h =>
    let P := mk2x2 1 1 2 1
    have memP : P ∈ invertible_matrices := by
      simp [invertible_matrices, all_matrices]
      simp [P]
      decide
    refine Exists.intro P (And.intro memP ?_)
    -- check conjugacy by computation
    simp [P, h, inv2x2, adj2x2, Matrix.mul_apply]
    ring
  | Or.inr (Or.inl h) =>
    let P := mk2x2 1 1 1 2
    have memP : P ∈ invertible_matrices := by
      simp [invertible_matrices, all_matrices]
      simp [P]
      decide
    refine Exists.intro P (And.intro memP ?_)
    -- check conjugacy by computation
    simp [P, h, inv2x2, adj2x2, Matrix.mul_apply]
    ring
  | Or.inr (Or.inr (Or.inl h)) =>
    let P := mk2x2 0 1 1 0
    have memP : P ∈ invertible_matrices := by
      simp [invertible_matrices, all_matrices]
      simp [P]
      decide
    refine Exists.intro P (And.intro memP ?_)
    -- check conjugacy by computation
    simp [P, h, inv2x2, adj2x2, Matrix.mul_apply]
    ring
  | Or.inr (Or.inr (Or.inr (Or.inl h))) =>
    let P := mk2x2 0 1 1 2
    have memP : P ∈ invertible_matrices := by
      simp [invertible_matrices, all_matrices]
      simp [P]
      decide
    refine Exists.intro P (And.intro memP ?_)
    -- check conjugacy by computation
    simp [P, h, inv2x2, adj2x2, Matrix.mul_apply]
    ring
  | Or.inr (Or.inr (Or.inr (Or.inr (Or.inl h)))) =>
    let P := mk2x2 0 1 1 1
    have memP : P ∈ invertible_matrices := by
      simp [invertible_matrices, all_matrices]
      simp [P]
      decide
    refine Exists.intro P (And.intro memP ?_)
    -- check conjugacy by computation
    simp [P, h, inv2x2, adj2x2, Matrix.mul_apply]
    ring
  | Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl h))))) =>
    let P := mk2x2 1 1 1 0
    have memP : P ∈ invertible_matrices := by
      simp [invertible_matrices, all_matrices]
      simp [P]
      decide
    refine Exists.intro P (And.intro memP ?_)
    -- check conjugacy by computation
    simp [P, h, inv2x2, adj2x2, Matrix.mul_apply]
    ring
  | Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl h)))))) =>
    let P := mk2x2 1 1 2 0
    have memP : P ∈ invertible_matrices := by
      simp [invertible_matrices, all_matrices]
      simp [P]
      decide
    refine Exists.intro P (And.intro memP ?_)
    -- check conjugacy by computation
    simp [P, h, inv2x2, adj2x2, Matrix.mul_apply]
    ring
  | Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl h))))))) =>
    let P := mk2x2 1 0 0 1
    have memP : P ∈ invertible_matrices := by
      simp [invertible_matrices, all_matrices]
      simp [P]
      decide
    refine Exists.intro P (And.intro memP ?_)
    -- check conjugacy by computation
    simp [P, h, inv2x2, adj2x2, Matrix.mul_apply]
    ring
  | Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl h)))))))) =>
    let P := mk2x2 1 0 1 1
    have memP : P ∈ invertible_matrices := by
      simp [invertible_matrices, all_matrices]
      simp [P]
      decide
    refine Exists.intro P (And.intro memP ?_)
    -- check conjugacy by computation
    simp [P, h, inv2x2, adj2x2, Matrix.mul_apply]
    ring
  | Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl h))))))))) =>
    let P := mk2x2 1 0 2 1
    have memP : P ∈ invertible_matrices := by
      simp [invertible_matrices, all_matrices]
      simp [P]
      decide
    refine Exists.intro P (And.intro memP ?_)
    -- check conjugacy by computation
    simp [P, h, inv2x2, adj2x2, Matrix.mul_apply]
    ring
  | Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl h)))))))))) =>
    let P := mk2x2 1 1 0 2
    have memP : P ∈ invertible_matrices := by
      simp [invertible_matrices, all_matrices]
      simp [P]
      decide
    refine Exists.intro P (And.intro memP ?_)
    -- check conjugacy by computation
    simp [P, h, inv2x2, adj2x2, Matrix.mul_apply]
    ring
  | Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inr (Or.inl h))))))))))) =>
    let P := mk2x2 1 1 0 1
    have memP : P ∈ invertible_matrices := by
      simp [invertible_matrices, all_matrices]
      simp [P]
      decide
    refine Exists.intro P (And.intro memP ?_)
    -- check conjugacy by computation
    simp [P, h, inv2x2, adj2x2, Matrix.mul_apply]
    ring

end GL2F3Enumeration
