#!/usr/bin/env python3
"""Analyze irreducibility of the 81-dim representation of Sp(4,3) on H1(W33).

Method:
- Construct symplectic transvections T(u) = I + u (J u)^T over GF(3)
- Induce permutation action on W33 vertices and edges
- Compute induced matrices on H1 harmonic basis and compute commutant dimension
- If commutant dimension = 1 (scalars), representation is irreducible (Schur)
"""
from __future__ import annotations

import itertools
import json
from typing import List

import numpy as np

import sys
from pathlib import Path as _Path
sys.path.insert(0, str(_Path(__file__).parent))

from w33_hodge import compute_hodge_laplacians, compute_h1_kernel
from w33_homology import build_w33


def gf3(x: int) -> int:
    return int(x % 3)


def mat_mod3(A: np.ndarray) -> np.ndarray:
    return np.array([[gf3(int(x)) for x in row] for row in A], dtype=int)


def J_matrix() -> np.ndarray:
    # symplectic form J in block form [[0, I], [-I, 0]] (4x4)
    J = np.zeros((4, 4), dtype=int)
    J[0, 1] = 1
    J[1, 0] = -1
    J[2, 3] = 1
    J[3, 2] = -1
    return mat_mod3(J)


def transvection_matrix(u: np.ndarray, J: np.ndarray) -> np.ndarray:
    """Return M = I + u (J u)^T over GF(3) as integer matrix 4x4."""
    u = u.reshape((4, 1))
    Ju = J @ u
    M = np.eye(4, dtype=int) + (u @ Ju.T)
    return mat_mod3(M)


def apply_matrix_to_projective_vertex(M: np.ndarray, v: tuple) -> tuple:
    """Apply 4x4 mod-3 matrix M to projective vector v (representative of point).
    Normalize so first nonzero entry is 1 (canonical rep used by build_w33).
    """
    vec = np.array(v, dtype=int).reshape((4, 1))
    res = (M @ vec) % 3
    res = tuple(int(x) for x in res.flatten())
    # normalize to canonical rep: multiply by inv of first nonzero entry
    for i, x in enumerate(res):
        if x % 3 != 0:
            inv = pow(int(x), -1, 3)
            norm = tuple((inv * int(y)) % 3 for y in res)
            return norm
    # zero vector (shouldn't happen for nonzero input)
    return res


def make_vertex_permutation(M: np.ndarray, vertices: List[tuple]):
    mapping = {}
    for idx, v in enumerate(vertices):
        newv = apply_matrix_to_projective_vertex(M, v)
        # find index of newv in vertices
        j = vertices.index(newv)
        mapping[idx] = j
    return mapping


def permutation_on_edges(perm_vertex: dict, edges: List[tuple]) -> List[int]:
    m = len(edges)
    perm_edges = [-1] * m
    edge_index = {e: i for i, e in enumerate(edges)}
    # include flipped edges as (min,max)
    edge_index.update({(b, a): i for (a, b), i in edge_index.items()})
    for i, (a, b) in enumerate(edges):
        a2 = perm_vertex[a]
        b2 = perm_vertex[b]
        key = (min(a2, b2), max(a2, b2))
        j = edge_index[key]
        perm_edges[i] = j
    return perm_edges


def permutation_matrix_from_perm(perm: List[int]) -> np.ndarray:
    m = len(perm)
    P = np.zeros((m, m), dtype=float)
    for i, j in enumerate(perm):
        P[j, i] = 1.0
    return P


def compute_commutant_dim_by_group(gen_vertex_perms: List[dict], harmonic_basis: np.ndarray, edges: List[tuple]) -> int:
    """Compute commutant dimension using group closure and character averaging.

    Uses the identity for finite groups:
      dim(End_G(V)) = (1/|G|) * sum_{g in G} |chi(g)|^2,
    where chi(g) = trace(R_g) and R_g = W^T P_g W is the representation on the
    harmonic subspace. We compute chi(g) efficiently via chi(g) = trace(P_g S)
    with S = W W^T to avoid building R_g explicitly.
    """
    from collections import deque

    # Convert generator vertex permutations to canonical tuple form
    if isinstance(gen_vertex_perms[0], dict):
        # dict mapping idx -> j
        n = max(max(g.keys()) for g in gen_vertex_perms) + 1
        gens_v = [tuple(int(g[i]) for i in range(n)) for g in gen_vertex_perms]
    else:
        gens_v = [tuple(g) for g in gen_vertex_perms]
        n = len(gens_v[0])

    m = len(edges)

    # Precompute generator edge permutations
    gens_e = [tuple(permutation_on_edges(g, edges)) for g in gens_v]

    # Projection matrix S = W W^T (shape m x m)
    W = harmonic_basis
    S = np.asarray(W @ W.T, dtype=float)

    # Enumerate group generated by gens_v using BFS on vertex permutations,
    # carrying along the corresponding edge permutation so we can compute traces.
    id_v = tuple(range(n))
    id_e = tuple(range(m))
    visited = set([id_v])
    queue = deque([(id_v, id_e)])

    total = 0.0
    count = 0
    ar = np.arange(m, dtype=int)

    while queue:
        cur_v, cur_e = queue.popleft()
        # compute character via vectorized indexing
        cur_e_np = np.asarray(cur_e, dtype=int)
        chi = float(S[ar, cur_e_np].sum())
        total += chi * chi
        count += 1

        for gen_v, gen_e in zip(gens_v, gens_e):
            # composition new = gen o cur
            new_v = tuple(gen_v[i] for i in cur_v)
            new_e = tuple(gen_e[i] for i in cur_e)
            if new_v not in visited:
                visited.add(new_v)
                queue.append((new_v, new_e))

    avg = total / max(1, count)
    return int(round(avg))


def main():
    # Build underlying W33 vertex representatives as canonical vectors used in build_w33
    n, vertices, adj, edges = build_w33()
    # But build_w33 returns vertices as tuples in F3^4 canonical reps
    verts = vertices

    # Prepare harmonic basis
    Ls = compute_hodge_laplacians()
    L1 = Ls["L1"]
    harmonic_basis, _ = compute_h1_kernel(L1)

    # Choose several transvections
    J = J_matrix()
    # pick some u vectors (nonzero) in F3^4; choose basis + some combos
    vs = [np.array([1, 0, 0, 0], dtype=int), np.array([0, 1, 0, 0], dtype=int), np.array([0, 0, 1, 0], dtype=int), np.array([0, 0, 0, 1], dtype=int), np.array([1, 1, 0, 0], dtype=int), np.array([0, 1, 1, 0], dtype=int)]
    symp_mats = [transvection_matrix(u, J) for u in vs]

    # Induce vertex permutation generators and compute commutant dimension via group traces
    gen_vertex_perms = [make_vertex_permutation(M.tolist(), verts) for M in symp_mats]
    comm_dim = compute_commutant_dim_by_group(gen_vertex_perms, harmonic_basis, edges)
    print("Commutant dimension (approx):", comm_dim)

    # Heuristically, comm_dim==1 => irreducible over C (Schur)
    out = {"commutant_dim": int(comm_dim)}
    print(out)

    # write results to checks/
    import time
    from pathlib import Path
    ts = int(time.time())
    out_path = Path.cwd() / "checks" / f"PART_CVII_h1_irreducibility_{ts}.json"
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(out, f, indent=2)
    print(f"Wrote irreducibility result to {out_path}")
    return out


if __name__ == "__main__":
    main()
