#!/usr/bin/env python3
"""Analyse the 500 involution quadruples previously collected to extract
structural invariants that explain the obstruction.

Specifically compute the subgroup sizes generated by various subsets and
their intersections.  The results will be used as evidence that any
solution respecting the edge permutations forces the wrong intersection
size.
"""

import json
from collections import deque, Counter


# load raw solutions from enumeration
j=json.load(open('unrestricted_solutions.json'))
solutions=len(j['solutions'])
pairs=j['pairs']
edge_of=[pairs[i][0] for i in range(48)]
print(f"analyzing {solutions} quadruples\n")

# helper to compute orbit size under given generators using BFS

def orbit_size(gen_list, start=0):
    seen=set([start])
    q=deque([start])
    while q:
        v=q.popleft()
        for g in gen_list:
            w=g[v]
            if w not in seen:
                seen.add(w); q.append(w)
    return len(seen)

# compute intersection (approximate) by counting points fixed by both orbit closures

def intersection_orbit_size(gensA, gensB):
    count=0
    for v in range(48):
        if orbit_size(gensA,v)==1 and orbit_size(gensB,v)==1:
            count+=1
    return count

# compute intersection sizes
intersect_sizes=[]
for sol in j.get('solution_examples', [None]):
    pass
# actually solutions not saved; need to recompute by rerunning enumeration? easier: reload full file and parse if stored

# Instead regenerate from 500 solutions stored earlier? they weren't stored separately.
# we can modify enumeration script to save them, but by looking at json we see only pairs and stats, not sol data. so we can't analyze individual r's.


# helper closure with cutoff

def closure_elems(gen_list, max_elems=10000):
    G={tuple(range(48))}
    changed=True
    while changed:
        changed=False
        for g in list(G):
            for h in gen_list:
                comp=tuple(h[g[i]] for i in range(48))
                if comp not in G:
                    G.add(comp); changed=True
                    if len(G) > max_elems:
                        return None
    return G

# iterate solutions
counts=Counter()
intersections=Counter()
for sol in j['solutions']:
    gens=[tuple(sol[i]) for i in range(4)]
    size_all=orbit_size(gens)
    size_123=orbit_size(gens[1:4])
    size_012=orbit_size(gens[0:3])
    A=closure_elems(gens[0:3])
    B=closure_elems(gens[1:4])
    if A is None or B is None:
        inter=None
    else:
        inter=len(A & B)
    counts[(size_all,size_123,size_012)] +=1
    intersections[inter] +=1

print("group size distributions (all, r1..r3, r0..r2):")
for k,v in counts.items():
    print(v,k)
print("intersection sizes of <r0,r1,r2> & <r1,r2,r3>",intersections)

print("sample intersection values above")
