#!/usr/bin/env python3
"""Generate a Lean file embedding explicit conjugator witnesses found by Python enumeration.

Writes to `proofs/lean/conjugators_generated.lean` by default. The generated theorem is
`GL2F3Enumeration.candidates_conjugate_generated` which mirrors the hand-written proof
and can be used to detect drift between Python enumeration and checked-in Lean fixtures.
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Iterable, Sequence, Tuple

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in __import__("sys").path:
    __import__("sys").path.insert(0, str(ROOT))

from tools.analyze_gl2_f3_involution_conjugacy import build_report


def fmt_tuple(t: Sequence[int]) -> str:
    return ", ".join(str(int(x)) for x in t)


def mk_case_eq(m: Tuple[int, int, int, int]) -> str:
    a, b, c, d = m
    return f"M = mk2x2 {a} {b} {c} {d}"


def mk_branch(m: Tuple[int, int, int, int], p: Tuple[int, int, int, int]) -> str:
    """Return Lean branch text for a single case."""
    a, b, c, d = m
    p0, p1, p2, p3 = p
    branch = []
    branch.append(
        f"  | Or.inl h =>" if m == ordered[0] else "  | Or.inr " + "(Or.inl h) =>"
    )
    # The above line will be fixed up by the caller to chain ors properly; instead we will
    # generate a canonical sequence using the same pattern used in the hand-written file.
    return "TODO"


def generate(report: dict) -> str:
    rows = report.get("candidates", [])
    # Extract matrix -> conjugator (use first 4 entries)
    mapping: dict[tuple[int, int, int, int], tuple[int, int, int, int]] = {}
    for row in rows:
        mat = tuple(int(x) for x in row["matrix"][:4])
        conj = row.get("conjugator_example", None)
        if conj is None:
            raise RuntimeError(f"No conjugator example for matrix {mat}")
        mapping[mat] = tuple(int(x) for x in conj[:4])

    ordered = sorted(mapping.keys())
    if not ordered:
        raise RuntimeError(
            "No candidate matrices found in report; cannot generate Lean file"
        )

    # Build the big `M = mk2x2 ... ∨ M = mk2x2 ...` chain
    cases = "\n        ∨ ".join(
        f"M = mk2x2 {a} {b} {c} {d}" for (a, b, c, d) in ordered
    )

    # Build branches like: | Or.inl h => ... | Or.inr (Or.inl h) => ... etc
    branches: list[str] = []
    for idx, m in enumerate(ordered):
        if idx == 0:
            header = "  | Or.inl h =>"
        else:
            inner = "Or.inl h"
            for _ in range(idx):
                inner = f"Or.inr ({inner})"
            header = f"  | {inner} =>"
        p = mapping[m]
        p_line = f"    let P := mk2x2 {p[0]} {p[1]} {p[2]} {p[3]}"
        memP = (
            "    have memP : P ∈ invertible_matrices := by\n"
            "      simp [invertible_matrices, all_matrices]\n"
            "      simp [P]\n"
            "      decide"
        )
        body = (
            "    refine Exists.intro P (And.intro memP ?_)\n"
            "    -- check conjugacy by computation\n"
            "    simp [P, h, inv2x2, adj2x2, Matrix.mul_apply]\n"
            "    ring"
        )
        branches.append(f"{header}\n{p_line}\n{memP}\n{body}")

    file_text = f"""-- AUTOGENERATED: do not edit manually
-- Generated by scripts/generate_conjugators_lean.py

import gl2_base

open GL2F3
open GL2F3Enumeration

namespace GL2F3Enumeration

/-- Generated constructive conjugacy lemma (python-generated witnesses). -/
"""
    file_text += (
        "theorem candidates_conjugate_generated :\n"
        "  ∀ M ∈ candidates, ∃ P ∈ invertible_matrices, P ⬝ M ⬝ inv2x2 P = GL2F3.A_diag_mat := by\n"
        "  intro M hM\n"
        f"  have cases :\n        {cases} := by\n"
        "    dec_trivial\n"
        "  rcases cases with\n"
    )
    file_text += "\n".join(branches)
    file_text += "\n\nend GL2F3Enumeration\n"
    return file_text


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--out",
        type=Path,
        default=ROOT / "proofs" / "lean" / "conjugators_generated.lean",
    )
    args = parser.parse_args()

    report = build_report()
    text = generate(report)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(text, encoding="utf-8")
    print(f"Wrote {args.out}")
