#!/usr/bin/env python3
"""Tools for exploring the automorphism group of the 24‑dimensional Golay
Lie algebra.

The 
    inner automorphism subgroup
is generated (experimentally) by the "transvection" candidates
    T_x = I + ad(x)  (mod 3)
for the 24 basis elements.  Previous diagnostics produced around 4.26e6
distinct elements, but the full order remains to be computed.

This module provides a simple BFS-based enumerator for the group generated by
these matrices, along with routines to test how this subgroup interacts with
outer symplectic grade permutations.

The computations are moderately heavy (millions of 24x24 matrices) and may
require several seconds or minutes on a typical machine.  They are intended for
interactive experimentation rather than automated CI.
"""

from __future__ import annotations

from typing import Callable, Iterable, List, Optional

import numpy as np

# avoid circular import issues by delaying heavy imports

def _build_t_matrices() -> List[np.ndarray]:
    """Return the 24 candidate transvection matrices T_i = I + ad(e_i) mod 3."""
    from scripts.w33_golay_lie_algebra import build_golay_lie_algebra, _ad_matrices

    alg = build_golay_lie_algebra()
    ad = _ad_matrices(alg)
    I = np.eye(24, dtype=int)
    return [(I + A) % 3 for A in ad]


def compute_inner_aut_group(limit: Optional[int] = None) -> List[np.ndarray]:
    """Enumerate the subgroup generated by the T_i matrices.

    The return value is a list of distinct matrices (mod 3).  If ``limit`` is
    provided, enumeration stops after that many elements have been collected.
    """
    T = _build_t_matrices()
    I = np.eye(24, dtype=int)
    seen: set[bytes] = set()
    queue: List[np.ndarray] = []

    def key(M: np.ndarray) -> bytes:
        return M.astype(np.int64).tobytes()

    seen.add(key(I))
    queue.append(I.copy())

    while queue:
        M = queue.pop()
        for t in T:
            N = (M.dot(t) % 3).astype(np.int64)
            k = key(N)
            if k not in seen:
                seen.add(k)
                queue.append(N)
                if limit is not None and len(seen) >= limit:
                    return [np.frombuffer(k, dtype=np.int64).reshape(24, 24) for k in seen]
    return [np.frombuffer(k, dtype=np.int64).reshape(24, 24) for k in seen]


def permutation_matrix(perm: Iterable[int]) -> np.ndarray:
    """Convert a permutation of {0..23} into a 24x24 permutation matrix."""
    P = np.zeros((24, 24), dtype=int)
    for i, j in enumerate(perm):
        P[int(j), int(i)] = 1
    return P


def symplectic_conjugates_inner_group(limit: Optional[int] = 5000) -> bool:
    """Heuristic check: a symplectic grade map normalizes the generated subgroup.

    This constructs the inner subgroup up to ``limit`` elements and tests
    membership after conjugation by one nontrivial symplectic basis permutation.
    If it returns ``False`` the result may be inconclusive (the truncated group
    may simply miss conjugates).
    """
    try:
        from scripts.w33_golay_lie_algebra import (
            build_golay_lie_algebra,
            symplectic_aut_permutation,
        )
        from scripts.grade_weil_phase import all_symplectic_matrices
    except ImportError:
        return False
    alg = build_golay_lie_algebra()
    A0 = None
    for A in all_symplectic_matrices():
        if not np.array_equal(A, np.eye(2, dtype=int)):
            A0 = np.asarray(A, dtype=np.int64) % 3
            break
    if A0 is None:
        return False
    perm = symplectic_aut_permutation(alg, A0)
    if perm is None:
        return False
    P = permutation_matrix(perm)
    G = compute_inner_aut_group(limit=limit)
    return check_conjugation_stability(G, P)

def check_conjugation_stability(
    group: Iterable[np.ndarray], P: np.ndarray
) -> bool:
    """Return True if conjugating every element of ``group`` by ``P`` keeps it
    inside ``group``.
    ``group`` should be a list of matrices; membership is checked by a simple
    byte-string set.
    """
    seen = {np.asarray(g, dtype=np.int64).tobytes() for g in group}
    P = np.asarray(P, dtype=np.int64) % 3
    # Permutation matrices satisfy P^{-1} = P^T, so avoid float inverses.
    P_inv = P.T.copy() % 3
    for g in group:
        g = np.asarray(g, dtype=np.int64) % 3
        h = (P @ g @ P_inv) % 3
        if h.tobytes() not in seen:
            return False
    return True


def symplectic_conjugates_transvection_generators() -> bool:
    """Return True if a symplectic basis-permutation conjugates T_i as expected.

    If P is a Lie automorphism that permutes the monomial basis (our symplectic
    grade permutations do), then it should transport inner derivations by:

        P ad(e_i) P^{-1} = ad(P e_i) = ad(e_{perm[i]}).

    For the transvection candidates T_i = I + ad(e_i) mod 3 this implies:

        P T_i P^{-1} = T_{perm[i]}.
    """
    from scripts.grade_weil_phase import all_symplectic_matrices
    from scripts.w33_golay_lie_algebra import (
        build_golay_lie_algebra,
        _ad_matrices,
        symplectic_aut_permutation,
    )

    alg = build_golay_lie_algebra()
    ad = _ad_matrices(alg)
    I = np.eye(24, dtype=np.int64) % 3
    T = [(I + np.asarray(Ai, dtype=np.int64)) % 3 for Ai in ad]

    A0 = None
    for A in all_symplectic_matrices():
        if not np.array_equal(A, np.eye(2, dtype=int)):
            A0 = np.asarray(A, dtype=np.int64) % 3
            break
    if A0 is None:
        return False

    perm = symplectic_aut_permutation(alg, A0)
    if perm is None:
        return False
    P = permutation_matrix(perm).astype(np.int64) % 3
    P_inv = P.T.copy() % 3
    for i in range(24):
        lhs = (P @ T[i] @ P_inv) % 3
        rhs = T[int(perm[i])]
        if not np.array_equal(lhs, rhs):
            return False
    return True


def main() -> None:
    """Quick command‑line driver for exploring the inner automorphism group."""
    import time
    from scripts.grade_weil_phase import all_symplectic_matrices
    from scripts.w33_golay_lie_algebra import build_golay_lie_algebra, symplectic_aut_permutation

    t0 = time.time()
    print("building inner automorphism group (limit=unbounded)...")
    G = compute_inner_aut_group()
    print(f"inner group size = {len(G)}")
    print(f"elapsed {time.time() - t0:.2f}s")

    # test stability under one symplectic generator
    mats = all_symplectic_matrices()
    if mats:
        A = mats[0]
        perm = symplectic_aut_permutation(build_golay_lie_algebra(), A)
        P = permutation_matrix(perm)
        print("conjugation by first symplectic perm preserves group?", check_conjugation_stability(G, P))

    print("symplectic conjugates transvection generators?", symplectic_conjugates_transvection_generators())
    print("symplectic conjugates inner group? (heuristic, limit=5000)", symplectic_conjugates_inner_group())
    print("done")


if __name__ == "__main__":
    main()
