#!/usr/bin/env python3
"""Tools for exploring the automorphism group of the 24‑dimensional Golay
Lie algebra.

The 
    inner automorphism subgroup
is generated (experimentally) by the "transvection" candidates
    T_x = I + ad(x)  (mod 3)
for the 24 basis elements.  Previous diagnostics produced around 4.26e6
distinct elements, but the full order remains to be computed.

This module provides a simple BFS-based enumerator for the group generated by
these matrices, along with routines to test how this subgroup interacts with
outer symplectic grade permutations.

The computations are moderately heavy (millions of 24x24 matrices) and may
require several seconds or minutes on a typical machine.  They are intended for
interactive experimentation rather than automated CI.
"""

from __future__ import annotations

from typing import Callable, Iterable, List, Optional

import numpy as np

# avoid circular import issues by delaying heavy imports

def _build_t_matrices() -> List[np.ndarray]:
    """Return the 24 candidate transvection matrices T_i = I + ad(e_i) mod 3."""
    from scripts.w33_golay_lie_algebra import build_golay_lie_algebra, _ad_matrices

    alg = build_golay_lie_algebra()
    ad = _ad_matrices(alg)
    I = np.eye(24, dtype=int)
    return [(I + A) % 3 for A in ad]


def compute_inner_aut_group(limit: Optional[int] = None) -> List[np.ndarray]:
    """Enumerate the subgroup generated by the T_i matrices.

    The return value is a list of distinct matrices (mod 3).  If ``limit`` is
    provided, enumeration stops after that many elements have been collected.
    """
    T = _build_t_matrices()
    I = np.eye(24, dtype=int)
    seen: set[bytes] = set()
    queue: List[np.ndarray] = []

    def key(M: np.ndarray) -> bytes:
        return M.astype(np.int64).tobytes()

    seen.add(key(I))
    queue.append(I.copy())

    while queue:
        M = queue.pop()
        for t in T:
            N = (M.dot(t) % 3).astype(np.int64)
            k = key(N)
            if k not in seen:
                seen.add(k)
                queue.append(N)
                if limit is not None and len(seen) >= limit:
                    return [np.frombuffer(k, dtype=np.int64).reshape(24, 24) for k in seen]
    return [np.frombuffer(k, dtype=np.int64).reshape(24, 24) for k in seen]


def permutation_matrix(perm: Iterable[int]) -> np.ndarray:
    """Convert a permutation of {0..23} into a 24×24 permutation matrix."""
    P = np.zeros((24, 24), dtype=int)
    for i, j in enumerate(perm):
        P[int(j), int(i)] = 1
    return P


def check_conjugation_stability(
    group: Iterable[np.ndarray], P: np.ndarray
) -> bool:
    """Return True if conjugating every element of ``group`` by ``P`` keeps it
    inside ``group``.
    ``group`` should be a list of matrices; membership is checked by a simple
    byte-string set.
    """
    seen = {g.tobytes() for g in group}
    for g in group:
        h = (P.dot(g).dot(np.linalg.inv(P)) % 3).astype(np.int64)
        if h.tobytes() not in seen:
            return False
    return True


def main() -> None:
    """Quick command‑line driver for exploring the inner automorphism group."""
    import time
    from scripts.grade_weil_phase import all_symplectic_matrices
    from scripts.w33_golay_lie_algebra import symplectic_aut_permutation

    t0 = time.time()
    print("building inner automorphism group (limit=unbounded)...")
    G = compute_inner_aut_group()
    print(f"inner group size = {len(G)}")
    print(f"elapsed {time.time() - t0:.2f}s")

    # test stability under one symplectic generator
    mats = all_symplectic_matrices()
    if mats:
        A = mats[0]
        perm = symplectic_aut_permutation(build_golay_lie_algebra(), A)
        P = permutation_matrix(perm)
        print("conjugation by first symplectic perm preserves group?", check_conjugation_stability(G, P))

    print("done")


if __name__ == "__main__":
    main()
