from collections import Counter, deque
from pathlib import Path

from scripts.w33_permrep_association import _point_bfs_coset_reps, parse_gap_permrep


def main():
    p1 = Path("data/HeG1-p2058B0.g1")
    p2 = Path("data/HeG1-p2058B0.g2")
    perms1 = parse_gap_permrep(p1)
    perms2 = parse_gap_permrep(p2)
    print("parsed perms:", len(perms1), len(perms2))
    perms = perms1 + perms2
    n = len(perms[0])
    print("degree =", n)

    for i, g in enumerate(perms):
        moved = [j for j, a in enumerate(g) if a != j]
        # cycle decomposition counts
        seen = [False] * n
        cycles = []
        for idx in range(n):
            if seen[idx]:
                continue
            j = idx
            cyc = []
            while not seen[j]:
                seen[j] = True
                cyc.append(j)
                j = g[j]
            if len(cyc) > 1:
                cycles.append(len(cyc))
        cycles.sort()
        print(
            f"gen{i}: moved={len(moved)} support_sample={moved[:8]} cycles_count={len(cycles)} largest_cycles={cycles[-5:]}"
        )

    # orbit on points under the generators (point-BFS)
    coset = _point_bfs_coset_reps(perms, n, base=0)
    print("coset size (point-bfs reps):", len(coset))

    # BFS orbit generated by action of gens on point 0
    seen = {0}
    q = deque([0])
    while q:
        u = q.popleft()
        for g in perms:
            v = g[u]
            if v not in seen:
                seen.add(v)
                q.append(v)
    print("orbit size under gens (starting at 0):", len(seen))
    print("orbit sample (first 80):", sorted(list(seen))[:80])

    # report counts of orbit sizes across all points
    visited = [False] * n
    orbit_sizes = []
    for v in range(n):
        if visited[v]:
            continue
        q = deque([v])
        visited[v] = True
        size = 0
        while q:
            x = q.popleft()
            size += 1
            for g in perms:
                y = g[x]
                if not visited[y]:
                    visited[y] = True
                    q.append(y)
        orbit_sizes.append(size)
    orbit_sizes.sort()
    print(
        "orbit sizes from gens (sorted):",
        orbit_sizes[:10],
        "... total parts =",
        len(orbit_sizes),
    )


if __name__ == "__main__":
    main()
