"""Utilities for monomial permutation groups and phase lifts.

The ternary Golay / Mathieu 12-point story requires working with monomial
maps (permutation + diagonal sign) over F3.  The functions here abstract the
basic algebra so that more scripts can reuse them without duplication.

A monomial element is represented as a pair ``(perm, signs)`` where
``perm`` is a tuple of length *n* describing a coordinate permutation and
``signs`` is a tuple of the same length with entries in \{1,2\} representing
multiplicative factors in F3.  Composition is then

    (D_a P_a) (D_b P_b) = D_a (P_a D_b P_a^{-1}) (P_a P_b)

and inversion follows the obvious reindexing formula.
"""

from __future__ import annotations

import itertools
from collections import deque
from typing import Iterable, List, Optional, Tuple

import numpy as np

Monomial = Tuple[Tuple[int, ...], Tuple[int, ...]]


# ---------------------------------------------------------------------------
# basic monomial arithmetic
# ---------------------------------------------------------------------------

def perm_inverse(perm: Tuple[int, ...]) -> Tuple[int, ...]:
    inv = [0] * len(perm)
    for i, j in enumerate(perm):
        inv[int(j)] = int(i)
    return tuple(inv)


def monomial_mul(a: Monomial, b: Monomial) -> Monomial:
    """Multiply two monomial maps (perm, signs).

    The result is also expressed in the (perm, signs) convention used
    throughout the repo.
    """
    perm_a, signs_a = a
    perm_b, signs_b = b
    n = len(perm_a)
    assert n == len(perm_b) == len(signs_a) == len(signs_b)

    perm_out = tuple(int(perm_a[int(perm_b[i])]) for i in range(n))
    inv_perm_a = perm_inverse(perm_a)
    signs_out = tuple(
        (int(signs_a[j]) * int(signs_b[int(inv_perm_a[j])])) % 3 for j in range(n)
    )
    return perm_out, signs_out


def monomial_inv(elem: Monomial) -> Monomial:
    """Inverse of a monomial element."""
    perm, signs = elem
    n = len(perm)
    inv_perm = perm_inverse(perm)
    signs_inv = tuple(int(signs[int(perm[j])]) % 3 for j in range(n))
    return inv_perm, signs_inv


def monomial_group_order(gens: Iterable[Monomial], limit: Optional[int] = None) -> int:
    """Return order of subgroup generated by ``gens``.

    BFS is used; ``limit`` can cap enumeration if an upper bound is known.
    """
    gens = list(gens)
    if not gens:
        return 1
    n = len(gens[0][0])
    ident = (tuple(range(n)), tuple([1] * n))
    seen: set[Monomial] = {ident}
    q: deque[Monomial] = deque([ident])
    while q:
        x = q.popleft()
        for g in gens:
            y = monomial_mul(x, g)
            if y not in seen:
                seen.add(y)
                q.append(y)
                if limit is not None and len(seen) >= limit:
                    return len(seen)
    return len(seen)


def apply_monomial(
    word: Tuple[int, ...], perm: Tuple[int, ...], signs: Tuple[int, ...]
) -> Tuple[int, ...]:
    """Apply monomial map to a vector over F3 (represented as tuple).

    The convention is the same as :func:`scripts.w33_monster_11a_m12_golay_bridge._act_word_by_monomial`:
    first perform the permutation ``out[j] = word[i]`` where ``perm[i]=j``,
    then multiply each coordinate by the corresponding `signs` entry.
    """
    n = len(word)
    assert len(perm) == n and len(signs) == n
    # apply permutation in the same orientation as _act_word_by_perm
    out = [0] * n
    for i, j in enumerate(perm):
        out[int(j)] = int(word[int(i)]) % 3
    return tuple((int(signs[i]) * int(out[i])) % 3 for i in range(n))


def find_sign_lift_for_perm(
    *,
    perm: Tuple[int, ...],
    generator_rows: Iterable[Tuple[int, ...]],
    code_set: set[Tuple[int, ...]],
) -> Optional[Tuple[int, ...]]:
    """Return a sign vector in {1,2}^n making ``perm`` preserve the code.

    We still search over all sign choices, but once a candidate satisfies the
    generator-row constraints we additionally verify that *every* codeword is
    taken to another codeword.  That stronger requirement matches the later
    sanity check previously done in the 11A bridge and avoids choosing a
    "false positive" sign vector.
    """
    n = len(perm)
    for signs in itertools.product((1, 2), repeat=n):
        # quick generator-row check first
        ok = True
        for row in generator_rows:
            if apply_monomial(row, perm, signs) not in code_set:
                ok = False
                break
        if not ok:
            continue
        # full code preservation test
        for cw in code_set:
            if apply_monomial(cw, perm, signs) not in code_set:
                ok = False
                break
        if ok:
            return tuple(int(x) for x in signs)
    return None


def find_sign_lifts_for_group(
    perms: Iterable[Tuple[int, ...]],
    generator_rows: Iterable[Tuple[int, ...]],
    code_set: set[Tuple[int, ...]],
) -> Optional[List[Tuple[int, ...]]]:
    """Attempt to find a sign lift for each permutation in ``perms``.

    Returns a list of sign tuples in the same order as ``perms`` if
    every permutation admits a lift; otherwise ``None``.
    """
    lifts: List[Tuple[int, ...]] = []
    for perm in perms:
        signs = find_sign_lift_for_perm(
            perm=perm, generator_rows=generator_rows, code_set=code_set
        )
        if signs is None:
            return None
        lifts.append(signs)
    return lifts
