#!/usr/bin/env python3
"""Golay-side outer normalizer: construct M12:2 inside Sp(12,3) from 11A data.

This repo contains two independent embeddings related to Monster centralizers:

  - 3B backend:  2.Suz ⊂ Sp(12,3) with an ATLAS-word witness for M12:2 < Suz
    (see scripts/w33_2suz_m12_2_subgroup.py).

  - 11A backend: monomial sign lifts on the ternary Golay code give a 2-cover
    2.M12 acting on F3^12 (see scripts/w33_monster_11a_m12_golay_bridge.py).

The Golay construction naturally produces a block-diagonal symplectic model
diag(g, g^{-T}) in a Lagrangian "p-axis gauge"
(scripts/w33_2m12_sp12_embedding.py).

The missing piece on the Golay side is the outer element (Fourier swap) that
extends 2.M12 to a preimage of M12:2 inside Sp(12,3), matching the Suz witness.

We find it by solving an intertwining problem in the induced 6D representation.

  Let H = <g11, g21> ⊂ GL(6,3) be the Golay-derived 2.M12 action in p-axis gauge.
  Let H* be the dual action generated by g11^{-T}, g21^{-T}.

We search for A ∈ GL(6,3) with A H* A^{-1} = H. Then the symplectic swap

    X = [[0, A],
         [-A^{-T}, 0]]

normalizes the symplectic embedding diag(H, H^{-T}) ⊂ Sp(12,3) and yields the
expected index-2 extension (projectively M12:2).

Run:
  & .venv\\Scripts\\python.exe -X utf8 scripts\\w33_2m12_outer_normalizer.py
"""

from __future__ import annotations

import sys
import time
from pathlib import Path
from typing import Any, Iterable

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
SCRIPTS_DIR = ROOT / "scripts"
for p in (ROOT, SCRIPTS_DIR):
    if str(p) not in sys.path:
        sys.path.insert(0, str(p))


def _mat_mod_p(A: np.ndarray, p: int) -> np.ndarray:
    return (np.asarray(A, dtype=np.int64) % int(p)).astype(np.int64)


def _inv_mod_p(A: np.ndarray, p: int) -> np.ndarray:
    """Matrix inverse over GF(p). Raises ValueError if singular."""
    A = _mat_mod_p(A, p)
    n = int(A.shape[0])
    if A.shape != (n, n):
        raise ValueError(f"expected square matrix, got {A.shape}")
    aug = np.concatenate([A.copy(), np.eye(n, dtype=np.int64)], axis=1) % p

    r = 0
    for c in range(n):
        pivot = None
        for i in range(r, n):
            if int(aug[i, c]) % p != 0:
                pivot = i
                break
        if pivot is None:
            continue
        if pivot != r:
            aug[[r, pivot]] = aug[[pivot, r]]
        inv = pow(int(aug[r, c] % p), -1, p)
        aug[r, :] = (aug[r, :] * inv) % p
        for i in range(n):
            if i == r:
                continue
            factor = int(aug[i, c] % p)
            if factor:
                aug[i, :] = (aug[i, :] - factor * aug[r, :]) % p
        r += 1
        if r == n:
            break

    left = aug[:, :n] % p
    if not np.array_equal(left, np.eye(n, dtype=np.int64) % p):
        raise ValueError("matrix is singular over GF(p)")
    return aug[:, n:] % p


def _matrix_bytes(M: np.ndarray, p: int) -> bytes:
    return (_mat_mod_p(M, p)).astype(np.uint8, copy=False).tobytes()


def _group_elements_bytes(
    gens: Iterable[np.ndarray], *, p: int = 3, limit: int | None = None
) -> list[bytes]:
    """Enumerate group elements by BFS closure under right-multiplication."""
    gens = [(_mat_mod_p(g, p)).astype(np.int16) for g in gens]
    if not gens:
        return [np.eye(1, dtype=np.uint8).tobytes()]
    n = int(gens[0].shape[0])
    I = (np.eye(n, dtype=np.int64) % p).astype(np.uint8)
    id_b = I.tobytes()
    elems: list[bytes] = [id_b]
    seen: set[bytes] = {id_b}

    idx = 0
    while idx < len(elems):
        g_b = elems[idx]
        idx += 1
        g = (
            np.frombuffer(g_b, dtype=np.uint8)
            .astype(np.int16, copy=False)
            .reshape((n, n))
        )
        for gen in gens:
            h = (g @ gen) % p
            h_b = h.astype(np.uint8, copy=False).tobytes()
            if h_b in seen:
                continue
            seen.add(h_b)
            elems.append(h_b)
            if limit is not None and len(seen) > int(limit):
                raise RuntimeError(f"group enumeration exceeded limit={limit}")
    return elems


def _order_mod_p(M: np.ndarray, *, p: int = 3, max_pow: int = 2000) -> int | None:
    """Multiplicative order of M in GL(n,p) if <= max_pow."""
    M = _mat_mod_p(M, p).astype(np.int16)
    n = int(M.shape[0])
    I = np.eye(n, dtype=np.int16) % p
    P = I.copy()
    for k in range(1, int(max_pow) + 1):
        P = (P @ M) % p
        if np.array_equal(P, I):
            return int(k)
    return None


def _nullspace_basis_mod_p(M: np.ndarray, p: int) -> list[np.ndarray]:
    from scripts.w33_2suz_m12_2_subgroup import _nullspace_basis_mod_p

    return _nullspace_basis_mod_p(_mat_mod_p(M, p), p)


def _monomial_matrix(
    perm: tuple[int, ...], signs: tuple[int, ...], p: int = 3
) -> np.ndarray:
    """Return the monomial matrix D*P in the repo convention perm[i]=j via out[j]=word[i]."""
    n = len(perm)
    M = np.zeros((n, n), dtype=np.int64)
    for i, j in enumerate(perm):
        M[int(j), int(i)] = int(signs[int(j)]) % p
    return M % p


def _golay_p_axis_generators() -> tuple[np.ndarray, np.ndarray]:
    """Return (g11, g21) as 6×6 generators in the Golay p-axis gauge."""
    from tools.s12_universal_algebra import ternary_golay_generator_matrix
    from scripts.w33_monster_11a_m12_golay_bridge import analyze as analyze_11a_bridge

    p = 3
    gen = ternary_golay_generator_matrix()
    G = _mat_mod_p(np.array(gen, dtype=np.int64), p)
    if G.shape != (6, 12):
        raise RuntimeError(f"unexpected Golay generator shape: {G.shape}")
    I6 = np.eye(6, dtype=np.int64) % p
    if not np.array_equal(G[:, :6], I6):
        raise RuntimeError("expected systematic Golay generator [I|A]")
    A = _mat_mod_p(G[:, 6:], p)

    Z6 = np.zeros((6, 6), dtype=np.int64)
    S = np.block([[I6, Z6], [(-A) % p, I6]]) % p
    S_inv = np.block([[I6, Z6], [A % p, I6]]) % p

    bridge = analyze_11a_bridge(compute_monomial_order=False)
    if bridge.get("available") is not True:
        raise RuntimeError(f"11A bridge unavailable: {bridge.get('reason')}")
    golay = bridge.get("golay", {})
    gens = golay.get("m12_generators_in_code_coords", {})
    lifts = golay.get("monomial_lift_signs", {})
    if not (isinstance(gens, dict) and isinstance(lifts, dict)):
        raise RuntimeError("missing generators/lifts in 11A bridge payload")

    b11_perm = tuple(int(x) for x in gens["b11_code_perm"])
    b21_perm = tuple(int(x) for x in gens["b21_code_perm"])
    s11 = tuple(int(x) % p for x in lifts["b11_code"])
    s21 = tuple(int(x) % p for x in lifts["b21_code"])

    M11 = _monomial_matrix(b11_perm, s11, p=p)
    M21 = _monomial_matrix(b21_perm, s21, p=p)
    M11p = (S @ M11 @ S_inv) % p
    M21p = (S @ M21 @ S_inv) % p

    bl11 = _mat_mod_p(M11p[6:, :6], p)
    bl21 = _mat_mod_p(M21p[6:, :6], p)
    if not (np.all(bl11 == 0) and np.all(bl21 == 0)):
        raise RuntimeError("expected conjugated monomial generators to preserve p-axis")

    g11 = _mat_mod_p(M11p[:6, :6], p)
    g21 = _mat_mod_p(M21p[:6, :6], p)
    return g11 % p, g21 % p


def analyze(*, compute_full_order: bool = False, include_matrices: bool = False) -> dict[str, Any]:
    """Find a Golay-side outer normalizer element extending 2.M12 to M12:2."""
    p = 3
    t0 = time.time()

    g11, g21 = _golay_p_axis_generators()
    g11_inv = _inv_mod_p(g11, p)
    g21_inv = _inv_mod_p(g21, p)

    # Dual (contragredient) generators.
    d11 = g11_inv.T % p
    d21 = g21_inv.T % p

    # Enumerate H = <g11,g21>.
    elems = _group_elements_bytes([g11, g21], p=p, limit=250_000)
    seen = set(elems)
    base_order = int(len(elems))
    if base_order != 190_080:
        raise RuntimeError(f"unexpected base group order: {base_order}")

    I6 = np.eye(6, dtype=np.int64) % p
    rng = np.random.default_rng(12345)

    def _has_order(h: np.ndarray, o: int) -> bool:
        if o == 1:
            return bool(np.array_equal(h % p, I6))
        if o == 2:
            return bool(np.array_equal((h @ h) % p, I6)) and not bool(
                np.array_equal(h % p, I6)
            )
        if o == 3:
            return bool(np.array_equal((h @ h @ h) % p, I6)) and not bool(
                np.array_equal(h % p, I6)
            )
        if o == 6:
            h2 = (h @ h) % p
            h3 = (h2 @ h) % p
            h6 = (h3 @ h3) % p
            return bool(np.array_equal(h6, I6)) and not bool(np.array_equal(h3, I6))
        return _order_mod_p(h, p=p, max_pow=5000) == int(o)

    def _pow_mod_small(M: np.ndarray, k: int) -> np.ndarray:
        out = I6.copy()
        base = M % p
        kk = int(k)
        while kk:
            if kk & 1:
                out = (out @ base) % p
            base = (base @ base) % p
            kk >>= 1
        return out % p

    def _prod_matches_order(P: np.ndarray, ord_target: int) -> bool:
        """Fast order filter for the common ord_target values (11 or 22)."""
        if np.array_equal(P % p, I6):
            return False
        ord_target = int(ord_target)
        if ord_target == 11:
            return bool(np.array_equal(_pow_mod_small(P, 11), I6))
        if ord_target == 22:
            return bool(np.array_equal(_pow_mod_small(P, 22), I6)) and not bool(
                np.array_equal(_pow_mod_small(P, 11), I6)
            )
        o = _order_mod_p(P, p=p, max_pow=5000)
        return o == ord_target

    def _find_A_for_targets(
        *, dd11: np.ndarray, dd21: np.ndarray, h1: np.ndarray, h2: np.ndarray
    ) -> np.ndarray | None:
        """Solve A dd11 = h1 A and A dd21 = h2 A; return an invertible A if found.

        Prefer symmetric solutions A = A^T when available. In that case the
        symplectic swap X = [[0,A],[-A^{-T},0]] satisfies X^2 = -I_12 and has
        the canonical order-4 "Fourier" signature.
        """
        L1 = np.kron(dd11.T % p, I6) % p
        L2 = np.kron(dd21.T % p, I6) % p
        K1 = (L1 - np.kron(I6, h1 % p)) % p
        K2 = (L2 - np.kron(I6, h2 % p)) % p
        K = np.concatenate([K1, K2], axis=0) % p
        if K.size == 0:
            return None

        def _enumerate_candidates(vecs: list[np.ndarray]) -> list[tuple[int, ...]]:
            k = len(vecs)
            coeffs: list[tuple[int, ...]] = []
            for i in range(k):
                c = [0] * k
                c[i] = 1
                coeffs.append(tuple(c))

            kk = min(k, 12)
            for i in range(kk):
                for j in range(i + 1, kk):
                    for a in (1, 2):
                        for b in (1, 2):
                            c = [0] * k
                            c[i] = a
                            c[j] = b
                            coeffs.append(tuple(c))

            if k <= 7:
                for idx in range(1, p**k):
                    x = idx
                    c = []
                    for _ in range(k):
                        c.append(int(x % p))
                        x //= p
                    coeffs.append(tuple(c))
            else:
                for _ in range(8000):
                    c = tuple(int(x) for x in rng.integers(0, p, size=(k,)))
                    if any(c):
                        coeffs.append(c)
            return coeffs

        def _search_from_basis(basis: list[np.ndarray]) -> np.ndarray | None:
            if not basis:
                return None
            vecs = [v.reshape((-1,)) % p for v in basis]
            coeffs = _enumerate_candidates(vecs)

            for c in coeffs:
                v = np.zeros((36,), dtype=np.int64)
                for ci, bi in zip(c, vecs):
                    if ci:
                        v = (v + int(ci) * bi) % p
                if not np.any(v):
                    continue
                A = v.reshape((6, 6), order="F") % p
                try:
                    _inv_mod_p(A, p)
                except ValueError:
                    continue
                if not np.array_equal((A @ dd11) % p, (h1 @ A) % p):
                    continue
                if not np.array_equal((A @ dd21) % p, (h2 @ A) % p):
                    continue
                return A % p
            return None

        # First try the symmetric subspace (A = A^T) by adding explicit linear
        # constraints to the nullspace problem. This avoids relying on luck in
        # the coefficient enumeration.
        sym_rows: list[np.ndarray] = []
        for i in range(6):
            for j in range(i + 1, 6):
                row = np.zeros((36,), dtype=np.int64)
                row[i + 6 * j] = 1
                row[j + 6 * i] = -1
                sym_rows.append(row % p)
        Sym = np.stack(sym_rows, axis=0) % p
        Ksym = np.concatenate([K, Sym], axis=0) % p
        basis_sym = _nullspace_basis_mod_p(Ksym, p)
        A = _search_from_basis(basis_sym)
        if A is not None:
            return A % p

        # Fallback: any invertible intertwiner.
        basis = _nullspace_basis_mod_p(K, p)
        if not basis:
            return None
        A_any = _search_from_basis(basis)
        if A_any is None:
            return None
        if np.array_equal(A_any % p, A_any.T % p):
            return A_any % p
        return A_any % p

    ord_d11 = _order_mod_p(d11, p=p, max_pow=400)
    tr_d11 = int(np.trace(d11) % p)
    if ord_d11 is None:
        raise RuntimeError("failed to determine order(d11) within bound")

    A_best: np.ndarray | None = None
    dual_sign_best: int | None = None

    # Allow a global central sign on the dual generators.
    for sign in (1, 2):
        dd11 = (sign * d11) % p
        dd21 = (sign * d21) % p
        ord_dd11 = _order_mod_p(dd11, p=p, max_pow=400)
        ord_dd21 = _order_mod_p(dd21, p=p, max_pow=400)
        if ord_dd11 is None or ord_dd21 is None:
            continue
        ord_prod = _order_mod_p((dd11 @ dd21) % p, p=p, max_pow=5000)
        if ord_prod is None or int(ord_prod) <= 1:
            continue

        tr_dd11 = int(np.trace(dd11) % p)
        tr_dd21 = int(np.trace(dd21) % p)

        # Candidate targets in H by trace + small-order filters.
        h1_bytes: list[bytes] = []
        h2_bytes: list[bytes] = []
        for b in elems:
            h = (
                np.frombuffer(b, dtype=np.uint8)
                .astype(np.int64, copy=False)
                .reshape((6, 6))
                % p
            )
            tr = int(np.trace(h) % p)
            if tr == tr_dd11 and _has_order(h, int(ord_dd11)):
                h1_bytes.append(b)
            if tr == tr_dd21 and _has_order(h, int(ord_dd21)):
                h2_bytes.append(b)

        rng.shuffle(h1_bytes)
        rng.shuffle(h2_bytes)

        for b1 in h1_bytes:
            h1 = (
                np.frombuffer(b1, dtype=np.uint8)
                .astype(np.int64, copy=False)
                .reshape((6, 6))
                % p
            )
            # For this h1, only consider h2 with ord(h1*h2)=ord(dd11*dd21).
            for b2 in h2_bytes:
                h2 = (
                    np.frombuffer(b2, dtype=np.uint8)
                    .astype(np.int64, copy=False)
                    .reshape((6, 6))
                    % p
                )
                if not _prod_matches_order((h1 @ h2) % p, int(ord_prod)):
                    continue
                A = _find_A_for_targets(dd11=dd11, dd21=dd21, h1=h1, h2=h2)
                if A is None:
                    continue
                # Ensure the conjugated true duals land back in H.
                A_inv = _inv_mod_p(A, p)
                conj11 = (A @ d11 @ A_inv) % p
                conj21 = (A @ d21 @ A_inv) % p
                if _matrix_bytes(conj11, p) not in seen:
                    continue
                if _matrix_bytes(conj21, p) not in seen:
                    continue
                A_best = A % p
                dual_sign_best = int(sign)
                break
            if A_best is not None:
                break
        if A_best is not None:
            break

    if A_best is None or dual_sign_best is None:
        return {"available": False, "reason": "failed to find outer normalizer swap A"}

    A = A_best % p
    dual_sign = int(dual_sign_best)

    # Symplectic embedding (p-axis gauge): E(g)=diag(g, g^{-T}).
    Z6 = np.zeros((6, 6), dtype=np.int64)
    E11 = np.block([[g11, Z6], [Z6, g11_inv.T % p]]) % p
    E21 = np.block([[g21, Z6], [Z6, g21_inv.T % p]]) % p

    # Canonicalize the swap by left-multiplying A with an element of H to make
    # it symmetric. This produces an order-4 "Fourier swap" satisfying X^2=-I,
    # matching the Suz-side witness.
    sym_h: np.ndarray | None = None
    for b in elems:
        h = (
            np.frombuffer(b, dtype=np.uint8)
            .astype(np.int64, copy=False)
            .reshape((6, 6))
            % p
        )
        S = (h @ A) % p
        if np.array_equal(S, S.T % p):
            sym_h = h % p
            A = S % p
            break

    A_inv = _inv_mod_p(A, p)

    # Outer swap: X = [[0,A],[-A^{-T},0]].
    X = np.block([[Z6, A % p], [(-A_inv.T) % p, Z6]]) % p

    from scripts.w33_2suz_m12_2_subgroup import _standard_symplectic_form

    J0 = _standard_symplectic_form(6, p=p)
    assert np.array_equal((X.T @ J0 @ X) % p, J0)

    # Conjugation check on generators: X normalizes the symplectic embedding.
    conj11 = (A @ g11_inv.T @ A_inv) % p
    conj21 = (A @ g21_inv.T @ A_inv) % p
    assert _matrix_bytes(conj11, p) in seen
    assert _matrix_bytes(conj21, p) in seen

    orders: dict[str, Any] = {"base_order": int(base_order)}
    outer: dict[str, Any] = {
        "A_symmetric": bool(np.array_equal(A % p, A.T % p)),
        "A_symmetrizer_in_H": bool(sym_h is not None),
        "X_order": _order_mod_p(X, p=p, max_pow=2000),
        "conjugates_g11_dual_to_H": True,
        "conjugates_g21_dual_to_H": True,
        "dual_sign": int(dual_sign),
    }

    minus_I6 = (2 * np.eye(6, dtype=np.int64)) % p
    minus_I12 = (2 * np.eye(12, dtype=np.int64)) % p
    X2 = (X @ X) % p
    outer["X2_equals_minus_I12"] = bool(np.array_equal(X2, minus_I12))
    outer["X2_pblock_in_H"] = bool(_matrix_bytes(X2[:6, :6], p) in seen)
    outer["minus_I6_in_H"] = bool(_matrix_bytes(minus_I6, p) in seen)
    outer["predicted_full_order"] = 2 * int(base_order)

    # Polarization witness: the commutant of 2.M12 inside End(F3^12) has
    # dimension 2 and contains a non-scalar involution J with 6+6 Lagrangian
    # eigenspaces. The outer element X conjugates J -> -J (Fourier swap).
    from scripts.w33_2suz_m12_2_subgroup import (
        _basis_matrix,
        _commutant_basis,
        _find_involutive_commutant_element,
        _is_scalar_multiple_of_identity,
        _is_totally_isotropic,
        _solve_in_basis,
        _symplectic_inverse,
    )

    I12 = np.eye(12, dtype=np.int64) % p
    x = X % p
    y1 = E11 % p
    y2 = E21 % p

    comm_basis = _commutant_basis([y1, y2], p=p)
    inv = _find_involutive_commutant_element(comm_basis, p=p)

    polarization: dict[str, Any] = {
        "commutant_dim": int(len(comm_basis)),
        "found_involution": bool(inv is not None),
    }
    if inv is not None:
        polarization["involution_is_scalar"] = _is_scalar_multiple_of_identity(inv, p=p)
        polarization["involution_squares_to_I"] = bool(
            np.array_equal((inv @ inv) % p, I12)
        )

        plus_vecs = _nullspace_basis_mod_p((inv - I12) % p, p)
        minus_vecs = _nullspace_basis_mod_p((inv + I12) % p, p)
        U_plus = _basis_matrix(plus_vecs, p=p)
        U_minus = _basis_matrix(minus_vecs, p=p)

        polarization["eigenspace_dims"] = {
            "+1": int(len(plus_vecs)),
            "-1": int(len(minus_vecs)),
        }
        polarization["plus_isotropic"] = _is_totally_isotropic(U_plus, J0, p=p)
        polarization["minus_isotropic"] = _is_totally_isotropic(U_minus, J0, p=p)

        x_inv = _symplectic_inverse(x, J0, p=p)
        inv_conj = (x_inv @ inv @ x) % p
        polarization["x_conjugates_J_to_minus_J"] = bool(
            np.array_equal(inv_conj, (-inv) % p)
        )

        if U_plus.shape == (12, 6) and U_minus.shape == (12, 6):
            A_swap = _solve_in_basis(U_minus, (x @ U_plus) % p, p=p)
            B_swap = _solve_in_basis(U_plus, (x @ U_minus) % p, p=p)
            minus_I = (-np.eye(6, dtype=np.int64)) % p
            polarization["swap_blocks"] = {
                "AB_equals_minus_I": bool(
                    np.array_equal((A_swap @ B_swap) % p, minus_I)
                ),
                "BA_equals_minus_I": bool(
                    np.array_equal((B_swap @ A_swap) % p, minus_I)
                ),
            }

    if compute_full_order:
        from scripts.w33_2suz_m12_2_subgroup import _matrix_group_order

        full = _matrix_group_order([E11, E21, X], p=p, limit=450_000)
        orders["full_order"] = int(full) if full is not None else None

    out: dict[str, Any] = {
        "available": True,
        "field_p": int(p),
        "base_group": {
            "g11_order": _order_mod_p(g11, p=p, max_pow=400),
            "g21_order": _order_mod_p(g21, p=p, max_pow=400),
            "d11_order": int(ord_d11),
            "d11_trace": int(tr_d11),
        },
        "orders": orders,
        "outer": outer,
        "polarization": polarization,
        "elapsed_s": float(time.time() - t0),
    }
    if include_matrices:
        out["matrices_mod3"] = {
            "A": (A % p).astype(int).tolist(),
            "X": (X % p).astype(int).tolist(),
            "E11": (E11 % p).astype(int).tolist(),
            "E21": (E21 % p).astype(int).tolist(),
        }
    return out


def main() -> None:
    rep = analyze(compute_full_order=True)
    if rep.get("available") is not True:
        raise SystemExit(f"Unavailable: {rep}")

    print("=" * 78)
    print("Golay-side OUTER normalizer: 2.M12 -> M12:2 inside Sp(12,3)")
    print("=" * 78)
    print()

    bg = rep["base_group"]
    print("1) Base 2.M12 (Golay p-axis gauge) invariants")
    print("-" * 58)
    print(f"  ord(g11)   = {bg['g11_order']}")
    print(f"  ord(g21)   = {bg['g21_order']}")
    print(f"  ord(d11)   = {bg['d11_order']} (dual)")
    print(f"  tr(d11)    = {bg['d11_trace']} (mod 3)")
    print()

    outer = rep["outer"]
    print("2) Outer swap element X")
    print("-" * 58)
    print(f"  dual sign  = {outer['dual_sign']}")
    print(f"  A symmetric: {outer['A_symmetric']}")
    print(f"  ord(X)     = {outer['X_order']} (expect 4)")
    print(f"  X^2 = -I12:  {outer['X2_equals_minus_I12']}")
    print(f"  -I6 in H:    {outer['minus_I6_in_H']}")
    print()

    pol = rep.get("polarization", {})
    if isinstance(pol, dict) and pol:
        print("3) Polarization witness from commutant of 2.M12")
        print("-" * 58)
        print(f"  commutant dim      = {pol.get('commutant_dim')} (expect 2)")
        print(f"  found involution   = {pol.get('found_involution')}")
        if pol.get("found_involution") is True:
            print(f"  involution scalar  = {pol.get('involution_is_scalar')} (expect False)")
            print(f"  J^2 = I            = {pol.get('involution_squares_to_I')} (expect True)")
            print(f"  eigenspace dims    = {pol.get('eigenspace_dims')} (expect 6+6)")
            print(f"  plus isotropic     = {pol.get('plus_isotropic')} (expect True)")
            print(f"  minus isotropic    = {pol.get('minus_isotropic')} (expect True)")
            print(
                f"  X: J -> -J         = {pol.get('x_conjugates_J_to_minus_J')} (expect True)"
            )
            sb = pol.get("swap_blocks", {})
            if isinstance(sb, dict) and sb:
                print(f"  swap AB=-I         = {sb.get('AB_equals_minus_I')}")
                print(f"  swap BA=-I         = {sb.get('BA_equals_minus_I')}")
        print()

    orders = rep["orders"]
    print("4) Orders")
    print("-" * 58)
    print(f"  |H|         = {orders['base_order']} (expect 190080 = 2.M12)")
    print(f"  predicted   = {outer['predicted_full_order']} (expect 380160 = 2*(2.M12))")
    if orders.get("full_order") is not None:
        print(f"  |<H,X>|     = {orders['full_order']} (expect 380160)")
    print()
    print(f"Elapsed: {rep['elapsed_s']:.2f}s")
    print("ALL CHECKS PASSED ✓")


if __name__ == "__main__":
    main()
