#!/usr/bin/env sage
"""Compute the Weyl subgroup generated by reflections in the 72-root orthogonal complement (candidate E6) and return its order and orbit sizes."""

import json
from pathlib import Path

from sage.all_cmdline import *

data = json.loads(Path("PART_CVII_e6_via_A2.json").read_text())
orth = data[0]["orth_indices"]

E8 = RootSystem(["E", 8])
RL = E8.root_lattice()
roots = list(RL.roots())
# collect orth roots as vectors
orth_roots = [roots[i] for i in north]
# map vector->index
vec_to_idx = {tuple(v): i for i, v in zip(north, orth_roots)}

# define reflection in root alpha: v -> v - 2*(v·alpha)/(alpha·alpha) * alpha
# action on orth roots
perms = []
for alpha in orth_roots[:6]:
    perm = []
    for v in orth_roots:
        w = v - 2 * (v.dot_product(alpha)) / (alpha.dot_product(alpha)) * alpha
        # w should be in orth_roots
        key = tuple(w)
        if key not in vec_to_idx:
            print("Reflection maps outside orth set!")
            break
        perm.append(vec_to_idx[key])
    else:
        perms.append(Permutation(perm))

if not perms:
    print("No permutations built")
    raise SystemExit(1)

PG = PermutationGroup(perms)
order = PG.order()
# compute orbit sizes of the 72 roots under this group
orbits = PG.orbits()
orbit_sizes = [len(o) for o in orbits]

out = {"weyl_subgroup_order": int(order), "orbit_sizes": orbit_sizes}
Path("PART_CVII_e6_weyl_subgroup.json").write_text(json.dumps(out, indent=2))
print("Wrote PART_CVII_e6_weyl_subgroup.json")
print(json.dumps(out, indent=2))
