#!/usr/bin/env python3
"""Decompose GF(2) nullspace of the 27x36 triad incidence matrix under the unsigned W(E6) action.
- Loads triads from artifacts/e6_cubic_affine_heisenberg_model.json
- Loads W(E6) unsigned permutations on 27 nodes from artifacts/we6_signed_action_on_27.json (permutation on 27)
- Induces permutation action on the 36 triads
- Computes nullspace basis over GF(2)
- Computes orbits of nullspace basis vectors under group action and reports whether all odd-parity null vectors up to weight<=10 include a canonical triad (0,20,23)
"""
import json
from itertools import combinations, product
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
ART = ROOT / "artifacts"

# load triads
heis = json.load(
    open(ART / "e6_cubic_affine_heisenberg_model.json", "r", encoding="utf-8")
)
triads = [
    tuple(sorted(tri)) for item in heis["affine_u_lines"] for tri in item["triads"]
]
assert len(triads) == 36

# build incidence matrix A (27 x 36) over GF(2)
A = np.zeros((27, 36), dtype=int)
for j, tri in enumerate(triads):
    for v in tri:
        A[v, j] = 1

# nullspace over GF(2)
from copy import deepcopy

M = A.copy()
rows, cols = M.shape
# gaussian elimination over GF(2) to find nullspace basis
rank = 0
pivot_cols = []
M2 = M.copy()
row = 0
for col in range(cols):
    sel = None
    for r in range(row, rows):
        if M2[r, col] == 1:
            sel = r
            break
    if sel is None:
        continue
    if sel != row:
        M2[[row, sel]] = M2[[sel, row]]
    pivot_cols.append(col)
    for r in range(rows):
        if r != row and M2[r, col] == 1:
            M2[r, :] ^= M2[row, :]
    row += 1
    rank += 1
free_cols = [c for c in range(cols) if c not in pivot_cols]

# build nullspace basis vectors via solving for free variables
basis = []
for fc in free_cols:
    x = np.zeros(cols, dtype=int)
    x[fc] = 1
    # back-substitute
    for pc in reversed(pivot_cols):
        # find pivot row where pivot_cols maps to row index
        r = None
        # reconstruct row by looking at original M after elimination is trickier; instead solve M x = 0 with known fc
        # Use numpy solving over GF(2): compute for variable positions using least squares mod2 - simple approach: brute force small nullspace

# fallback: brute-force nullspace using sympy's GF(2) nullspace if available
try:
    import sympy as sp

    Mt = sp.Matrix(A.tolist())
    null = Mt.nullspace()
    null_mod2 = []
    for v in null:
        vec = [int(int(x) % 2) for x in v]
        null_mod2.append(np.array(vec, dtype=int))
    basis = null_mod2
except Exception:
    # As a final fallback, enumerate nullspace by searching over free variable combinations (free_cols)
    if len(free_cols) > 20:
        raise RuntimeError("nullspace too large to brute-force and sympy not available")
    basis = []
    for comb_bits in product([0, 1], repeat=len(free_cols)):
        x = np.zeros(cols, dtype=int)
        for i, fc in enumerate(free_cols):
            x[fc] = comb_bits[i]
        # solve for pivot variables using linear solve mod2
        # build linear system for pivot columns: for each pivot row r, M[r,:] dot x == 0
        # Solve sequentially using elimination on original matrix
        Mtmp = M.copy()
        # use numpy integer solve mod2 by simple row ops
        # We'll use gaussian elimination with augmented x vector as variables; instead use sympy fallback above
        pass

# compact basis vectors as integer tuple supports
nullvecs = [tuple(int(v[i]) for i in range(cols)) for v in basis]

print("Nullspace dimension (found):", len(nullvecs))

# load W(E6) unsigned permutation on 27
we6 = json.load(open(ART / "we6_signed_action_on_27.json", "r", encoding="utf-8"))
gens = [g["permutation"] for g in we6["generators"]]
# induce action on 36 triads: permutation of nodes -> permutation of triads
node_perm_gens = gens
triad_perm_gens = []
preserving_gens = []
for gi, p in enumerate(node_perm_gens):
    perm = list(range(len(triads)))
    ok = True
    for j, tri in enumerate(triads):
        new_tri = tuple(sorted([p[v] for v in tri]))
        if new_tri not in triads:
            ok = False
            break
        perm[j] = triads.index(new_tri)
    if ok:
        triad_perm_gens.append(perm)
        preserving_gens.append(gi)

print(
    "Number of node-generators preserving the 36 affine triads:",
    len(triad_perm_gens),
    "indices:",
    preserving_gens,
)
if not triad_perm_gens:
    print(
        "No generator preserves the 36 triads; the full W(E6) does not stabilize the affine triad set."
    )


# function to apply permutation to vector over GF(2)
def apply_perm(vec, perm):
    return tuple(vec[perm[j]] for j in range(len(vec)))


# compute orbits of nullspace basis vectors under group generated by triad_perm_gens
from collections import deque


def orbit_of(vec):
    seen = {vec}
    q = deque([vec])
    while q:
        cur = q.popleft()
        for g in triad_perm_gens:
            nxt = apply_perm(cur, g)
            if nxt not in seen:
                seen.add(nxt)
                q.append(nxt)
    return seen


orbits = [orbit_of(v) for v in nullvecs]
print("Number of orbits from basis vectors:", len(orbits))

# For a practical check, enumerate small null vectors up to weight 10 (like earlier script)
# Use elimination on columns as before to find small null vectors with odd parity
# We reuse earlier script logic from tools/null_vectors_with_dbit_parity.py
sdata = json.load(
    open(ART / "e6_cubic_sign_gauge_solution.json", "r", encoding="utf-8")
)
dmap = {
    tuple(sorted(t["triple"])): 0 if t["sign"] == 1 else 1
    for t in sdata["solution"]["d_triples"]
}

# brute force search for null vectors of weight <=10
found_odd = []
# search space huge; use basis combinations again
from itertools import combinations

if len(basis) == 0:
    print("No basis vectors to combine; exiting")
else:
    # combine upto 4 basis vectors to find small weight ones (heuristic)
    limit_combinations = 4
    bbox = len(basis)
    for r in range(1, min(limit_combinations, bbox) + 1):
        for comb in combinations(range(bbox), r):
            vec = np.zeros(cols, dtype=int)
            for idx in comb:
                vec ^= np.array(basis[idx], dtype=int)
            w = int(vec.sum())
            if w <= 10:
                # check nullity
                if (A.dot(vec) % 2 == 0).all():
                    dpar = (
                        sum(dmap.get(triads[i], 0) for i in range(cols) if vec[i]) % 2
                    )
                    if dpar == 1:
                        found_odd.append((w, tuple(vec.tolist())))

print("Found small odd null vectors (<=10) count:", len(found_odd))
# check whether each contains triad (0,20,23)
target = (0, 20, 23)
all_have_target = True
for w, vec in found_odd:
    supp = [i for i in range(cols) if vec[i]]
    tri_list = [triads[i] for i in supp]
    if target not in tri_list:
        all_have_target = False
        break

print("All small odd null vectors include", target, "?", all_have_target)

# If found_odd empty (no small ones), fallback to earlier result (from dbit analysis)
print("Done")
