#!/usr/bin/env python3
"""Enumerate all unordered double-sixes in W33 and compute stabilizer sizes.
Stop and report any stabilizer with orbit size 27 or stabilizer order 1440.
Writes artifacts/w33_double_six_stabilizer_search.json with findings.
"""
from __future__ import annotations

import json
from collections import defaultdict
from itertools import combinations
from pathlib import Path

from tools.find_k6_double_sixes_w33_fast import bron_kerbosch_bounded
from tools.find_schlafli_embedding_in_w33 import compute_w33_lines, construct_w33_points
from tools.w33_aut_group_construct import build_points, generate_group

ROOT = Path(__file__).resolve().parent
ART = ROOT / "artifacts"
ART.mkdir(exist_ok=True)


def image_of_lineset(perm, lineset, lines, line_index):
    """Map a set of line indices through a point permutation `perm`.

    perm: tuple mapping old point index -> new point index
    lineset: iterable of line indices (each line is a tuple of 4 point indices)
    lines: list of line tuples so we can look up point lists by index
    line_index: dict mapping canonical line tuple -> its index
    """
    mapped = set()
    for line_idx in lineset:
        # get the 4 points on this line
        line = lines[line_idx]
        new_line = tuple(sorted(perm[i] for i in line))
        mapped.add(line_index[new_line])
    return mapped


def main():
    # Use the same point ordering as the group generator to avoid index mismatches
    pts = build_points()
    lines = compute_w33_lines(pts)
    n = len(lines)

    # build line index map
    line_index = {tuple(sorted(line)): i for i, line in enumerate(lines)}

    # build G_lines adjacency for BK
    G = {i: set() for i in range(n)}
    for i in range(n):
        for j in range(i + 1, n):
            if set(lines[i]).isdisjoint(set(lines[j])):
                G[i].add(j)
                G[j].add(i)

    # find all K6 cliques
    cliques = []
    bron_kerbosch_bounded(G, set(), set(range(n)), set(), 6, cliques)
    print("K6 cliques found:", len(cliques))

    # compute all unordered disjoint pairs and check matching
    double_sixes = []
    import networkx as nx

    for i in range(len(cliques)):
        a = cliques[i]
        for b in cliques[i + 1 :]:
            if a & b:
                continue
            # bipartite matching
            B = nx.Graph()
            A_nodes = [("A", x) for x in a]
            B_nodes = [("B", y) for y in b]
            B.add_nodes_from(A_nodes)
            B.add_nodes_from(B_nodes)
            for x in a:
                for y in b:
                    if y in G[x]:
                        B.add_edge(("A", x), ("B", y))
            matching = nx.algorithms.bipartite.matching.hopcroft_karp_matching(
                B, top_nodes=A_nodes
            )
            pairs = [(u, v) for u, v in matching.items() if u[0] == "A"]
            if len(pairs) == 6:
                double_sixes.append((tuple(sorted(a)), tuple(sorted(b))))

    print("Unordered double-sixes:", len(double_sixes))

    # build automorphism group (as permutations on 40 points)
    pts_for_group = build_points()
    G_perms, gens = generate_group(pts_for_group)
    G_list = list(G_perms)
    print("Group size:", len(G_list))

    findings = []
    for idx, (A, B) in enumerate(double_sixes):
        if idx % 500 == 0:
            print("Checking double-six", idx, "of", len(double_sixes))
        Aset = set(A)
        Bset = set(B)
        stab_elems = []
        # Precompute canonical tuple forms for A and B (as point-tuples)
        A_tuples = {tuple(sorted(lines[i])) for i in A}
        B_tuples = {tuple(sorted(lines[i])) for i in B}
        # Efficient stabilizer computation: find generators that preserve the unordered pair {A,B}
        perm_gens = gens  # 'gens' are already generator permutations (tuples)
        gens_pres = []
        for gm in perm_gens:
            Ag_tuples = {tuple(sorted(gm[p] for p in lines[i])) for i in A}
            Bg_tuples = {tuple(sorted(gm[p] for p in lines[i])) for i in B}
            if (Ag_tuples == A_tuples and Bg_tuples == B_tuples) or (
                Ag_tuples == B_tuples and Bg_tuples == A_tuples
            ):
                gens_pres.append(gm)

        if not gens_pres:
            order = 1
            closure = {tuple(range(len(pts)))}
        else:
            # close subgroup generated by gens_pres (BFS closure in permutation space)
            identity = tuple(range(len(pts)))
            closure = {identity}
            q = [identity]
            while q:
                h = q.pop()
                for gen in gens_pres:
                    comp = tuple(gen[i] for i in h)
                    if comp not in closure:
                        closure.add(comp)
                        q.append(comp)
            order = len(closure)
        if order >= 2 and (order == 1440 or order >= 100):
            # compute orbits of this stabilizer on lines
            seen = set()
            orbits = []
            for i in range(n):
                if i in seen:
                    continue
                orb = {g[i] for g in stab_elems}
                for x in orb:
                    seen.add(x)
                orbits.append(len(orb))
            findings.append(
                {
                    "A": list(A),
                    "B": list(B),
                    "stab_order": order,
                    "orbits": sorted(orbits),
                }
            )
            if order == 1440 and 27 in orbits:
                print("Found candidate with stabilizer 1440 and orbit 27")
                (ART / "w33_double_six_stabilizer_found.json").write_text(
                    json.dumps(findings[-1], indent=2), encoding="utf-8"
                )
                return
    (ART / "w33_double_six_stabilizer_search.json").write_text(
        json.dumps({"findings": findings}, indent=2), encoding="utf-8"
    )
    print("Done. Findings count:", len(findings))


if __name__ == "__main__":
    main()
