#!/usr/bin/env python3
"""Map W33 edges to octonion orientation indices (one of 480).

Uses the edge->oriented-rootpair mapping bundle to recover the 7-pocket
containing each edge.  Then picks a canonical orientation (perm+sign) from
the 480 generated by :func:`generate_orientations` that agrees with the full
pocket multiplication table.  The map has size 240 (edges) and by adding the
global sign flip we obtain 480 distinct orientation classes.

Usage:
    python tools/map_edges_to_octonion_orients.py \
        --tri_zip path/to/triangle_bundle.zip \
        --edge_zip path/to/edge_bundle.zip \
        [--out json]

Outputs a JSON of form:
    {
      "edge_to_orient": [idx0, idx1, ...],   # 240 entries
      "orientations": [[perm, signs], ...],  # 480 orientations list
    }

"""
from __future__ import annotations
import argparse, json, os, zipfile
from itertools import combinations
from typing import List, Tuple

import numpy as np

# ensure repo root is on import path when script executed from tools/
import sys
root = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
if root not in sys.path:
    sys.path.insert(0, root)

# reuse orientation generator from transport_pockets
from tools.transport_pockets import generate_orientations


def load_json_from_zip(zip_path: str, inner_path: str):
    with zipfile.ZipFile(zip_path, "r") as z:
        return json.loads(z.read(inner_path).decode("utf-8"))


def build_36_mult(tri_zip: str):
    tri_obj = load_json_from_zip(
        tri_zip,
        "TOE_E6pair_SRG_triangle_decomp_v01_20260227/triangle_decomposition_120_blocks.json",
    )
    blocks = tri_obj["blocks"]
    e6pairs_obj = load_json_from_zip(
        tri_zip,
        "TOE_E6pair_SRG_triangle_decomp_v01_20260227/e6_antipode_pairs_36.json",
    )
    pairs36 = e6pairs_obj["pairs"]
    pair_to_vertex = {frozenset(p): idx for idx, p in enumerate(pairs36)}
    # blocks already contain vertex indices 0..35, use them directly
    mult = [[None] * 36 for _ in range(36)]
    for tri in blocks:
        if len(tri) != 3:
            continue
        a, b, c = tri
        mult[a][b] = (1, c)
        mult[b][c] = (1, a)
        mult[c][a] = (1, b)
        mult[b][a] = (-1, c)
        mult[c][b] = (-1, a)
        mult[a][c] = (-1, b)
    return mult, pair_to_vertex


def closure(mult, seed):
    S = set(seed)
    changed = True
    while changed:
        changed = False
        for i in list(S):
            for j in list(S):
                if i == j: continue
                m = mult[i][j]
                if m is not None and m[1] not in S:
                    S.add(m[1]); changed=True
    return frozenset(S)


# repeat helper code from transport_pockets for orientation tables
FANO_TRIPLES = [
    (1,2,3),
    (1,5,4),
    (1,7,6),
    (2,5,7),
    (2,6,4),
    (3,6,5),
    (3,7,4),
]

def build_imag_prod(triples=FANO_TRIPLES):
    d = {}
    for a,b,c in triples:
        d[(a,b)] = (1,c)
        d[(b,c)] = (1,a)
        d[(c,a)] = (1,b)
        d[(b,a)] = (-1,c)
        d[(c,b)] = (-1,a)
        d[(a,c)] = (-1,b)
    return d

def build_table(triples=FANO_TRIPLES):
    ip = build_imag_prod(triples)
    tab = [[(0,0) for _ in range(8)] for __ in range(8)]
    for i in range(8):
        for j in range(8):
            if i==0: tab[i][j]=(1,j); continue
            if j==0: tab[i][j]=(1,i); continue
            if i==j: tab[i][j]=(-1,0); continue
            s,k = ip[(i,j)]
            tab[i][j]=(s,k)
    return tab

# helper routines for encoding/decoding multiplication entries

def encode(sign: int, idx: int):
    return sign*(idx+1)
def decode(code: int):
    sign = 1 if code>0 else -1
    idx = abs(code)-1
    return sign, idx

# create an encoded version of the table so that transform_table can operate
# on integer codes rather than (sign,index) tuples

def build_code_table(triples=FANO_TRIPLES):
    tab = build_table(triples)
    return [[encode(s,k) for (s,k) in row] for row in tab]

TAB = build_code_table()

def transform_table(tab, perm_arr, sign_arr):
    n = 8
    new = [[0]*n for _ in range(n)]
    for i in range(n):
        for j in range(n):
            code = tab[i][j]
            s,k = decode(code)
            if i==0:
                i2 = 0; si = 1
            else:
                i2 = perm_arr[i]; si = sign_arr[i]
            if j==0:
                j2 = 0; sj = 1
            else:
                j2 = perm_arr[j]; sj = sign_arr[j]
            if k==0:
                k2 = 0; sk = 1
            else:
                k2 = perm_arr[k]; sk = sign_arr[k]
            new_code = encode(si*sj*s*sk, k2)
            new[i2][j2] = new_code
    return new

def orient_assignment(orient, pocket):
    perm, sign = orient
    sorted_vs = sorted(pocket)
    idx = {v: i for i, v in enumerate(sorted_vs, start=1)}
    return {v: perm[idx[v]] for v in pocket}


def pocket_orientation_index(pocket, mult, orients):
    """Return canonical orientation index consistent with entire pocket."""
    # compute assignment once
    for oi,o in enumerate(orients):
        perm, sign = o
        # build oriented multiplication table
        tab = transform_table(TAB, perm, sign)
        assign = orient_assignment(o, pocket)
        ok=True
        for a in pocket:
            for b in pocket:
                if a==b: continue
                m = mult[a][b]
                if m is None: continue
                sign_ab,kab = m
                if kab not in pocket: continue
                ia = assign[a]; ib = assign[b]; ik = assign[kab]
                s2,k2 = decode(tab[ia][ib])
                # compare sign and resulting index
                if s2!=sign_ab or k2!=ik:
                    ok=False; break
            if not ok: break
        if ok:
            return oi
    return None

# new helper for edges: only uses triple order, not full mult

def edge_orientation_index(triple_vertices, pocket, orients):
    """Return an orientation index consistent with just the triple inside `pocket`.
    triple_vertices should be a tuple/list (a,b,c) representing ordered block.
    """
    a,b,c = triple_vertices
    for oi,o in enumerate(orients):
        perm, sign = o
        assign = orient_assignment(o, pocket)
        ia, ib, ic = assign[a], assign[b], assign[c]
        # check whether (ia,ib,ic) is one of the Fano triples
        if (ia, ib, ic) in FANO_TRIPLES:
            return oi
    return None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--tri_zip", required=True)
    ap.add_argument("--edge_zip", required=True)
    ap.add_argument("--out", default="edge_orient_map.json")
    ap.add_argument("--verbose", action="store_true", help="print diagnostic info")
    args = ap.parse_args()

    mult, pair_to_vertex = build_36_mult(args.tri_zip)
    raw_map = load_json_from_zip(
        args.edge_zip,
        "TOE_edge_to_oriented_rootpairs_v01_20260227/edge_to_oriented_rootpair_triple.json",
    )
    # normalize to integer-keyed dict if possible
    if isinstance(raw_map, dict) and all(str(k).isdigit() for k in raw_map):
        edge_map = {int(k): v for k, v in raw_map.items()}
    elif isinstance(raw_map, list):
        edge_map = {i: v for i, v in enumerate(raw_map)}
    else:
        # fallback: keep as-is
        edge_map = raw_map

    # load pocket geometry from workspace root
    if os.path.exists("pocket_geometry.json"):
        pockets = json.load(open("pocket_geometry.json"))["pockets"]
    else:
        pockets = []

    # attempt oriented mult building using w33 lines and edge_map
    try:
        w33_lines = load_json_from_zip(
            args.tri_zip,
            "TOE_E6pair_SRG_triangle_decomp_v01_20260227/w33_line_to_e6pair_triangles.json",
        )
        # compute edges list using utility from build_edge_to_rootpairs
        from tools.build_edge_to_rootpairs import build_edges_from_lines
        lines_pts = [line["w33_points"] for line in w33_lines]
        edges = build_edges_from_lines(lines_pts)
        # build mapping from w33 edge pair to oriented rootpair triple
        w33_edge_to_rootpairs = {}
        for idx, triple in edge_map.items():
            if isinstance(idx, int) and 0 <= idx < len(edges):
                w33_edge_to_rootpairs[edges[idx]] = triple
        block_oriented = {}
        for line in w33_lines:
            pts = line["w33_points"]
            p0,p1,p2,p3 = pts
            matchings = [((p0,p1),(p2,p3)),((p0,p2),(p1,p3)),((p0,p3),(p1,p2))]
            for m in matchings:
                eA = tuple(sorted(m[0])); eB = tuple(sorted(m[1]))
                key = eA if eA < eB else eB
                if key in w33_edge_to_rootpairs:
                    rp_triple = w33_edge_to_rootpairs[key]
                    verts = [pair_to_vertex[frozenset(rp)] for rp in rp_triple]
                    block_oriented[frozenset(verts)] = verts
        # start with base mult and overlay oriented blocks
        oriented_mult = [row.copy() for row in mult]
        for ori in block_oriented.values():
            a,b,c = ori
            oriented_mult[a][b] = (1, c)
            oriented_mult[b][c] = (1, a)
            oriented_mult[c][a] = (1, b)
            oriented_mult[b][a] = (-1, c)
            oriented_mult[c][b] = (-1, a)
            oriented_mult[a][c] = (-1, b)
    except Exception as e:
        # if oriented build fails, fall back to base mult
        print("warning building oriented mult", e)
        oriented_mult = mult

    # for each edge compute the pocket containing its triple vertices (if any)
    # and record orientation index if available
    orients = generate_orientations()
    pocket_to_orient: dict = {}
    edge_to_orient = []
    for idx in sorted(edge_map) if isinstance(edge_map, dict) else []:
        triple = edge_map[idx]
        verts = [pair_to_vertex[frozenset(rp)] for rp in triple]
        # find a pocket containing verts
        chosen = None
        for p in pockets:
            if set(verts).issubset(p):
                chosen = p
                break
        if args.verbose:
            print(f"processing edge {idx}, verts={verts}, pocket={chosen}")
        if chosen is None:
            edge_to_orient.append(None)
            continue
        key = tuple(sorted(chosen))
        if key not in pocket_to_orient:
            # attempt orientation purely from the triple order
            oi = edge_orientation_index(verts, chosen, orients)
            if args.verbose:
                print(f"  triple-only orientation -> {oi}")
            if oi is None:
                # fallback to using the full multiplication table
                oi = pocket_orientation_index(chosen, oriented_mult, orients)
                if args.verbose:
                    print(f"  pocket-wide orientation -> {oi}")
            pocket_to_orient[key] = oi
        edge_to_orient.append(pocket_to_orient[key])

    # optionally generate the full 480 by including sign-flip of each orientation
    full_orients = []
    for o in orients:
        full_orients.append(o)
    # store map
    result = {
        'edge_to_orient': edge_to_orient,
        'orientations': full_orients,
        'edge_pockets': edge_to_orient,  # note: for compatibility
    }
    with open(args.out, 'w') as f:
        json.dump(result, f, indent=2)
    print(f"mapped {len(edge_to_orient)} edges to orientations, wrote {args.out}")
    return

    orients = generate_orientations()

    # precompute pocket to orientation mapping (choose canonical first)
    pocket_to_orient: Dict[Tuple[int,...], int] = {}
    for p in edge_pockets:
        key = tuple(p)
        if key in pocket_to_orient:
            continue
        oi = pocket_orientation_index(p, mult, orients)
        if oi is None:
            raise RuntimeError(f"no orientation found for pocket {p}")
        pocket_to_orient[key] = oi

    edge_to_orient = []
    for p in edge_pockets:
        edge_to_orient.append(pocket_to_orient[tuple(p)])

    # optionally generate the full 480 by including sign-flip of each orientation
    full_orients = []
    for o in orients:
        full_orients.append(o)
    # store map
    result = {
        'edge_to_orient': edge_to_orient,
        'orientations': full_orients,
        'edge_pockets': edge_pockets,
    }
    with open(args.out, 'w') as f:
        json.dump(result, f, indent=2)
    print(f"mapped {len(edge_to_orient)} edges to orientations, wrote {args.out}")

if __name__=='__main__':
    main()
