#!/usr/bin/env python3
"""Simple MeatAxe-style decomposition over GF(3).

Input JSON should contain a list or dict of matrices under key "matrices"; each
matrix is a list-of-lists of integers.  All matrices must be square of the same
size and entries are reduced mod 3.

The script will compute a decomposition of the module into irreducible
submodules and output a JSON file listing the dimensions of each factor and
(optionally) change-of-basis matrices.

Uses a brute-force orbit algorithm suitable for small dimensions (<= 20).
"""
from __future__ import annotations

import json
import random
from pathlib import Path
from typing import List, Tuple

import numpy as np

ROOT = Path(__file__).resolve().parents[1]


def load_matrices(path: Path) -> List[np.ndarray]:
    data = json.loads(path.read_text())
    mats = data.get("matrices", data)
    if isinstance(mats, dict):
        mats = [np.array(m, dtype=int) for k,m in sorted(mats.items(), key=lambda kv:int(kv[0]))]
    else:
        mats = [np.array(m, dtype=int) for m in mats]
    # reduce mod3
    for i in range(len(mats)):
        mats[i] = mats[i] % 3
    return mats


def orbit_subspace(mats: List[np.ndarray], seed: np.ndarray) -> np.ndarray:
    """Return a basis for the subspace generated by the orbit of seed."""
    m = seed.shape[0]
    # use list of vectors encoded as tuple for uniqueness
    span = {tuple(seed % 3)}
    changed = True
    while changed:
        changed = False
        for M in mats:
            for v in list(span):  # iterate over snapshot
                w = M.dot(np.array(v)) % 3
                wt = tuple(w.tolist())
                if wt not in span:
                    span.add(wt)
                    changed = True
    # convert span to numpy array (columns are vectors)
    mat = np.array(list(span), dtype=int).T  # shape (m, k)
    # perform simple Gaussian elimination mod 3 to find independent columns
    basis_cols = []
    for col in range(mat.shape[1]):
        v = mat[:, col].copy()
        # reduce by existing basis columns
        for b in basis_cols:
            # find leading entry of b
            leads = np.nonzero(b)[0]
            if len(leads) == 0:
                continue
            lead = leads[0]
            if v[lead] != 0:
                inv = pow(int(b[lead]), -1, 3)
                v = (v - b * v[lead] * inv) % 3
        if np.any(v):
            # normalize leading 1
            lead = np.nonzero(v)[0][0]
            inv = pow(int(v[lead]), -1, 3)
            v = (v * inv) % 3
            basis_cols.append(v)
    if not basis_cols:
        return np.zeros((m,0),dtype=int)
    B = np.column_stack(basis_cols) % 3
    return B


def solve_mod3(A: np.ndarray, b: np.ndarray) -> np.ndarray:
    """Solve A x = b over GF(3); raise ValueError if no solution."""
    A = A.copy() % 3
    b = b.copy() % 3
    m,n = A.shape
    # augmented matrix
    M = np.hstack((A, b.reshape(-1,1))).astype(int)
    row = 0
    for col in range(n):
        if row >= m:
            break
        # find pivot with nonzero in this col
        pivot = None
        for r in range(row, m):
            if M[r,col] % 3 != 0:
                pivot = r
                break
        if pivot is None:
            continue
        # swap rows
        if pivot != row:
            M[[pivot,row]] = M[[row,pivot]]
        inv = pow(int(M[row,col]), -1, 3)
        M[row] = (M[row] * inv) % 3
        # eliminate other rows
        for r in range(m):
            if r != row and M[r,col] != 0:
                M[r] = (M[r] - M[r,col] * M[row]) % 3
        row += 1
    # check for inconsistency
    for r in range(row, m):
        if M[r, :-1].sum() % 3 == 0 and M[r, -1] != 0:
            raise ValueError("no solution")
    # extract solution (assuming free vars zero)
    x = np.zeros(n, dtype=int)
    for r in range(row):
        lead = np.nonzero(M[r, :-1])[0]
        if lead.size > 0:
            x[lead[0]] = M[r, -1] % 3
    return x


def find_invariant(mats: List[np.ndarray], dim_target: int) -> np.ndarray:
    m = mats[0].shape[0]
    for trial in range(500):
        V = np.random.randint(0,3,size=(m,dim_target))
        if np.linalg.matrix_rank(V.astype(float)) < dim_target:
            continue
        # check invariance
        good = True
        for M in mats:
            MV = (M @ V) % 3
            # for each column of MV solve V x = MV_col
            for col in range(dim_target):
                try:
                    _ = solve_mod3(V, MV[:, col])
                except ValueError:
                    good = False
                    break
            if not good:
                break
        if good:
            return V
    return None


def decompose(mats: List[np.ndarray]) -> List[int]:
    # seed numpy/random for reproducibility (important for tests)
    np.random.seed(0)
    random.seed(0)
    dims: List[int] = []
    current = mats
    m = current[0].shape[0]
    while m > 0:
        found = False
        # try larger submodules first for more balanced decomposition
        for d in range(m//2, 0, -1):
            V = find_invariant(current, d)
            if V is not None:
                dims.append(d)
                # construct a complement basis C so that [V|C] is an invertible m×m matrix
                def find_complement(V):
                    mV, dV = V.shape
                    Ccols = []
                    # try random vectors first for diversity
                    for _ in range(1000):
                        if len(Ccols) == mV - dV:
                            break
                        v = np.random.randint(0, 3, size=(mV,))
                        Mtest = np.column_stack([V] + Ccols + [v])
                        if np.linalg.matrix_rank(Mtest.astype(float)) > dV + len(Ccols):
                            Ccols.append(v)
                    # fall back to standard basis if needed
                    for i in range(mV):
                        if len(Ccols) == mV - dV:
                            break
                        e = np.zeros(mV, dtype=int)
                        e[i] = 1
                        Mtest = np.column_stack([V] + Ccols + [e])
                        if np.linalg.matrix_rank(Mtest.astype(float)) > dV + len(Ccols):
                            Ccols.append(e)
                    if len(Ccols) != mV - dV:
                        raise RuntimeError("could not find complement basis")
                    return np.column_stack(Ccols)

                C = find_complement(V)
                # build change-of-basis matrix P and use it to restrict
                P = np.hstack((V, C)) % 3
                if np.linalg.matrix_rank(P.astype(float)) != m:
                    raise RuntimeError("basis for full space is not invertible")
                new_mats = []
                for M in current:
                    k = C.shape[1]
                    N = np.zeros((k, k), dtype=int)
                    for j in range(k):
                        b = (M @ C[:, j]) % 3
                        coeff = solve_mod3(P, b)
                        N[:, j] = coeff[d:]
                    new_mats.append(N)
                current = new_mats
                m = current[0].shape[0]
                found = True
                break
        if not found:
            # remainder is irreducible
            dims.append(m)
            break
    return dims


def main():
    import argparse
    parser = argparse.ArgumentParser(description="MeatAxe decomposition over GF3")
    parser.add_argument("--input", help="JSON file with matrices", required=True)
    parser.add_argument("--output", help="JSON output path", default=str(ROOT/"artifacts"/"meataxe_decomp.json"))
    args = parser.parse_args()

    mats = load_matrices(Path(args.input))
    dims = decompose(mats)
    out = {"dims": dims}
    Path(args.output).write_text(json.dumps(out, indent=2))
    print("wrote", args.output, "dims", dims)

if __name__ == "__main__":
    main()
