#!/usr/bin/env python3
"""Sage: intersection of W(E6) orbits with Coxeter 6-cycles in E8.

Computes:
- W(E6) orbits on E8 roots (sizes 72, 6x27, 6x1)
- Coxeter element c in W(E8), its power c^5 (order 6)
- 40 orbits of size 6 under <c^5>
- Intersection matrix counts: 40x13
- Histogram of intersection patterns for the 40 orbits
"""

from __future__ import annotations

import json
from collections import Counter, deque

from sage.all import RootSystem, WeylGroup


def act(g, v):
    try:
        return g.action(v)
    except Exception:
        try:
            return g * v
        except Exception:
            return g.matrix() * v


def orbit(generators, start):
    seen = {start}
    q = deque([start])
    while q:
        x = q.popleft()
        for g in generators:
            y = act(g, x)
            if y not in seen:
                seen.add(y)
                q.append(y)
    return seen


def root_key(v):
    vec = list(v.to_vector())
    return tuple(int(2 * x) for x in vec)


def main():
    R8 = RootSystem(["E", 8]).ambient_space()
    roots = list(R8.roots())

    W8 = WeylGroup(["E", 8])
    s = W8.simple_reflections()

    # W(E6) parabolic subgroup generated by s1..s6
    gens_we6 = [s[i] for i in [1, 2, 3, 4, 5, 6]]
    WE6 = W8.subgroup(gens_we6)

    # W(E6) orbits
    remaining = set(roots)
    we6_orbits = []
    while remaining:
        r = next(iter(remaining))
        orb = orbit(gens_we6, r)
        we6_orbits.append(orb)
        remaining -= orb
    we6_orbits = sorted(we6_orbits, key=lambda o: (-len(o), root_key(next(iter(o)))))

    # Coxeter element c = s1*s2*...*s8
    c = s[1]
    for i in range(2, 9):
        c = c * s[i]
    c5 = c**5  # order 6

    # Orbits under <c5>
    remaining = set(roots)
    c6_orbits = []
    while remaining:
        r = next(iter(remaining))
        orb = {r}
        cur = r
        for _ in range(5):
            cur = act(c5, cur)
            orb.add(cur)
        c6_orbits.append(orb)
        remaining -= orb

    # Intersection matrix: 40 x 13
    matrix = []
    patterns = []
    for o6 in c6_orbits:
        row = [len(o6 & ow) for ow in we6_orbits]
        matrix.append(row)
        patterns.append(tuple(row))

    pattern_counts = Counter(patterns)

    # Summaries
    sizes_we6 = [len(o) for o in we6_orbits]
    sizes_c6 = sorted([len(o) for o in c6_orbits], reverse=True)

    out = {
        "we6_orbit_sizes": sizes_we6,
        "coxeter6_orbit_sizes": sizes_c6,
        "intersection_patterns": {str(k): v for k, v in pattern_counts.items()},
        "matrix": matrix,
    }

    with open("artifacts/we6_coxeter6_intersection.json", "w", encoding="utf-8") as f:
        json.dump(out, f, indent=2, default=str)

    print("Wrote artifacts/we6_coxeter6_intersection.json")
    print(f"W(E6) orbit sizes: {sizes_we6}")
    print(f"Coxeter6 orbits: {len(c6_orbits)} of size {sizes_c6[0]}")
    print("Pattern counts:")
    for k, v in pattern_counts.most_common(10):
        print(f"  {k}: {v}")


if __name__ == "__main__":
    main()
