#!/usr/bin/env sage
"""
Minimal SageMath verification of the "spine" facts used throughout the repo:

  - |Sp(4,3)| = 51840
  - |W(E6)| = 51840 and E6 has 72 roots
  - W33 = SymplecticPolarGraph(4,3) is SRG(40,12,2,4) with 240 edges
  - |Aut(W33)| = 51840 (exact, Sage)
  - E8 has 240 roots and |W(E8)| = 696729600

Run (Docker fallback supported):
  SAGE_DOCKER_IMAGE=sagemath/sagemath:latest ./run_sage.sh tools/sage_verify_w33_sp4_we6.sage

Outputs:
  - artifacts/sage_verify_w33_sp4_we6.json
  - artifacts/sage_verify_w33_sp4_we6.md
"""

from __future__ import annotations

# This file was *autogenerated* from the file tools/sage_verify_w33_sp4_we6.sage
from sage.all_cmdline import *  # import sage library

_sage_const_3 = Integer(3)
_sage_const_4 = Integer(4)
_sage_const_6 = Integer(6)
_sage_const_0 = Integer(0)
_sage_const_1 = Integer(1)
_sage_const_8 = Integer(8)
_sage_const_51840 = Integer(51840)
_sage_const_72 = Integer(72)
_sage_const_40 = Integer(40)
_sage_const_240 = Integer(240)
_sage_const_696729600 = Integer(696729600)
_sage_const_2 = Integer(2)


import json
from pathlib import Path

from sage.all import GF, RootSystem, Sp, factor, graphs  # type: ignore

ROOT = Path(".").resolve()
OUT_JSON = ROOT / "artifacts" / "sage_verify_w33_sp4_we6.json"
OUT_MD = ROOT / "artifacts" / "sage_verify_w33_sp4_we6.md"


def _json_default(o):
    try:
        return int(o)
    except Exception:
        return str(o)


def main() -> None:
    results = {}

    F3 = GF(_sage_const_3)
    sp4 = Sp(_sage_const_4, F3)
    results["sp4_f3_order"] = int(sp4.order())
    results["sp4_f3_factor"] = str(factor(sp4.order()))

    e6 = RootSystem(["E", _sage_const_6])
    e6_roots = list(e6.root_lattice().roots())
    we6 = e6.root_lattice().weyl_group()
    results["e6_rank"] = int(e6.root_lattice().rank())
    results["e6_roots"] = int(len(e6_roots))
    results["we6_order"] = int(we6.order())
    results["we6_factor"] = str(factor(we6.order()))

    w33 = graphs.SymplecticPolarGraph(_sage_const_4, _sage_const_3)
    results["w33_vertices"] = int(w33.order())
    results["w33_edges"] = int(w33.size())
    results["w33_connected"] = bool(w33.is_connected())
    results["w33_is_srg"] = bool(w33.is_strongly_regular())
    if results["w33_is_srg"]:
        results["w33_srg_params"] = tuple(
            int(x) for x in w33.is_strongly_regular(parameters=True)
        )

    # Eigenvalues (exact rationals / integers)
    evs = w33.adjacency_matrix().eigenvalues()
    # Convert to string counts to avoid Sage type serialization surprises
    counts = {}
    for e in evs:
        k = str(e)
        counts[k] = counts.get(k, _sage_const_0) + _sage_const_1
    results["w33_eigenvalue_multiset"] = counts

    # Aut(W33) order (this is the expensive bit, but still feasible for 40 vertices)
    aut = w33.automorphism_group()
    results["aut_w33_order"] = int(aut.order())
    results["aut_w33_factor"] = str(factor(aut.order()))

    e8 = RootSystem(["E", _sage_const_8])
    e8_roots = list(e8.root_lattice().roots())
    we8 = e8.root_lattice().weyl_group()
    results["e8_rank"] = int(e8.root_lattice().rank())
    results["e8_roots"] = int(len(e8_roots))
    results["we8_order"] = int(we8.order())
    results["we8_factor"] = str(factor(we8.order()))

    # Key equalities used in the project narrative
    results["checks"] = {
        "sp4_eq_we6": results["sp4_f3_order"] == results["we6_order"],
        "sp4_eq_aut_w33": results["sp4_f3_order"] == results["aut_w33_order"],
        "w33_edges_eq_e8_roots": results["w33_edges"] == results["e8_roots"],
    }

    ok = (
        results["sp4_f3_order"] == _sage_const_51840
        and results["we6_order"] == _sage_const_51840
        and results["e6_roots"] == _sage_const_72
        and results["w33_vertices"] == _sage_const_40
        and results["w33_edges"] == _sage_const_240
        and results["w33_is_srg"]
        and results["aut_w33_order"] == _sage_const_51840
        and results["e8_roots"] == _sage_const_240
        and results["we8_order"] == _sage_const_696729600
        and all(results["checks"].values())
    )

    results["status"] = "ok" if ok else "fail"

    OUT_JSON.write_text(
        json.dumps(results, indent=_sage_const_2, sort_keys=True, default=_json_default)
        + "\n",
        encoding="utf-8",
    )

    md = []
    md.append("# Sage verify: W33 / Sp(4,3) / W(E6)\n")
    md.append(f"- status: `{results['status']}`")
    md.append(f"- |Sp(4,3)|: `{results['sp4_f3_order']}` ({results['sp4_f3_factor']})")
    md.append(
        f"- |W(E6)|: `{results['we6_order']}` ({results['we6_factor']}); roots: `{results['e6_roots']}`"
    )
    md.append(
        f"- W33: vertices `{results['w33_vertices']}`, edges `{results['w33_edges']}`, SRG `{results['w33_srg_params']}`"
    )
    md.append(
        f"- |Aut(W33)|: `{results['aut_w33_order']}` ({results['aut_w33_factor']})"
    )
    md.append(
        f"- E8: roots `{results['e8_roots']}`; |W(E8)| `{results['we8_order']}` ({results['we8_factor']})\n"
    )
    md.append("## Checks\n")
    for k, v in results["checks"].items():
        md.append(f"- {k}: `{v}`")
    md.append(f"\n- JSON: `{OUT_JSON.as_posix()}`")
    OUT_MD.write_text("\n".join(md).rstrip() + "\n", encoding="utf-8")

    print(
        json.dumps(results, indent=_sage_const_2, sort_keys=True, default=_json_default)
    )
    if not ok:
        raise SystemExit(_sage_const_1)


if __name__ == "__main__":
    main()
