#!/usr/bin/env python3
"""Sage: compute normalizer of the Coxeter-6 element c^5 in W(E8)."""

from __future__ import annotations

import json
from pathlib import Path

from sage.all import RootSystem

ROOT = Path(__file__).resolve().parents[1]


def main():
    R = RootSystem(["E", 8]).root_lattice()
    W = R.weyl_group()

    # Coxeter element c = s1 s2 ... s8
    c = W.simple_reflection(1)
    for i in range(2, 9):
        c = c * W.simple_reflection(i)
    c5 = c**5

    # subgroup generated by c5
    H = W.subgroup([c5])
    N = W.normalizer(H)

    out = {
        "W_order": int(W.order()),
        "c5_order": int(c5.order()),
        "H_order": int(H.order()),
        "N_order": int(N.order()),
        "index_of_N": int(W.order() // N.order()),
    }

    out_path = ROOT / "artifacts" / "e8_c5_normalizer.json"
    out_path.write_text(json.dumps(out, indent=2), encoding="utf-8")
    print(out)
    print("Wrote", out_path)


if __name__ == "__main__":
    main()
