#!/usr/bin/env sage
"""
Compute automorphism groups of:
  (A) the full 45 E6 cubic triads on 27 labels, and
  (B) the firewall-effective triads (45 minus the 9 forbidden).

We model each 3-uniform hypergraph as a bipartite incidence graph:
  - left vertices: 27 "line" labels (0..26)
  - right vertices: one vertex per triad, connected to its 3 labels

Then compute the graph automorphism group (restricted to the left partition).

Outputs:
  - artifacts/sage_aut_group_of_firewall_effective_triads.json
"""


# This file was *autogenerated* from the file tools/sage_aut_group_of_firewall_effective_triads.sage
from sage.all_cmdline import *  # import sage library

_sage_const_1 = Integer(1)
_sage_const_27 = Integer(27)
_sage_const_0 = Integer(0)
_sage_const_45 = Integer(45)
_sage_const_9 = Integer(9)
_sage_const_36 = Integer(36)
_sage_const_2 = Integer(2)
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[_sage_const_1]
OUT = ROOT / "artifacts" / "sage_aut_group_of_firewall_effective_triads.json"


def triad_key(t):
    a, b, c = (int(x) for x in t)
    return tuple(sorted((a, b, c)))


def build_incidence_graph(triads):
    # Bipartite incidence graph, with explicit partition to avoid any accidental swaps.
    V = [("v", i) for i in range(_sage_const_27)]
    T = [("t", k) for k in range(len(triads))]
    G = Graph()
    G.add_vertices(V)
    G.add_vertices(T)
    for k, (a, b, c) in enumerate(triads):
        tk = ("t", k)
        G.add_edge(("v", int(a)), tk)
        G.add_edge(("v", int(b)), tk)
        G.add_edge(("v", int(c)), tk)
    return G, V, T


def induced_action_on_V(aut, V):
    # aut is a permutation group acting on graph vertices; restrict to V-part.
    # Represent as a permutation group on 27 points.
    # Sage's automorphism_group(partition=...) acts on the graph's vertex set,
    # so we compute images of ("v",i) and read off i.
    gens = []
    for g in aut.gens():
        perm = []
        for i in range(_sage_const_27):
            img = g(("v", i))
            if img[_sage_const_0] != "v":
                raise RuntimeError("Partition-violating automorphism (unexpected)")
            perm.append(
                int(img[_sage_const_1]) + _sage_const_1
            )  # 1-based for PermutationGroup
        gens.append(Permutation(perm))
    return PermutationGroup(gens)


def main():
    canon = json.loads(
        (ROOT / "artifacts" / "canonical_su3_gauge_and_cubic.json").read_text(
            encoding="utf-8"
        )
    )
    triads_45 = sorted({triad_key(t["triple"]) for t in canon["solution"]["d_triples"]})
    if len(triads_45) != _sage_const_45:
        raise RuntimeError("Expected 45 cubic triads")

    fw = json.loads(
        (ROOT / "artifacts" / "firewall_bad_triads_mapping.json").read_text(
            encoding="utf-8"
        )
    )
    bad_9 = sorted({triad_key(t) for t in fw["bad_triangles_Schlafli_e6id"]})
    if len(bad_9) != _sage_const_9:
        raise RuntimeError("Expected 9 firewall triads")

    triads_eff = sorted(set(triads_45) - set(bad_9))
    if len(triads_eff) != _sage_const_36:
        raise RuntimeError("Expected 36 effective triads")

    # Full triads
    G45, V45, T45 = build_incidence_graph(triads_45)
    aut45 = G45.automorphism_group(partition=[V45, T45])
    aut45_V = induced_action_on_V(aut45, V45)

    # Effective triads
    G36, V36, T36 = build_incidence_graph(triads_eff)
    aut36 = G36.automorphism_group(partition=[V36, T36])
    aut36_V = induced_action_on_V(aut36, V36)

    # Basic permutation action invariants.
    trans45 = bool(aut45_V.is_transitive())
    trans36 = bool(aut36_V.is_transitive())
    stab45 = int(aut45_V.stabilizer(_sage_const_1).order())  # point "1" (1-based)
    stab36 = int(aut36_V.stabilizer(_sage_const_1).order())
    stab45_desc = str(aut45_V.stabilizer(_sage_const_1).structure_description())
    stab36_desc = str(aut36_V.stabilizer(_sage_const_1).structure_description())

    # Look for a normal subgroup of order 27 (translation-like) in the effective group.
    normal27 = None
    for N in aut36_V.normal_subgroups():
        if int(N.order()) == _sage_const_27:
            normal27 = N
            break

    # Orbits on triads (treat triads as 3-subsets of {1..27}).
    tri45_1based = [tuple(int(x) + _sage_const_1 for x in t) for t in triads_45]
    tri36_1based = [tuple(int(x) + _sage_const_1 for x in t) for t in triads_eff]

    def orbit_sizes_on_triads(G, triads_1based):
        remaining = set(tuple(sorted(t)) for t in triads_1based)
        orbs = []
        while remaining:
            t0 = next(iter(remaining))
            orb = set()
            for g in G:
                img = tuple(sorted(g(i) for i in t0))
                if img in remaining:
                    orb.add(img)
            remaining -= orb
            orbs.append(len(orb))
        return sorted(orbs, reverse=True)

    orb45 = orbit_sizes_on_triads(aut45_V, tri45_1based)
    orb36 = orbit_sizes_on_triads(aut36_V, tri36_1based)

    out = {
        "status": "ok",
        "counts": {
            "triads_45": len(triads_45),
            "triads_bad_9": len(bad_9),
            "triads_effective_36": len(triads_eff),
        },
        "orders": {
            "aut_full_triads_on_27": int(aut45_V.order()),
            "aut_effective_triads_on_27": int(aut36_V.order()),
            "stab_full_triads_point1": stab45,
            "stab_effective_triads_point1": stab36,
        },
        "structure": {
            "aut_full_triads_on_27": str(aut45_V.structure_description()),
            "aut_effective_triads_on_27": str(aut36_V.structure_description()),
            "stab_full_triads_point1": stab45_desc,
            "stab_effective_triads_point1": stab36_desc,
        },
        "action": {
            "full_triads_transitive": trans45,
            "effective_triads_transitive": trans36,
            "full_triads_orbit_sizes_on_45": orb45,
            "effective_triads_orbit_sizes_on_36": orb36,
        },
        "normal_subgroup_27": (
            None
            if normal27 is None
            else {
                "order": int(normal27.order()),
                "structure": str(normal27.structure_description()),
                "is_abelian": bool(normal27.is_abelian()),
            }
        ),
    }

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        json.dumps(out, indent=_sage_const_2, sort_keys=True) + "\n", encoding="utf-8"
    )
    print("status=ok wrote", OUT)


if __name__ == "__main__":
    main()
