#!/usr/bin/env python3
"""Search for φ map giving a prescribed edge-orbit pattern under Aut(W33).

The target pattern specifies the sizes of orbits of the 240-edge set under
the action induced by the lift subgroup (i.e. the group generated by
Gperms).  The canonical φ produces a single 240-cycle, but the E6×A2
line action has pattern [36,27,27,27,1,1,1].  This tool randomly permutes
the root assignments and looks for a candidate matching the target pattern.

Usage:
    python tools/search_orbit_pattern.py --target 36,27,27,27,1,1,1 --trials 1000

"""
from __future__ import annotations

import json, random
from pathlib import Path
from typing import List, Tuple

ROOT = Path(__file__).resolve().parents[1]
import sys
sys.path.insert(0, str(ROOT))

from tools.compute_phi_lift_subgroup import edge_action_orbits
from tools.compute_phi_sign_gauge import load_root_list, compute_sign_gauge  # type: ignore
from tools.compute_phi_lift_subgroup import compute_lift_for_roots

import argparse
parser = argparse.ArgumentParser()
parser.add_argument("--target", help="comma-separated orbit sizes", required=True)
parser.add_argument("--trials", type=int, default=1000)
args = parser.parse_args()

target = sorted(int(x) for x in args.target.split(","))

# load canonical map
edges_sorted, root_list0 = load_root_list(ROOT / "artifacts" / "edge_to_e8_root.json")
m = len(root_list0)
assert m == 240

for t in range(args.trials):
    perm = list(range(m))
    random.shuffle(perm)
    candidate = [root_list0[j] for j in perm]
    orbits = sorted(edge_action_orbits(candidate))
    if orbits == target:
        raw = compute_lift_for_roots(candidate)
        signvec, signed, gauged = compute_sign_gauge(candidate)
        print(f"found matching pattern at trial {t}; raw lift {raw}, gauged {gauged}")
        out = {str(edges_sorted[k]): list(candidate[k]) for k in range(m)}
        (ROOT / "artifacts" / "orbit_pattern_candidate.json").write_text(json.dumps(out, indent=2))
        (ROOT / "artifacts" / "sign_gauge_candidate.json").write_text(json.dumps(signvec, indent=2))
        break
    if t % 100 == 0:
        print(f"trial {t}, orbits {orbits[:3]}...")

print("done")
