#!/usr/bin/env python3
"""
Compute the **exact** Standard Model (SU3×SU2×U1_Y) decomposition of the E6 27-rep
in the repo's weight-basis export, then analyze the 45 cubic triads and the firewall cut.

This uses:
  - artifacts/e6_27rep_basis_export/Cartan_mats.npy  (diagonal Cartan on the 27 weights)
  - tools/toe_dynamics.py  (canonical Schläfli skew/meet graph + firewall bad triangles)

Key outputs:
  1) A fully explicit dictionary: vertex i∈{0..26} -> {field, (SU3,SU2,Y), (Qψ,Qχ), ...}
     where Qψ is the E6→SO(10)×U(1)ψ charge (27 = 16_1 + 10_-2 + 1_4).
  2) The 45 "cubic triads" = triangles in the **meet** graph (Schläfli complement),
     which satisfy exact E6 weight conservation: w_a + w_b + w_c = 0.
  3) The firewall forbids **exactly 9** of those 45 triads (the 9 bad triangles),
     and we classify the forbidden couplings in SM field-language.

Outputs:
  - artifacts/toe_sm_decomposition_27.json
  - artifacts/toe_sm_decomposition_27.md
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import sys
from dataclasses import dataclass
from fractions import Fraction
from pathlib import Path
from typing import Dict, List, Sequence, Tuple

import numpy as np

ROOT = Path(__file__).resolve().parents[1]


def _load_module(path: Path, name: str):
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Failed to import {name} from {path}")
    mod = importlib.util.module_from_spec(spec)
    sys.modules[name] = mod
    spec.loader.exec_module(mod)
    return mod


toe_dynamics = _load_module(ROOT / "tools" / "toe_dynamics.py", "toe_dynamics")


def _write_json(path: Path, data: Dict[str, object]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, sort_keys=True), encoding="utf-8")


def _write_md(path: Path, lines: List[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


E6_CARTAN = np.array(
    [
        [2, -1, 0, 0, 0, 0],
        [-1, 2, -1, 0, 0, 0],
        [0, -1, 2, -1, -1, 0],
        [0, 0, -1, 2, 0, 0],
        [0, 0, -1, 0, 2, -1],
        [0, 0, 0, 0, -1, 2],
    ],
    dtype=int,
)


def _fund_coweight(idx: int) -> List[Fraction]:
    """Return ω_idx^∨ (fundamental coweight) in the simple-coroot basis coefficients."""
    e = np.zeros(6, dtype=float)
    e[int(idx)] = 1.0
    t = np.linalg.inv(E6_CARTAN.T) @ e
    return [Fraction(x).limit_denominator() for x in t.tolist()]


def _dot_frac(w: Sequence[int], t: Sequence[Fraction]) -> Fraction:
    s = Fraction(0, 1)
    for wi, ti in zip(w, t):
        s += Fraction(int(wi), 1) * ti
    return s


def _compute_weights_27() -> np.ndarray:
    cartan = np.load(
        ROOT / "artifacts" / "e6_27rep_basis_export" / "Cartan_mats.npy"
    ).astype(np.complex128)
    w = np.stack(
        [np.real_if_close(np.diag(cartan[i]), tol=1e-9) for i in range(6)],
        axis=1,
    ).astype(int)
    if w.shape != (27, 6):
        raise RuntimeError("Unexpected 27-weight shape")
    return w


def _sm_quantum_numbers(w27: np.ndarray) -> Tuple[List[str], List[str], np.ndarray]:
    """Return (rep3, rep2, Y6) for each vertex."""
    # SU(3)_C: choose A2 in SU(5) as simple coroots H1,H2 (E6 indices 1,2).
    su3_weights = {
        (1, 0): "3",
        (-1, 1): "3",
        (0, -1): "3",
        (0, 1): "3bar",
        (1, -1): "3bar",
        (-1, 0): "3bar",
        (0, 0): "1",
    }
    rep3_raw = [
        su3_weights.get(tuple(int(x) for x in row.tolist()), "?")
        for row in w27[:, [1, 2]]
    ]
    # Physical convention: swap 3<->3bar so that Q is in "3" and u^c in "3bar".
    swap = {"3": "3bar", "3bar": "3", "1": "1", "?": "?"}
    rep3 = [swap[r] for r in rep3_raw]

    # SU(2)_L: choose the A1 generated by simple root index 5 (E6 node 5).
    rep2 = [
        "2" if abs(int(x)) == 1 else ("1" if int(x) == 0 else "?") for x in w27[:, 5]
    ]

    # Hypercharge Y in 1/6 units from SU(5): coefficients on (α1,α2,α4,α5) coroots = (1/3,2/3,1,1/2).
    coeff = np.array([0.0, 1.0 / 3.0, 2.0 / 3.0, 0.0, 1.0, 1.0 / 2.0], dtype=float)
    y6 = np.rint((w27 @ coeff) * 6.0).astype(int)
    return rep3, rep2, y6


@dataclass(frozen=True)
class Field:
    name: str
    idxs: List[int]


def _field_assignment(
    rep3: List[str], rep2: List[str], y6: np.ndarray, qpsi3: List[int]
) -> Dict[int, str]:
    """Return i->field_label."""
    by = {}

    def pick(r3: str, r2: str, y: int, q: int) -> List[int]:
        return [
            i
            for i in range(27)
            if (rep3[i], rep2[i], int(y6[i]), int(qpsi3[i])) == (r3, r2, int(y), int(q))
        ]

    # E6 -> SO(10)×U(1)_ψ: qpsi3 in {1,-2,4} for 16,10,1.
    Q = pick("3", "2", 1, 1)
    uC = pick("3bar", "1", -4, 1)
    dC = pick("3bar", "1", 2, 1)
    L = pick("1", "2", -3, 1)
    eC = pick("1", "1", 6, 1)
    nuC = pick("1", "1", 0, 1)

    D = pick("3", "1", -2, -2)
    Dbar = pick("3bar", "1", 2, -2)
    Hu = pick("1", "2", 3, -2)
    Hd = pick("1", "2", -3, -2)
    S = pick("1", "1", 0, 4)

    for i in Q:
        by[i] = "Q"
    for i in uC:
        by[i] = "u^c"
    for i in dC:
        by[i] = "d^c"
    for i in L:
        by[i] = "L"
    for i in eC:
        by[i] = "e^c"
    for i in nuC:
        by[i] = "nu^c"
    for i in D:
        by[i] = "D"
    for i in Dbar:
        by[i] = "Dbar"
    for i in Hu:
        by[i] = "H_u"
    for i in Hd:
        by[i] = "H_d"
    for i in S:
        by[i] = "S"

    if len(by) != 27:
        missing = [i for i in range(27) if i not in by]
        raise RuntimeError(
            f"Failed to assign all 27 weights to fields; missing={missing}"
        )
    return by


def main(argv: Sequence[str] | None = None) -> None:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        "--out-json",
        type=Path,
        default=ROOT / "artifacts" / "toe_sm_decomposition_27.json",
    )
    p.add_argument(
        "--out-md", type=Path, default=ROOT / "artifacts" / "toe_sm_decomposition_27.md"
    )
    args = p.parse_args(list(argv) if argv is not None else None)

    w27 = _compute_weights_27()
    rep3, rep2, y6 = _sm_quantum_numbers(w27)

    omega_psi = _fund_coweight(0)  # gives 16_1 + 10_-2 + 1_4 after x3 scaling
    omega_chi = _fund_coweight(3)  # convenient second U(1) for SU(5) chain
    qpsi = [_dot_frac(w27[i], omega_psi) for i in range(27)]
    qchi = [_dot_frac(w27[i], omega_chi) for i in range(27)]
    qpsi3 = [int(x * 3) for x in qpsi]
    # qchi is already integral in this basis (0,±1), keep as int.
    qchi1 = [int(x) for x in qchi]

    field_by_i = _field_assignment(rep3, rep2, y6, qpsi3)

    # Triads = meet-graph triangles.
    skew, meet = toe_dynamics.load_schlafli_graph()
    triads: List[Tuple[int, int, int]] = []
    for a in range(27):
        for b in range(a + 1, 27):
            if not bool(meet[a, b]):
                continue
            for c in range(b + 1, 27):
                if bool(meet[a, c]) and bool(meet[b, c]):
                    triads.append((a, b, c))
    if len(triads) != 45:
        raise RuntimeError(
            f"Expected 45 cubic triads (meet triangles), got {len(triads)}"
        )
    # Weight conservation check: w_a+w_b+w_c=0 for all triads.
    for a, b, c in triads:
        if not np.all((w27[a] + w27[b] + w27[c]) == 0):
            raise RuntimeError(
                "Found a meet-triangle that does not conserve E6 weights"
            )

    fw = toe_dynamics.load_firewall_bad_edges()
    bad_tri = {tuple(sorted(t)) for t in fw.triangles}
    if len(bad_tri) != 9:
        raise RuntimeError("Expected 9 firewall bad triangles")
    # Each bad triangle must be a cubic triad.
    triad_set = {tuple(sorted(t)) for t in triads}
    if not bad_tri.issubset(triad_set):
        raise RuntimeError("Firewall bad triangles are not a subset of cubic triads")

    # Classify triads by field triple.
    from collections import Counter

    type_counts = Counter()
    type_forbidden = Counter()
    qpsi_pattern_counts = Counter()
    qpsi_pattern_forbidden = Counter()
    triad_records = []
    for a, b, c in triads:
        labs = [field_by_i[a], field_by_i[b], field_by_i[c]]
        key = tuple(sorted(labs))
        is_forbidden = tuple(sorted((a, b, c))) in bad_tri
        type_counts[key] += 1
        if is_forbidden:
            type_forbidden[key] += 1
        qpat = tuple(sorted((qpsi3[a], qpsi3[b], qpsi3[c])))
        qpsi_pattern_counts[qpat] += 1
        if is_forbidden:
            qpsi_pattern_forbidden[qpat] += 1
        triad_records.append(
            {
                "verts": [a, b, c],
                "fields": labs,
                "forbidden": bool(is_forbidden),
            }
        )

    # Parity annotations from the mapping artifact (optional).
    parity_by_scheme: Dict[str, Dict[Tuple[int, int, int], int]] = {}
    mapping_path = ROOT / "artifacts" / "firewall_bad_triads_mapping.json"
    if mapping_path.exists():
        mapping = json.loads(mapping_path.read_text(encoding="utf-8"))
        sel = mapping.get("selection_parity_on_bad_triads")
        if isinstance(sel, dict):
            for scheme, blob in sel.items():
                if not isinstance(blob, dict):
                    continue
                tri_list = blob.get("bad_triads")
                if not isinstance(tri_list, list):
                    continue
                m: Dict[Tuple[int, int, int], int] = {}
                for entry in tri_list:
                    if not isinstance(entry, dict):
                        continue
                    tri = entry.get("triad")
                    par = entry.get("parity")
                    if not (
                        isinstance(tri, list) and len(tri) == 3 and isinstance(par, int)
                    ):
                        continue
                    t = tuple(sorted((int(tri[0]), int(tri[1]), int(tri[2]))))
                    m[t] = int(par)
                if m:
                    parity_by_scheme[str(scheme)] = m

    # Add parity + Qpsi patterns to triad records.
    for rec in triad_records:
        t = tuple(sorted(int(x) for x in rec["verts"]))
        rec["qpsi3_pattern"] = sorted([int(qpsi3[i]) for i in rec["verts"]])
        if rec["forbidden"]:
            rec["parity"] = {
                k: int(v[t]) for k, v in parity_by_scheme.items() if t in v
            }
        else:
            rec["parity"] = {}

    # The 9 forbidden triads should partition the 27 vertices (cover each exactly once).
    forb_verts = [i for r in triad_records if r["forbidden"] for i in r["verts"]]
    forb_partition_ok = (len(forb_verts) == 27) and (len(set(forb_verts)) == 27)

    out: Dict[str, object] = {
        "status": "ok",
        "notes": {
            "hypercharge": "Y is computed in 1/6 units from the SU(5) A4 chain (α1-α2-α4-α5), with Y(Hα1..)=+(-2,-4,-6,-3)/6 in SU5-coroot coordinates.",
            "u1_psi": "Qψ is ω0^∨ (fundamental coweight for the E6 node whose deletion yields D5), scaled by 3 to give {1,-2,4}.",
            "triads": "The 45 cubic triads are exactly the meet-graph triangles; they conserve the full E6 Cartan weight vector.",
        },
        "cartan": {"e6_cartan_matrix": E6_CARTAN.tolist()},
        "per_vertex": [
            {
                "i": i,
                "w": [int(x) for x in w27[i].tolist()],
                "su3": rep3[i],
                "su2": rep2[i],
                "Y6": int(y6[i]),
                "Q6": int(3 * int(w27[i, 5]) + int(y6[i])),  # Q = T3 + Y, with T3=w5/2
                "Qpsi3": int(qpsi3[i]),
                "Qchi": int(qchi1[i]),
                "field": field_by_i[i],
            }
            for i in range(27)
        ],
        "triads": {
            "total": 45,
            "forbidden": 9,
            "forbidden_partitions_vertices": bool(forb_partition_ok),
            "type_counts": [
                {
                    "fields": list(k),
                    "count": int(v),
                    "forbidden": int(type_forbidden.get(k, 0)),
                }
                for k, v in sorted(type_counts.items(), key=lambda kv: (-kv[1], kv[0]))
            ],
            "qpsi3_pattern_counts": [
                {
                    "qpsi3": list(k),
                    "count": int(v),
                    "forbidden": int(qpsi_pattern_forbidden.get(k, 0)),
                }
                for k, v in sorted(
                    qpsi_pattern_counts.items(), key=lambda kv: (-kv[1], kv[0])
                )
            ],
            "records": triad_records,
            "firewall_bad_triangles": [list(t) for t in sorted(bad_tri)],
        },
    }
    _write_json(args.out_json, out)

    lines: List[str] = []
    lines.append("# TOE: SM Decomposition + Cubic Triads + Firewall Cut (27-rep)")
    lines.append("")
    lines.append("## SM Multiplet Counts (one 27 of E6)")
    # Count by (field)
    from collections import Counter

    c_field = Counter(field_by_i.values())
    for k, v in sorted(c_field.items()):
        lines.append(f"- {k}: `{v}`")
    lines.append("")
    lines.append("## Triad Types (cubic invariant terms)")
    for row in out["triads"]["type_counts"]:
        lines.append(
            f"- {row['fields']}: total `{row['count']}` forbidden `{row['forbidden']}`"
        )
    lines.append("")
    lines.append("## Forbidden Triads (9)")
    for rec in sorted(
        [r for r in triad_records if r["forbidden"]], key=lambda r: r["verts"]
    ):
        lines.append(f"- verts {rec['verts']}: {rec['fields']}")
    lines.append("")
    lines.append(f"- JSON: `{args.out_json}`")
    _write_md(args.out_md, lines)

    print(f"Wrote {args.out_json}")
    print(f"Wrote {args.out_md}")


if __name__ == "__main__":
    main()
