#!/usr/bin/env python3
"""Generate a machine-checkable universalization report for the s12 model."""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
import tools.s12_universal_algebra as s12


def _render_markdown(report: dict) -> str:
    dims = report["algebra_dimensions"]
    laws = report["universal_grade_laws"]
    checks = report["exhaustive_checks"]

    lines = []
    lines.append("# s12 Universalization Report")
    lines.append("")
    lines.append(f"- Model: `{report.get('model')}`")
    lines.append(
        "- Code size / dims: `{} / {} + {} + {}`".format(
            report.get("code_size"),
            dims.get("grade0"),
            dims.get("grade1"),
            dims.get("grade2"),
        )
    )
    lines.append(
        "- Quotient dimension (`g1+g2`): `{}`".format(dims.get("quotient_by_grade0"))
    )
    lines.append("")
    lines.append("## Universal Grade Laws")
    lines.append("")
    lines.append(
        "- Jacobi coefficient identity (Lie condition): `{}`".format(
            laws.get("jacobi_coefficient_identity_holds")
        )
    )
    lines.append(
        "- Jacobi grade-failure count: `{}`".format(laws.get("jacobi_failure_count"))
    )
    lines.append(
        "- `ad^3` coefficient identity: `{}`".format(
            laws.get("ad3_coefficient_identity_holds")
        )
    )
    lines.append(
        "- Jordan triple symmetry (grade level): `{}`".format(
            laws.get("jordan_triple_xz_symmetry_holds")
        )
    )
    lines.append("")
    lines.append("## Exhaustive / Sampled Checks")
    lines.append("")
    lines.append(
        "- `g1 x g1` symmetric: `{}` ({}/{})".format(
            checks["g1_g1_symmetric"]["holds"],
            checks["g1_g1_symmetric"]["pass"],
            checks["g1_g1_symmetric"]["total"],
        )
    )
    lines.append(
        "- `g2 x g2` symmetric: `{}` ({}/{})".format(
            checks["g2_g2_symmetric"]["holds"],
            checks["g2_g2_symmetric"]["pass"],
            checks["g2_g2_symmetric"]["total"],
        )
    )
    lines.append(
        "- `g1 x g2` antisymmetric: `{}` ({}/{})".format(
            checks["g1_g2_antisymmetric"]["holds"],
            checks["g1_g2_antisymmetric"]["pass"],
            checks["g1_g2_antisymmetric"]["total"],
        )
    )
    lines.append(
        "- `g0` central: `{}` ({}/{})".format(
            checks["g0_central"]["holds"],
            checks["g0_central"]["pass"],
            checks["g0_central"]["total"],
        )
    )
    lines.append(
        "- `ad^3=0` on `g1`: `{}` ({}/{})".format(
            checks["ad3_zero_on_g1"]["holds"],
            checks["ad3_zero_on_g1"]["pass"],
            checks["ad3_zero_on_g1"]["total"],
        )
    )
    lines.append(
        "- `ad^2` nontrivial count: `{}` / `{}`".format(
            checks["ad2_nontrivial_on_g1"]["nonzero_count"],
            checks["ad2_nontrivial_on_g1"]["total"],
        )
    )
    lines.append(
        "- Jordan triple symmetry sample: `{}` ({}/{})".format(
            checks["jordan_triple_xz_symmetry_sample"]["holds"],
            checks["jordan_triple_xz_symmetry_sample"]["pass"],
            checks["jordan_triple_xz_symmetry_sample"]["total"],
        )
    )
    if not laws.get("jacobi_coefficient_identity_holds", False):
        lines.append(
            "- Interpretation: grade laws are Jordan-Lie (Lie Jacobi is obstructed on a finite grade subset)."
        )
    lines.append("")
    lines.append(
        "Generated by `tools/universalize_s12_algebra.py` and core checks in "
        "`tools/s12_universal_algebra.py`."
    )
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--jordan-sample-limit", type=int, default=4000)
    parser.add_argument(
        "--out-json",
        type=Path,
        default=ROOT / "artifacts" / "s12_universalization_report.json",
    )
    parser.add_argument(
        "--out-md",
        type=Path,
        default=ROOT / "docs" / "S12_UNIVERSALIZATION_2026_02_11.md",
    )
    args = parser.parse_args()

    report = s12.build_s12_universal_report(
        jordan_sample_limit=int(args.jordan_sample_limit)
    )
    args.out_json.parent.mkdir(parents=True, exist_ok=True)
    args.out_json.write_text(json.dumps(report, indent=2), encoding="utf-8")

    rendered = _render_markdown(report)
    args.out_md.parent.mkdir(parents=True, exist_ok=True)
    args.out_md.write_text(rendered, encoding="utf-8")

    print(f"Wrote {args.out_json}")
    print(f"Wrote {args.out_md}")


if __name__ == "__main__":
    main()
