#!/usr/bin/env python3
"""
Verify the W(E6) permutation action on a 27-orbit preserves the 27-line configuration.

We construct:
  - one 27-orbit of E8 roots under W(E6),
  - the Schläfli skew graph (ip=1) and meet graph (ip=0),
  - the 6 simple reflections of E6 (reflections in E6_SIMPLE_ROOTS),
  - the induced permutations on the 27 vertices,
  - the generated permutation group size,
  - preservation of adjacency and tritangent planes (meet-graph triangles).

Expected:
  - |W(E6)| = 51840
  - The induced action is faithful on the 27 lines and preserves the Schläfli configuration.
"""

from __future__ import annotations

import importlib.util
from collections import Counter, deque
from pathlib import Path
from typing import Dict, List, Set, Tuple

import numpy as np

ROOT = Path(__file__).resolve().parents[1]


def _load_compute_double_sixes():
    path = ROOT / "tools" / "compute_double_sixes.py"
    spec = importlib.util.spec_from_file_location("compute_double_sixes", path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Failed to load module from {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


_cds = _load_compute_double_sixes()


def triangles_in_graph(adj: np.ndarray) -> Set[Tuple[int, int, int]]:
    n = adj.shape[0]
    out: Set[Tuple[int, int, int]] = set()
    for i in range(n):
        for j in range(i + 1, n):
            if not adj[i, j]:
                continue
            for k in range(j + 1, n):
                if adj[i, k] and adj[j, k]:
                    out.add((i, j, k))
    return out


def compose(p: Tuple[int, ...], q: Tuple[int, ...]) -> Tuple[int, ...]:
    # p∘q
    return tuple(p[i] for i in q)


def invert(p: Tuple[int, ...]) -> Tuple[int, ...]:
    inv = [0] * len(p)
    for i, j in enumerate(p):
        inv[j] = i
    return tuple(inv)


def main() -> None:
    roots = _cds.construct_e8_roots()
    we6_orbits = _cds.compute_we6_orbits(roots)
    orbit27 = [o for o in we6_orbits if len(o) == 27][0]

    local_roots = roots[orbit27]
    # Map snapped root vectors -> local index
    key_to_local: Dict[Tuple[float, ...], int] = {}
    for i in range(27):
        key_to_local[_cds.snap_to_lattice(local_roots[i])] = i

    gram = np.rint(local_roots @ local_roots.T).astype(int)
    skew = gram == 1
    meet = gram == 0
    np.fill_diagonal(skew, False)
    np.fill_diagonal(meet, False)
    tris = triangles_in_graph(meet)
    assert len(tris) == 45

    # Build the 6 simple reflection generators as permutations on 27 vertices.
    gens: List[Tuple[int, ...]] = []
    for alpha in _cds.E6_SIMPLE_ROOTS:
        perm = []
        for i in range(27):
            v = _cds.weyl_reflect(local_roots[i], alpha)
            k = _cds.snap_to_lattice(v)
            j = key_to_local.get(k)
            if j is None:
                raise RuntimeError("Reflection moved vertex out of the 27-orbit")
            perm.append(j)
        p = tuple(perm)
        if sorted(p) != list(range(27)):
            raise RuntimeError("Generator is not a permutation")
        gens.append(p)

    # BFS closure of group generated by gens.
    idp = tuple(range(27))
    seen = {idp}
    q = deque([idp])
    group = [idp]
    while q:
        g = q.popleft()
        for h in gens:
            gh = compose(h, g)
            if gh not in seen:
                seen.add(gh)
                q.append(gh)
                group.append(gh)
    print("Generated permutation group size:", len(group))

    # Check adjacency and triangle preservation by generators (sufficient).
    def permute_adj(adj: np.ndarray, p: Tuple[int, ...]) -> np.ndarray:
        idx = np.array(p, dtype=int)
        return adj[idx][:, idx]

    for p in gens:
        assert np.array_equal(permute_adj(skew, p), skew)
        assert np.array_equal(permute_adj(meet, p), meet)
        invp = invert(p)
        for i, j, k in tris:
            img = tuple(sorted((p[i], p[j], p[k])))
            assert img in tris
        # also check inverse action
        for i, j, k in tris:
            img = tuple(sorted((invp[i], invp[j], invp[k])))
            assert img in tris

    # If the group is W(E6), we expect order 51840.
    print("Expected |W(E6)| =", 51840)
    print("Order matches? ", len(group) == 51840)


if __name__ == "__main__":
    main()
